volta-cli/volta

- Cargo.lock
- Cargo.toml
- crates/node-archive/Cargo.toml
- crates/node-archive/src/lib.rs
- crates/node-archive/src/source.rs
- crates/node-archive/src/tarball.rs
- crates/node-archive/src/zip.rs
- crates/notion-core/Cargo.toml
- crates/notion-core/src/lib.rs
- crates/notion-core/src/path/mod.rs
- crates/notion-core/src/path/windows.rs
- crates/notion-core/src/tool.rs
new crate/workspace feature for building cross-platform docs: `universal-docs`
command for building the docs: `RUSTDOCFLAGS=--document-private-items cargo doc --features universal-docs --all --no-deps`
> new crate/workspace feature for building cross-platform docs

- crates/notion-core/src/style.rs
Clean up the comments and progress bar message format based on comments for https://github.com/notion-cli/notion/pull/53.
Compiled and tested install locally.
> Follow-up with cleanup after #53

- crates/notion-core/src/catalog.rs
- crates/notion-core/src/style.rs
This adds a progress spinner to give an indication of what is happening when we are fetching the public node registry. Otherwise there is a visible pause with no feedback about what is going on.
This closes #33
> Add spinner to indicate fetching the public node registry

- crates/node-archive/src/lib.rs
- crates/notion-core/src/catalog.rs
- crates/notion-core/src/config.rs
- crates/notion-core/src/installer/node.rs
- crates/notion-core/src/lib.rs
- crates/notion-core/src/manifest.rs
- crates/notion-core/src/plugin.rs
- crates/notion-core/src/project.rs
- crates/notion-core/src/serial/catalog.rs
- crates/notion-core/src/serial/index.rs
- crates/notion-core/src/serial/mod.rs
- crates/notion-core/src/serial/version.rs
- crates/notion-core/src/session.rs
- crates/notion-core/src/tool.rs
- crates/notion-fail/src/lib.rs
- src/command/help.rs
- src/command/install.rs
- src/command/mod.rs
- src/command/use_.rs
I noticed this when working on code for events. The error message when the node version is not found was not being displayed to the user.
This changes the displayed message from this:
```
error: An unknown error has occurred
```
to this:
```
error: No Node version found for = 15.11.1
```
Looks like this fits into https://github.com/notion-cli/notion/issues/70
> Show a meaningful error message when node version is not found

- Cargo.lock
- crates/notion-core/src/style.rs
- crates/notion-core/src/tool.rs
- crates/notion-fail/Cargo.toml
- crates/notion-fail/src/lib.rs
- src/notion.rs
improved "unknown error" reporting:
- consistent for shims as well as notion executable
- can use `NOTION_DEV` (and `RUST_BACKTRACE`) env vars to get detailed reporting (useful for Notion implementers/maintainers)
> NOTION_DEV env var

- support/unix/build.sh
Currently running the build script errors when `release` is not set, even though it claims to be the default. This sets `target_dir` to `release` when it is not specified.
> Make 'release' the default build target

- .travis.yml
- Cargo.lock
- appveyor.yml
- crates/notion-fail/Cargo.toml
- crates/notion-fail/src/lib.rs
This changes CI to use `cargo test --all`, which runs tests in src/ and crates/, as well as rustdoc. Currently only tests in src/ are run.
I had to modify some examples in the notion-fail docs to get them to compile. There are a couple that I haven't been able to fix , so just marked as `compile_fail` for now so that the tests pass.
```
$ cargo test --all
Compiling notion-fail v0.1.0 (file:///Users/mistewar/fpe/notion/notion/crates/notion-fail)
Compiling notion-core v0.1.0 (file:///Users/mistewar/fpe/notion/notion/crates/notion-core)
Compiling notion v0.1.0 (file:///Users/mistewar/fpe/notion/notion)
Finished dev [unoptimized + debuginfo] target(s) in 7.87 secs
Running target/debug/deps/node_archive-a8af169d88f57520
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 …
```
> Run all tests in CI

- crates/notion-core/fixtures/basic/package.json
- crates/notion-core/src/manifest.rs
- crates/notion-core/src/serial/manifest.rs
(Breaking this out as a small change, as part of the 3rd party executables work.)
In the manifest, it already includes some code to get the `devDependencies` - I just added the rest of the code to expose that as `dev_dependencies`.
As a bonus, I added some happy path tests for things that are pulled out of package.json.
> Expose dev_dependencies in manifest

- crates/notion-core/fixtures/basic/node_modules/@namespace/some-dep/package.json
- crates/notion-core/fixtures/basic/node_modules/eslint/package.json
- crates/notion-core/fixtures/basic/node_modules/rsvp/package.json
- crates/notion-core/fixtures/basic/node_modules/typescript/package.json
- crates/notion-core/src/lib.rs
- crates/notion-core/src/package_info.rs
- crates/notion-core/src/serial/mod.rs
- crates/notion-core/src/serial/package.rs
This adds a new deserializer to handle the "bin" section in package.json. This can be either a map or string, and serde can't automatically handle that, so it needs a custom deserializer.
This is separate from the deserialization done in notion-core::manifest, because this will operate on project dependencies and should not require the `"notion"` section to be present in package.json.
> Deserialize the "bin" section from package.json

- .gitignore
- Cargo.toml
- crates/notion-core/src/catalog.rs
- crates/notion-core/src/config.rs
- crates/notion-core/src/env.rs
- crates/notion-core/src/installer/mod.rs
- crates/notion-core/src/installer/node.rs
- crates/notion-core/src/installer/yarn.rs
- crates/notion-core/src/path/mod.rs
- crates/notion-core/src/path/unix.rs
- crates/notion-core/src/plugin.rs
- crates/notion-core/src/serial/catalog.rs
- crates/notion-core/src/serial/config.rs
- crates/notion-core/src/serial/plugin.rs
- crates/notion-core/src/session.rs
- crates/notion-core/src/tool.rs
- package.json
- src/command/current.rs
- src/yarn.rs
- support/unix/build.sh
- support/unix/install.sh.in
Enable yarn support as a new tool that follows the same model as node.
Implements yarn version `catalog`, yarn `installer` and `shim`.
Since yarnpkg.com doesn't provide an API for released versions and some limitation with GitHub API to fetch versions and download, we decided to use `notion-cli/yarn-releases` git repo till we figure out a better solution.
Released versions: `https://github.com/notion-cli/yarn-releases/raw/master/index.json`
Download tarball URL: `https://github.com/notion-cli/yarn-releases/raw/master/dist/yarn-v{$version}.tar.gz`
This PR is for the following issues in MVP milestone: #73 #61 #67
> Adding Yarn support to notion

- crates/notion-core/fixtures/basic/node_modules/.bin/rsvp
- crates/notion-core/fixtures/basic/node_modules/@namespaced/something-else/package.json
- crates/notion-core/fixtures/basic/rsvp
- crates/notion-core/src/env.rs
- crates/notion-core/src/path/unix.rs
- crates/notion-core/src/path/windows.rs
- crates/notion-core/src/project.rs
- crates/notion-core/src/session.rs
- crates/notion-core/src/tool.rs
This implements the logic to handle shims to 3rd-party executables.
These are executables that can be installed
* locally (in `node_modules/.bin`),
* globally with the version of node installed using Notion,
* and/or globally with the system node
This is the priority used to decide what to execute:
1) If the executable is installed locally, and a direct dependency of the current project, then we execute that. We only execute direct dependencies because npm and yarn install executables for everything installed in `node_modules/`, not just direct dependencies. Exposing all of those on the path would be a security risk as well as confusing to debug.
2) If node is configured with Notion (using `notion use`, or Notion config in the project), we execute the globally-installed executable for the …
> Logic to handle shims for 3rd party executables

- crates/notion-core/src/catalog.rs
- crates/notion-core/src/installer/error.rs
- crates/notion-core/src/installer/mod.rs
- crates/notion-core/src/installer/node.rs
- crates/notion-core/src/installer/yarn.rs
- crates/notion-core/src/package_info.rs
- crates/notion-core/src/project.rs
- crates/notion-core/src/serial/version.rs
- crates/notion-core/src/style.rs
- crates/notion-core/src/tool.rs
- src/command/config.rs
- src/command/uninstall.rs
- src/error.rs
- src/notion.rs
I implemented error messages for common error cases where we usually get `error: an internal error occurred`, or `thread 'main' panicked at 'not yet implemented'`, which are not user-friendly or helpful.
Instead, we get these errors now:
```
$ notion install 6.5.4.3
error: the given version requirement is invalid
```
```
$ notion config list
error: command `list` is not yet implemented
```
```
$ notion install 8
error: Could not fetch public registry
https://nodejs.org/dist/index.json: failed to lookup address information: nodename nor servname provided, or not known
```
```
$ notion install 9
error: Failed to download version 9.11.2
https://nodejs.org/dist/v9.11.2/node-v9.11.2-darwin-x64.tar.gz: failed to lookup address information: nodename nor servname provided, or not known
```
```
$ …
```
> Better messages for common errors

- crates/notion-core/fixtures/basic/package.json
- crates/notion-core/src/serial/manifest.rs
- package.json
The mental model of static linking is that you're specifying the version of the toolchain you want your package to be executed with. So it's more general than just "tell Notion what to do" -- it's really _documenting how your project is meant to be run_. So this PR renames the key to `"toolchain"` to express this intent.
> Rename the `package.json` key to `"toolchain"`

- crates/notion-core/src/path/windows.rs
The "Publish" step is currently failing on travis, so all the build badges on https://github.com/notion-cli/notion are red - that's not a good look when we are getting ready to MVP this.
```
$ rustup install nightly
$ rustup run nightly cargo doc --features universal-docs -p notion-core --no-deps
```
I'm not sure why this is failing, since this is already using `#[doc(cfg(windows))]` for the windows module. All I did was split up the usage of `std::os::windows` so the compilation stops failing.
> Fix so publishing universal docs stops failing

- Cargo.lock
- crates/notion-core/Cargo.toml
- crates/notion-core/fixtures/no_toolchain/package.json
- crates/notion-core/src/catalog.rs
- crates/notion-core/src/distro/node.rs
- crates/notion-core/src/distro/yarn.rs
- crates/notion-core/src/lib.rs
- crates/notion-core/src/manifest.rs
- crates/notion-core/src/project.rs
- crates/notion-core/src/serial/manifest.rs
- crates/notion-core/src/session.rs
- crates/notion-core/src/tool.rs
- src/command/current.rs
- src/command/shim.rs
- src/command/use_.rs
This implements `notion use node <version>` and `notion use yarn <version>`, which pins those versions to the `"toolchain"` in package.json.
There are a lot of changes here because I re-worked some of the `Manifest` code so that it generates a Manifest even if the "toolchain" has not been pinned yet. That should make it easier to do https://github.com/notion-cli/notion/issues/85, which I will do at some point as a follow-up.
Closes https://github.com/notion-cli/notion/issues/115
> Implement new version of `notion use`

- Cargo.lock
- Cargo.toml
- crates/notion-core/Cargo.toml
- crates/notion-core/src/catalog.rs
- crates/notion-core/src/distro/error.rs
- crates/notion-core/src/event.rs
- crates/notion-core/src/lib.rs
- crates/notion-core/src/manifest.rs
- crates/notion-core/src/path/unix.rs
- crates/notion-core/src/project.rs
- crates/notion-core/src/serial/version.rs
- crates/notion-core/src/session.rs
- crates/notion-core/src/shell/mod.rs
- crates/notion-core/src/shim.rs
- crates/notion-core/src/tool.rs
- crates/notion-fail-derive/Cargo.toml
- crates/notion-fail-derive/src/lib.rs
- crates/notion-fail/Cargo.toml
- crates/notion-fail/src/lib.rs
- src/command/current.rs
- src/command/deactivate.rs
- src/command/fetch.rs
- src/command/help.rs
- src/command/install.rs
- src/command/shim.rs
- src/command/use_.rs
- src/command/version.rs
- src/error.rs
- src/notion.rs
This is an implementation of the ["Exit codes" RFC](https://github.com/notion-cli/rfcs/pull/20).  It consists of two primary changes:
* Implement `ExitCode` enum and convert existing errors and error-handling code to use it.
* Add a derivation for the `NotionFail` trait.
> Exit codes

- crates/notion-core/src/serial/version.rs
So users can do things like `notion use node v1.2`, which some people expect
> Allow optional `v` prefix for version specifiers

- src/command/install.rs
Show an error that this is unimplemented, because panicking is not helpful 😃 
Also, add some verbiage to the help text about which tools are currently implemented.
> Throw unimplemented error for `notion install sometool`

- dev/unix/install.sh.in
Using the `-f` option in `ln` to prevent the `File exists` errors for `npm` and `npx` when installing Notion a second time.
> Prevent "File exists" errors on reinstall

- crates/notion-core/src/catalog.rs
- src/command/fetch.rs
- src/command/install.rs
- src/command/use_.rs
notion will resolve to a version that is the latest released version of node/yarn
implemented latest for following notion commands:
`notion fetch node latest`
`notion fetch yarn latest`
`notion install node latest`
`notion install yarn latest`
`notion use node latest`
`notion use yarn latest`
moved node resolve request code out from `resolve_public` to a new method `resolve_node_versions` which can be reused for `latest`.
Yarn has a API to simply fetch the latest version number `https://yarnpkg.com/latest-version`, but couldn't find such endpoint for node, so ended up finding the latest version from `https://nodejs.org/dist/index.json`
> support "latest" to be specified as version for node and yarn

- Cargo.lock
- Cargo.toml
- crates/notion-core/src/catalog/mod.rs
- crates/notion-core/src/catalog/serial.rs
- crates/notion-core/src/config/mod.rs
- crates/notion-core/src/config/serial.rs
- crates/notion-core/src/env.rs
- crates/notion-core/src/fs.rs
- crates/notion-core/src/project.rs
- crates/notion-core/src/session.rs
- crates/notion-core/src/version/mod.rs
- crates/notion-core/src/version/serial.rs
- crates/notion-fail-derive/src/lib.rs
- src/command/current.rs
- src/command/fetch.rs
- src/command/install.rs
- src/command/use_.rs
- src/notion.rs
A few little fixes:
- Fixes the `latest` calculation which I broke in #139. (@mikrostew's test harnesses would've caught this!).
- Make the version argument to `notion install` optional, and default to `latest`.
- Stores the index as a `Vec` instead of a `BTreeMap` since we don't use any map methods; we're only operating on an iterator.
- A couple method renames to align with current terminology.
> Improvements to `latest`

- crates/notion-core/src/manifest/serial.rs
We are serializing the `"author"` field in package.json, but not using it for anything, so just remove it.
Closes #155
> Stop serializing the "author" field in package.json

- Cargo.lock
- crates/notion-core/Cargo.toml
The changes that we needed (https://github.com/DarkEld3r/os_info/pull/88) have been released in 1.1.0.
> Update os_info to released version.

- README.md
This adds the current test command to the README while we work on a better solution over in https://github.com/notion-cli/notion/issues/168.
> Add documentation for running the tests to the README.

- Cargo.toml
- crates/notion-core/src/manifest/mod.rs
- crates/notion-core/src/manifest/tests.rs
- crates/notion-core/src/project.rs
- crates/notion-core/src/shim.rs
- crates/notion-core/src/tool.rs
- src/command/help.rs
- src/command/mod.rs
- src/command/shim.rs
- src/command/use_.rs
- src/notion.rs
This is a speculative implementation of [RFC 23](https://github.com/notion-cli/rfcs/pull/23).
A notable change with this PR is the grammar for the `notion shim` command, which has been moved behind the `notion-dev` feature flag.
* `notion shim` => `notion shim list`
* `notion shim foo` => `notion shim create foo`
* `notion shim foo --delete` => `notion shim delete foo`
> Project autoshim

- Cargo.lock
- crates/notion-core/Cargo.toml
The changes in the fork of lazycell have been incorporated with upstream and are included in version 1.2.0.
Closes https://github.com/notion-cli/notion/issues/137 by deciding _not_ to switch from lazycell to once_cell.
> Use released version of lazycell.

- crates/notion-core/src/shell/bash.rs
- crates/notion-core/src/shell/mod.rs
- src/command/deactivate.rs
- tests/acceptance/notion_deactivate.rs
Closes #193.
I also changed `Postscript::Path` to `Postscript::Deactivate` to more closely match what it's actually doing.
> `notion deacctivate` also unsets NOTION_HOME

- crates/notion-core/src/session.rs
Fixes #202 
The `prepare_image` function was checking if the `node` version exists in the catalog before fetching it, however it was only checking if `yarn` was set on the project, not whether it had already been downloaded. This was causing the Yarn index to be re-fetched on every invocation, showing a spinner with `Fetching public registry: ...` before executing any command.
Updated `prepare_image` to _also_ check `if !catalog.yarn.contains(yarn_version)`, in the same way that Node is checked, before executing the fetch.
Tested locally with a project that was showing the `Fetching ...` spinner and verified that no spinner is shown when executing a `node` or `yarn` command.
> Prevent unneeded fetching of Yarn version / index #202

- crates/notion-core/src/path/unix.rs
- crates/notion-core/src/path/windows.rs
- crates/notion-core/src/toolchain/mod.rs
- crates/notion-core/src/toolchain/serial.rs
- tests/acceptance/notion_current.rs
- tests/acceptance/support/sandbox.rs
> Use JSON for internal platform config, to avoid TOML issues

- crates/archive/src/tarball.rs
- crates/notion-core/src/distro/yarn.rs
- crates/notion-core/src/inventory/mod.rs
- crates/notion-core/src/inventory/serial.rs
- tests/acceptance/notion_use.rs
- tests/acceptance/support/sandbox.rs
Fixes #214.
This PR streamlines the implementation of progress reporting for fetching and unpacking tarballs: it eliminates the unnecessary extra `HEAD` request and gets both the `Content-Length` and `Accepts` headers from a `GET` request of the full payload. Since [reqwest fetches payloads by-need](https://twitter.com/seanmonstar/status/1073634882469781504), we can kick of a second `GET` request to compute the uncompressed size before fetching the full tarball payload.
This means once we ship this, we no longer need to maintain the [Yarn release proxy repo](https://github.com/notion-cli/yarn-releases/), because the implementation just fetches releases directly from the GitHub releases API of the official public Yarn repo.
> Robust progress

- Cargo.lock
- crates/notion-core/Cargo.toml
- crates/notion-core/src/image/mod.rs
- crates/notion-core/src/lib.rs
- crates/notion-core/src/path/mod.rs
- crates/notion-core/src/path/unix.rs
- crates/notion-core/src/path/windows.rs
- tests/acceptance/support/sandbox.rs
Fixes #207.
Reduces the OS-specific logic by building everything on top of a `notion_home()` function. Most of the directory layout is OS-independent.
Also eliminates the Rust compiler warning for the deprecated `std::env::home_dir()` function, replacing it with the recommended `dirs` crate.
This PR is the first step towards making a more abstracted and manageable approach to the Notion directory layout. My goal is to create a `Layout` data structure with methods for extracting all the paths. This will then be something that can be shared by not only Notion, but also the test harness's sandbox setup code, as well as a migration tool for upgrading between different layouts.
> Use `NOTION_HOME` for all sandboxing

- dev/unix/boot-install.sh
As part of fixing #229, use the `notionjs.com/latest-version` URL instead of the Github API. This avoids the rate-limiting, and also simplifies the install script.
This should be merged after https://github.com/notion-cli/www/pull/3, so that `/latest-version` actually exists.
> Use latest-version URL instead of Github API

- crates/notion-core/src/distro/node.rs
- crates/notion-core/src/manifest/mod.rs
- crates/notion-core/src/manifest/serial.rs
- crates/notion-core/src/path/mod.rs
- crates/notion-core/src/platform/mod.rs
- crates/notion-core/src/project.rs
- crates/notion-core/src/session.rs
- crates/notion-core/src/tool.rs
- crates/notion-core/src/toolchain/mod.rs
- crates/notion-core/src/toolchain/serial.rs
- src/command/current.rs
- tests/acceptance/notion_pin.rs
Closes #208 
* Updated `PlatformSpec` to hold `node_runtime` and `npm` separately.
* Switched `PlatformSpec::npm` to be an `Option`.
* Included logic in `PlatformSpec::checkout()` that determines the default version of npm when creating an `Image`.
* Prevent writing of `npm` to `package.json` if it is the default for the selected `node` version when pinning the `node` version (currently that is always the case, so `npm` will never be written).
* Also did some minor refactors, removing a `Result` wrapper around `Session::current_platform` and related functions, since all code paths would return `Ok`
> Make "npm" key optional in package.json

- crates/notion-core/src/event.rs
- crates/notion-core/src/project.rs
- crates/notion-core/src/session.rs
- crates/notion-core/src/tool.rs
- crates/notion-core/src/tool/mod.rs
- crates/notion-core/src/toolchain/mod.rs
- src/command/current.rs
- src/command/pin.rs
- src/notion.rs
Closes #236 
Description
-----
Some commands that didn't need to know anything about the platform or configuration (e.g. `notion activate` and `notion deactivate`) were failing when being run from a folder where there was a malformed `toolchain` entry. Additionally, these commands would fail if there was something wrong with the user toolchain, despite the fact that they didn't use that toolchain in any way.
The root cause of this was that `Session::new()` was `Fallible`, and all commands required a `Session` to start processing. If creating the `Session` failed, then the entire command would fail.
Changed
-----
* Removed unnecessary `Fallible` return type for `EventLog`, as it could never fail and wasn't calling anything that could fail.
* Added Lazy Loading pattern to `Project` and …
> Allow Commands to run even if configuration is invalid

- crates/notion-core/src/env.rs
- crates/notion-core/src/tool/binary.rs
- crates/notion-core/src/tool/mod.rs
- crates/notion-core/src/tool/node.rs
- crates/notion-core/src/tool/npm.rs
- crates/notion-core/src/tool/npx.rs
- crates/notion-core/src/tool/script.rs
- crates/notion-core/src/tool/yarn.rs
- tests/acceptance/intercept_global_installs.rs
- tests/acceptance/main.rs
- tests/acceptance/support/sandbox.rs
Closes #154 
Changes
-----
* Added checks to `npm` and `yarn` to intercept global installs and show an error message guiding the user to `notion install` for global packages.
* Allowed this behavior to be overridden by the `NOTION_ALLOW_GLOBAL` environment variable.
* Refactored the `Tool` implementations into their own files within the `tool` subdirectory, but re-exported them from the `tool` module so they can be accessed in the same manner as they were previously.
Notes
-----
* Yarn global installs will always start with `yarn global add`, since `global` is a separate command that must be the first argument, then `add` is the command to install a package.
* npm global installs have a few variations. The command, which is the first argument, can be either `install` or `i`, while the …
> Intercept Global Installs from npm and Yarn

- dev/unix/install.sh.in
- Hide any failures during the `notion version` check and treat those as 0.1*.
- Also improved the reinstallation message style and copy: <img width="531" alt="image" src="https://user-images.githubusercontent.com/307871/52512855-fb822580-2bbb-11e9-9703-2e51f3f3ae02.png">
- Remove pointless cleanup logic from install script
> Bug fix in installer

- crates/notion-core/src/tool.rs
Using `VersionReq::matches` will (intentionally) not match prerelease versions. Instead you must compare via `>=`.
Fixes https://github.com/notion-cli/notion/issues/238
> Ensure prerelease npm still allow npx usage

- Cargo.lock
- Cargo.toml
- crates/archive/Cargo.toml
- crates/archive/src/tarball.rs
- crates/headers-011/Cargo.toml
- crates/headers-011/src/lib.rs
- crates/notion-core/Cargo.toml
- crates/notion-core/src/distro/error.rs
- crates/notion-core/src/inventory/mod.rs
- tests/acceptance/support/sandbox.rs
Upgraded all crates to reqwest 0.9.9 and made all the necessary changes based on incompatible changes in reqwest.
Unfortunately, reqwest temporarily removed the main APIs for typed header extraction and parsing, but it added some temporary compatibility layers you can opt into, using the now-outdated `hyper` 0.11. This PR uses those, and adds a trait to shim behavior similar to the old `Headers::get::<H: Header>()` method to the new `HeaderMap` type.
> Upgrade to reqwest 0.9.9

- dev/unix/boot-install.sh
Update the bootstrap installer (ie the https://get.notionjs.com script) to choose between multiple Linux builds for Notion >= 0.2, for different versions of OpenSSL.
> Multiple Linux builds

- dev/unix/boot-install.sh
- dev/unix/install.sh.in
The installer can't be interactive since it's piped from curl. And it's not a good idea to be trying to get too clever about uninstalling (`rm` is scary).
So this PR changes the installer to make it a hard error if an old Notion installation is found. The check is moved into the bootstrap script to avoid users having to download the (quite big) installer twice.
> Non-interactive installer

- crates/notion-fail/src/lib.rs
I started seeing deprecations for use of `.cause()` and just implemented the included recommendation to convert to `.as_fail()`.
> Fix Failure deprecation in notion-fail.

- Cargo.toml
- crates/notion-core/Cargo.toml
- crates/notion-core/src/tool/mod.rs
- tests/acceptance/main.rs
As noted in #272, we shouldn't intercept globals and direct the user to `notion install <package>` before the general package installs are working. Update to lock that behavior behind a feature flag (`intercept-globals`) until we get the package installs working.
> Move preventing globals behind a feature flag

- dev/unix/boot-install.sh
Closes #278 
Update the bootstrap installer (served by `get.notionjs.com`) to download the actual Notion installer using the `-#` option (Progress bar) instead of the `-s` option (Silent). This gives some feedback on the process of downloading the Installer, which can take a while as it is currently quite large.
> Show progress bar when downloading Notion installer

- Cargo.lock
- Cargo.toml
- src/command/install.rs
- Bumps required Rust version to 1.33 – corresponding docs change is at notion-cli/docs#2
- Fixes #287
> Migrate from result crate's `invert` to std's `transpose`.

- dev/unix/install.sh.in
The previous invocation was unqualifiedly adding `~/.notion` to the user's `PATH`. This would result in the path growing every time they started a new instance of their shell.
A corresponding implementation in bash would be a nice complement to this, but my bash-fu is much weaker than my fish-fu at this point. I'm happy to open an issue to track that, however.
> Core: don't repeatedly add `~/.notion` in fish.

- Cargo.lock
- Cargo.toml
- crates/notion-core/src/error.rs
- crates/notion-core/src/session.rs
- src/cli.rs
- src/command/activate.rs
- src/command/completions.rs
- src/command/config.rs
- src/command/current.rs
- src/command/deactivate.rs
- src/command/fetch.rs
- src/command/install.rs
- src/command/mod.rs
- src/command/pin.rs
- src/command/use.rs
- src/command/which.rs
- src/main.rs
Closes #167 
Info
-----
Adds a command `notion which <BINARY>` that shows the user which binary will actually be run, effectively seeing through the shims. It will also resolve any other binary that happens to be on the path, so it works as a drop-in replacement for `which`:
```bash
$ which node
/Users/me/.notion/bin/node
$ notion which node
/Users/me/.notion/tools/image/node/10.15.3/6.4.1/bin/node
$ which ls
/bin/ls
$ notion which ls
/bin/ls
```
Notes
-----
* Currently this command will use the system path (with Notion shim directory removed) as the `PATH` if there is no platform _or_ if there are any errors when attempting to retrieve the platform image. Errors with determining the system path or the current working directory will still be exposed as errors, however.
* This will likely …
> Add `notion which` command

- src/command/pin.rs
Fixes #312 
`notion pin` was requiring the `version` argument to be specified, instead of defaulting to "latest" like `notion install`. Update the `pin` command to match the `install` command with an Optional `version` argument and resolving the latest if the version is not specified.
> Allow version to be optional in 'notion pin'

- crates/notion-core/src/error.rs
- src/cli.rs
- src/command/use.rs
- src/main.rs
A number of fairly minor changes to the command-line logic and formatting:
- `notion --version` prints just the version number
- consistent prose style in usage
- `notion use` fails as an error
- hide `activate`/`deactivate` from main help information
<details>
<summary>Main help messages</summary>
</details>
<details>
<summary>Subcommand help pages don't include a version number</summary>
</details>
<details>
<summary>Error message for "notion use"</summary>
</details>
<details>
<summary>Error message if "notion use" gets passed any flags</summary>
(I couldn't figure out how to get StructOpt/Clap to just stop parsing anything after `use`, so it barfs if you have any flags.)
</details>
<details>
<summary>Help page for "notion deactivate"</summary>
</details>
> Command-line parsing and output improvements

- tests/acceptance/notion_pin.rs
As a follow-up to #313, add acceptance tests that cover invoking `notion pin` without a version specified.
> Add tests for notion pin without version

- crates/notion-core/src/project.rs
- crates/notion-core/src/session.rs
- crates/notion-core/src/tool/mod.rs
- crates/notion-core/src/tool/npm.rs
- crates/notion-core/src/tool/yarn.rs
- src/command/pin.rs
Closes #235 
Info
-----
Now that #247 has landed, we can remove the autoshimming to prevent cluttering the user's path with shims to JS binaries.
Changes
-----
* Removed the calls to `autoshim`.
* Removed the `finalize` method on the `Tool` trait, as it was only being used to support autoshimming.
* Removed the `autoshim` and `dependent_binary_names_fault_tolerant` methods from `Project`.
Tested
-----
* Verified locally that running `yarn` in a project with many dependencies doesn't result in any shims being created.
> Remove autoshimming

- Cargo.toml
- crates/notion-core/Cargo.toml
- crates/notion-core/src/tool/mod.rs
- tests/acceptance/intercept_global_installs.rs
- tests/acceptance/main.rs
Now that #247 has landed, we want to re-enable the interception of global installs by default. This will push the users to the new feature and the recommended workflow for Notion.
> Remove feature flag around intercepting global installs

- tests/acceptance/notion_pin.rs
Seems like in the shuffle of various PR merges some changes happened that altered the error output and broke one of the `notion pin` tests.
Update the expected output to what is actually shown.
> Fix broken test from merge changes

- crates/notion-core/src/tool/npm.rs
Somewhere in the mix of several of the sweeping changes that have been made recently, we inadvertently set `npm` to only look at the `project_platform`, not the `current_platform` (which also checks for a user platform).
This caused calls to `npm` to fail if you weren't inside of a project, because it was only looking for a `package.json` and failing if it didn't find one.
Updated to use `session.current_platform()`, instead of `session.project_platform()`.
> Check user platform as well as project for npm

- crates/notion-core/src/error/reporter.rs
Info
-----
* The verbose error output (and error logs) currently only shows the first level underlying cause of a given error. If the error is more deeply nested, with multiple wrapper `Error`s, then only the first will be listed.
Changes
-----
* Updated the `compose_error_details` method to traverse the entire tree of `.cause()` calls, outputting all of the causes.
* Also refactored the code a bit so `compose_error_details` returns an `Option`, instead of unwrapping the cause outside.
> List all causes in verbose errors

- crates/notion-core/src/distro/package.rs
- crates/notion-core/src/error/details.rs
- crates/notion-core/src/fs.rs
- crates/notion-core/src/inventory/serial.rs
- crates/notion-core/src/path/mod.rs
- crates/notion-core/src/path/windows.rs
- crates/notion-core/src/session.rs
- crates/notion-core/src/tool/mod.rs
- src/cli.rs
- src/command/mod.rs
- src/command/uninstall.rs
- tests/acceptance/main.rs
- tests/acceptance/notion_uninstall.rs
- tests/acceptance/support/sandbox.rs
This implements package uninstall: #319.
```
$ ./target/debug/notion uninstall cowsay
Removed executable 'cowthink' installed by 'cowsay'
Removed executable 'cowsay' installed by 'cowsay'
Package 'cowsay' uninstalled
```
```
$ ./target/debug/notion uninstall cowsay --full
Removed cached files for 'cowsay'
Package 'cowsay' uninstalled
```
Removes:
Optionally remove (with the `--full` flag):
Closes #319
> Package uninstall

- crates/notion-core/src/distro/mod.rs
- crates/notion-core/src/distro/package.rs
- crates/notion-core/src/error/details.rs
- crates/notion-core/src/fs.rs
- crates/notion-core/src/inventory/mod.rs
- crates/notion-core/src/manifest/mod.rs
- crates/notion-core/src/project.rs
- crates/notion-core/src/shim.rs
- crates/notion-core/src/tool/binary.rs
- crates/notion-core/src/tool/mod.rs
- crates/notion-core/src/tool/node.rs
- crates/notion-core/src/tool/npm.rs
- crates/notion-core/src/tool/npx.rs
- crates/notion-core/src/tool/yarn.rs
- crates/notion-core/src/version/mod.rs
- src/command/install.rs
- tests/acceptance/intercept_global_installs.rs
- tests/acceptance/notion_pin.rs
See #295 
Info
-----
* With the ability to provide verbose error messages in place, we can start to actually tackle improving the error messages.
* To start, we want to audit the existing error messages and update them to be more helpful.
* There are many error messages in the program currently, so to start I focused on two areas:
1. Informational error messages thrown by the Tool shims, indicating a problem with the users' configuration (platform or project).
2. Errors that included the text of an underlying error inside of them (via an `error` property on the `ErrorDetails` variant).
Changes
-----
* Updated error messages in `error/details.rs` to match the new style, including CTAs to help guide the user to the correct action.
* Updated all call sites to correctly reference the new …
> First pass at auditing existing error messages

- crates/notion-core/src/event.rs
Closes #297 
Update the tests in the `event` module to not use the `.unknown()` method and instead instantiate an `ErrorDetails` object.
> Rework unknown errors in event module

- crates/notion-core/src/distro/package.rs
Closes #325 
Info
-----
* Some user tools (e.g. `ember-cli`) can invoke `yarn` as part of their execution.
* We currently aren't saving a `yarn` version in the user tool config file.
* This means that the user tool is executed with a `PATH` that doesn't include `yarn`, meaning any invocations of `yarn` will fail.
* In these cases, we should include the user default yarn (if any) in the platform.
Changes
-----
* Added logic to check if the bin config has `yarn` set (which won't currently happen, but could in the future with `notion install` options).
* If `yarn` is not set, pull the user platform and copy the `yarn` version from there.
Tested
-----
* Executed `ember new my-project --yarn` and confirmed that it successfully installed using `yarn`, instead of failing to find yarn as it did …
> Merge user platform with bin platform when invoking packages

- crates/notion-core/src/error/details.rs
- crates/notion-core/src/project.rs
- src/command/which.rs
Closes #303 
Add a `CurrentDirError` to `ErrorDetails` for when determining the current directory fails.
> Rework unknown errors in project module

- crates/notion-core/src/error/details.rs
- crates/notion-core/src/platform/mod.rs
Closes #302 
Add `BuildPathError` to `ErrorDetails`, representing being unable to join the paths when creating a virtual environment in the `platform` module.
> Rework unknown errors in platform module

- crates/notion-core/src/error/details.rs
- crates/notion-core/src/shell/mod.rs
Closes #304 
Add a `CreatePostscriptError` to represent a failure to create the postscript file when executing `notion activate` or `notion deactivate`
> Rework unknown errors in shell module

- crates/notion-core/src/error/details.rs
- crates/notion-core/src/manifest/mod.rs
Closes #301 
Update all of the calls to `.unknown()` in `update_toolchain` to use `.with_context()` instead, returning `ErrorDetails` variants. Also Added `PackageWriteError` and `StringifyToolchainError` to cover the error cases that had not already been covered.
> Rework unknown errors in manifest module

- crates/notion-core/src/distro/mod.rs
- crates/notion-core/src/distro/node.rs
- crates/notion-core/src/distro/package.rs
- crates/notion-core/src/distro/yarn.rs
- crates/notion-core/src/fs.rs
- crates/notion-core/src/inventory/mod.rs
- crates/notion-core/src/session.rs
- src/command/fetch.rs
Closes #352 
Now this doesn't error if the same version has already been installed:
```
$ notion install cowsay
Unpacking cowsay-v1.4.0  [========================================] 100%
npm notice created a lockfile as package-lock.json. You should commit this file.
added 9 packages from 2 contributors and audited 1535 packages in 3.261s
found 0 vulnerabilities
$ notion install cowsay
Package `cowsay` is up-to-date, version 1.4.0 already installed
```
Closes #353 
Don't fail for a different version of an existing package:
```
$ notion install ember-cli 3.8.1
Fetching ember-cli-v3.8.1  [========================================] 100%
[lots out output not included]
$ ember --version
WARNING: Node v11.14.0 is not tested against Ember CLI on your platform. We recommend that you use the …
```
> Fix annoying package install errors

- .vscode/launch.json
- crates/notion-core/src/manifest/serial.rs
- Fixes #388
- Adds a debugger launch config for VS Code, which I found useful (can drop it if people don't want it here)
> Handle illegal `engines` fields.

- crates/notion-core/src/distro/package.rs
Closes #369 
Closes #374 
Add the following flags when executing `npm install` to install dependencies on a `notion install <package>`:
* `-q`: Sets output to quiet mode, meaning only warnings and errors are shown, but not notices.
* `--no-update-notifier`: Remove the message about a new version of `npm` being available.
* `--no-audit`: Remove the package auditing, which can result in a CTA saying `run npm audit fix`, which won't work and is misleading.
> Suppress misleading messages from npm on package install

- crates/notion-core/src/error/reporter.rs
Closes #358 
Closes #387 
Include the full path to the log file in the error output, not just the file name.
> Include full path to log file in error output

- crates/notion-core/src/distro/package.rs
- Drop an allocation by using `self.image_dir.as_os_str()` instead of `&self.image_dir.clone().into_os_string()`
- Simplify the logic by distinguishing *only* the installer, since the rest of the `install_command_for` invocation is identical.
> Make two small cleanups in package install logic.

- crates/notion-core/src/distro/package.rs
- crates/notion-core/src/error/details.rs
Closes #351 
Closes #385 
On unix, ensure that all 3rd-party binary files installed through `notion install <package>` are marked as executable in the file-system. This is necessary because we call the file directly when executing the shim, and if it is not executable, then we get a `permission denied` error.
On windows, this isn't a problem as there isn't a separate concept of "executable" permissions.
> Ensure package binary files are executable on Unix

- crates/notion-core/src/project.rs
- crates/notion-core/src/session.rs
- crates/notion-core/src/style.rs
- tests/acceptance/notion_pin.rs
Closes #357 
Adds a success message to `notion install node`, `notion install yarn`, `notion pin node`, and `notion pin yarn`, so that the user is informed of success, instead of leaving the terminal completely blank.
> Add success messages to 'notion pin' and 'notion install'

- crates/notion-core/src/error/details.rs
- crates/notion-core/src/event.rs
- crates/notion-core/src/tool/mod.rs
- src/command/activate.rs
- src/command/deactivate.rs
- src/command/fetch.rs
- src/command/pin.rs
Closes #359 
Replace uses of the `unimplemented!` macro with returning an `ErrorDetails::Unimplemented` error. The macro causes a panic, which is a jarring experience for the user, compared with our usual well-formatted errors. Instead of panicking in most cases, we can instead return an error that displays the same message using our existing error reporting mechanisms.
There are two cases where `unimplemented!` is still being used: Inside of `event.rs`, where it is part of an operation that isn't `Fallible` (and also isn't currently used), and inside of `windows.rs`, where it is simply a placeholder for when we compile with `universal-docs` and won't ever actually be run.
> Replace unimplemented macro with ErrorDetails variant

- azure-pipelines.yml
- ci/install-bats.yml
- ci/run-tests.yml
- dev/unix/release.sh
- dev/unix/tests/release-script.bats
Start to implement #151 by packaging the compiled binaries and shell scripts for release.
```
$ ./dev/unix/release.sh
Building Notion for notion-0.3.0-macos
Finished release [optimized] target(s) in 0.69s
Packaging the compiled binaries and shell scripts
a notion
a shim
a load.fish
a load.sh
Completed release in file target/release/notion-0.3.0-macos.tar.gz
```
```
$ ./dev/unix/release.sh --dev
Building Notion for notion-0.3.0-macos
Finished dev [unoptimized + debuginfo] target(s) in 0.43s
Packaging the compiled binaries and shell scripts
a notion
a shim
a load.fish
a load.sh
Completed release in file target/debug/notion-0.3.0-macos.tar.gz
```
```
$ ./dev/unix/release.sh -h
release.sh
Compile and package a release for Notion
USAGE:
./dev/unix/release.sh [FLAGS] [OPTIONS]
FLAGS:
-h, --help …
```
> Release script, and script tests in CI

- crates/notion-core/src/error/details.rs
- crates/notion-core/src/inventory/mod.rs
Closes #361 
Add a specific error message for the case when a user runs `notion install <package>` with a package name that doesn't exist in the npm registry. Before this change, we were showing a less-accurate `Could not parse package metadata` error, instead of telling the user that the package could not be found.
> Show specific error for nonexistent package

- .vscode/launch.json
- crates/notion-core/src/error/details.rs
- crates/notion-core/src/style.rs
- crates/notion-core/src/tool/mod.rs
- src/command/fetch.rs
- src/command/install.rs
- src/command/pin.rs
Users coming from tools like `nvm` or `nodenv` or other ecosystems may expect `notion install node 10` to install Node v10. Since it will instead install `node@lts` and `10@latest` -- and the package `10` [does indeed exist!][10] -- provide an error message when Notion detects that this scenario has occurred.
[10]: https://www.npmjs.com/package/10
> Provide informative error for `notion <action> <tool> <version-like>`.

- crates/volta-core/src/error/details.rs
- src/command/completions.rs
Fixes #382.
- Require the user to pass a shell to generate completions for.
- Change the `-o, --output` flag to be a *file* path, not a directory path, so users can do that instead of redirecting stdio.
- Include the path in the error for better information for the user.
- Add a `-f, --force` flag to let the user stomp the existing file if they just want to recreate it.
> Completions: be less clever but more usable.

- crates/volta-core/src/error/details.rs
Closes #363 
Updated error message for the `NoPlatform` case (when `node` is not set in either the project nor the user platform) to be less confusing and give a stronger CTA.
> Improve 'NoPlatform' error message

- crates/volta-core/fixtures/basic/package.json
- crates/volta-core/src/manifest/mod.rs
- crates/volta-core/src/manifest/serial.rs
- crates/volta-core/src/project.rs
- crates/volta-core/src/session.rs
- dev/package.json
- tests/acceptance/intercept_global_installs.rs
- tests/acceptance/volta_current.rs
- tests/acceptance/volta_pin.rs
- tests/smoke/autodownload.rs
- wix/main.wxs
Closes #412 
Info
-----
* As discussed in the issue, we want to use a more discoverable and tool-specific key `volta` in `package.json` instead of the generic `toolchain`.
* The concept is still the `toolchain` internally, so we only want to change how it is serialized and deserialized, not how the internal code references that value.
Changes
-----
* Added a serde rename attribute to the `toolchain` element in `manifest::serial::Manifest`
* Updated `volta pin` logic to use `volta` instead of `toolchain` as the key.
* Changed comments around `volta pin` methods to refer to the `volta` key.
* Updated all test fixtures to use `volta` in their `package.json` values.
Notes
-----
* I also updated the description in `main.wxs` to match the new slogan "The JavaScript Launcher", discovered when …
> Use 'volta' instead of 'toolchain' for package.json config

- src/command/which.rs
- Fixes #391.
- Includes some cleanup of the existing `which` code.
> which: look up user tools, including in projects.

- crates/volta-core/src/project.rs
Closes #393 
Info
-----
As noted in the issue, we are currently parsing all of the dependency `package.json` files to find which `bins` are local, direct dependencies. However, since we have implemented `volta install <package>`, we have a bin config file that can tell us which package a binary came from.
Changes
-----
* Updated `Project::has_direct_bin` to read the `BinConfig` file and then check that the `package` for that bin is declared in the current project's `dependencies` or `devDependencies`, bypassing the need to parse all of the dependencies directly.
* Removed the `LazyDependentBins` struct and all of the code around generating that HashMap, since we don't use it anymore.
> Don't parse dependencies when locating a local binary

- crates/volta-core/src/error/details.rs
- crates/volta-core/src/event.rs
- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/npm.rs
- crates/volta-core/src/tool/yarn.rs
- tests/acceptance/intercept_global_installs.rs
Fixes #360
<details>
<summary>
output for <code>yarn global add</code> and <code>npm -g, --global install</code> (all variations)
</summary>
```
$ yarn global add waffles
Volta error: Global package installs are not supported.
Use `volta install waffles` to add a package to your toolchain (see `volta help install` for more info).
$ yarn global add
Volta error: Global package installs are not supported.
Use `volta install` to add a package to your toolchain (see `volta help install` for more info).
$ npm i -g waffles
Volta error: Global package installs are not supported.
Use `volta install waffles` to add a package to your toolchain (see `volta help install` for more info).
$ npm add -g waffles
Volta error: Global package installs are not supported.
Use `volta install waffles` to add a …
```
> Tools: better message for intercepted global installs.

- crates/volta-core/src/inventory/serial.rs
Fixes an issue internal testing at LI identified. (I don't see a good test to write here because it's a *negative* test.)
> Cleanup: remove extraneous `println!()`.

- dev/unix/boot-install.sh
Remove `www.` from latest-version URL in installer.
> Fix boot-install latest-version URL

- crates/volta-core/src/manifest/mod.rs
- crates/volta-core/src/manifest/serial.rs
- crates/volta-core/src/style.rs
- Fixes #432.
- Fixes #433.
<details><summary>deprecation output</summary>
```sh
$ yarn
Volta warning: the `toolchain` key is deprecated and will be removed in a future
version. Please switch to `volta` instead.
yarn install v1.13.0
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.33s.
$ volta pin yarn@1.15.2
warning: the `toolchain` key is deprecated and will be removed in a future
version. Please switch to `volta` instead.
success: pinned yarn@1.15.2 in package.json
$ volta pin yarn
warning: this project is configured with both the deprecated `toolchain` key and
the `volta` key; using the versions specified in `volta`.
success: pinned yarn@1.16.0 in package.json
$ yarn
Volta warning: this project is configured with both the deprecated `toolchain`
key and the …
```
> Support `volta` and `toolchain` keys side by side.

- crates/volta-core/src/error/details.rs
- crates/volta-core/src/tool/binary.rs
- crates/volta-core/src/tool/mod.rs
When attempting to execute a project-local tool (e.g. `ember`), if the binary doesn't exist (because, for example, the `node_modules` have not been installed), then the error message is misleading:
```
Could not execute command.
See `volta help install` and `volta help pin` for info about making tools available.
```
The problem, in this case, isn't that the tool hasn't been made available, but rather that executing it failed for some reason (most likely because the file doesn't exist). Update that to instead say:
```
Could not execute command `/path/to/project/node_modules/.bin/ember`
Please ensure that all project dependencies are installed.
```
Which gives information about what command was being run _and_ what the user can do to fix it.
Also removed the `DepPackageReadError`, as we no …
> Improve error message when executing a project-local bin

- Cargo.lock
- crates/volta-core/Cargo.toml
- crates/volta-core/src/style.rs
Closes #450 
Use the `atty` crate to detect if `stdout` is a TTY or not. If it isn't, then we short-circuit the `write_warning` method to prevent writing warnings when we're being called in a script.
> Prevent printing warnings if stdout is not a tty

- dev/unix/volta-install.sh
The install script is not broken, but the code should be fixed to be more explicit.
Currently, in the `download_release_from_repo()` function, the `$download_dir` variable is passed in, and captured locally in the `$tmpdir` variable. But then `$tmpdir` is never used, and instead `$download_dir` is used (probably a refactoring miss on my part).
It seems like this shouldn't work, because `$download_dir` is a local var in the parent function, BUT the scope of local variables in bash is limited to the function _and any of its children_ (see [here](https://www.tldp.org/LDP/abs/html/localvar.html#FTN.AEN18568)). So this still works, but it works explicitly, which is not great.
All that to say that I changed this to actually use `$tmpdir` inside the function.
> Clean up a bug in the install script

- shell/unix/load.fish
Calling `env ... command ...` in `fish` fails with `env: ‘command’: No such file or directory`, this fixes that per @dfreeman's comment in #454.
Closes #454
> Fix fish script for non-macOS platforms

- ci/build-api-docs.yml
- ci/install-rust.yml
It appears that running `curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly` doesn't change the default toolchain if Rust is already installed. This is causing the docs build to fail because it needs Nightly to use the `#![feature]` attribute.
Added a new step that runs `rustup default nightly` to ensure that the nightly toolchain is always selected as the default.
> Enforce nightly build even if rust is already installed

- crates/volta-core/src/error/details.rs
- crates/volta-core/src/hook/mod.rs
- crates/volta-core/src/hook/serial.rs
- crates/volta-core/src/hook/tool.rs
Closes #459 
Info
-----
* The Hooks configuration has an option `bin` that allows you to specify a command to run to resolve the hook.
* Currently, that command is run relative to the current directory, so if you specify a relative path in `hooks.json`, it will only work if you are in the correct directory.
* The easiest way to specify hooks will be with a relative path to the script, so we should support this use-case.
Changes
-----
* Updated the hooks deserialization to propagate the base directory that the `hooks.json` file is found in to any `Bin` hooks.
* If the command is detected as being a relative path (if it begins with `.`), then we execute it relative to the base directory found above.
* Added detection for non-zero exit codes, so that if the hook command returns a failure …
> Support relative paths for Bin hooks

- crates/volta-core/src/log.rs
Update the logger to show messages from any crate that starts with `volta` (which includes the base `volta` as well as `volta_core` and `volta_fail`).
> Allow logs to show from main crate as well as volta-core

- crates/volta-core/src/tool/mod.rs
Closes #478 
Use `sort_by` and specify an ordering function to do the sorting of tools. That sorting function explicitly treats Node as the lowest, followed by Npm, Yarn, and Packages, but within each category it ignores the specifics and treats all tools as the same.
Per [the rust docs](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.sort_by), `Vec::sort_by` is stable, so by treating all of the Packages as equal, the original order (provided by the user) will be preserved.
Note: We use `sort_by` as opposed to a custom implementation of the `Ord` trait because the docs specify that the implementations of `Ord` and `PartialEq` must match exactly, and we use the derived `PartialEq` implementation elsewhere so it can't be changed.
> Use sort_by to preserve user-defined order of package installs

- crates/volta-core/src/error/details.rs
- crates/volta-core/src/platform/sourced.rs
- crates/volta-core/src/session.rs
- crates/volta-core/src/tool/binary.rs
- crates/volta-core/src/tool/node.rs
- crates/volta-core/src/tool/npm.rs
- crates/volta-core/src/tool/npx.rs
- crates/volta-core/src/tool/yarn.rs
- tests/acceptance/main.rs
- tests/acceptance/merged_platform.rs
Closes #436 
Info
-----
* Currently, if we have a default yarn set, but the user runs `yarn` within a project that _doesn't_ have yarn specified, then we throw an error and require the user to run `volta pin yarn` to continue.
* This is a poor UX, as the user has already run `volta install yarn`, so we do have a Yarn version available, we are just not using it.
* Additionally, with the command passthrough and other UX improvements, we have taken the approach of setting Volta up to _support_ doing things the "safe" way (e.g. if you use `yarn` in your project, you should specify it there), but not _require_ that they are done that way.
* To align with that goal, we should fall back to the default yarn, even in a project that doesn't have `yarn` specified.
Changes
-----
* Added an additional …
> Fall back to default Yarn if project Yarn is not set

- crates/volta-core/src/distro/package.rs
- crates/volta-core/src/manifest/mod.rs
- crates/volta-core/src/manifest/serial.rs
Closes #476 
Info
-----
* Currently the package install logic uses the full project Manifest parser to read the `package.json` and get the `bin` and `engines` information.
* This causes the package install to show a warning when the package being installed has a `toolchain` property.
* Additionally, we are parsing extra fields (`dependencies`, `volta`, etc.) that aren't needed in the package install context.
Changes
-----
* Split `Manifest` into two structs (`Manifest` for the project information and `BinManifest` for the specific information needed when doing a package install).
* Update the deserialization logic to reflect the split in behavior.
* Switch package install process to use the `BinManifest` instead of the `Manifest` object, which removes the code path that shows a warning …
> Separate bin manifest parse from regular manifest

- crates/volta-core/src/distro/node.rs
- crates/volta-core/src/distro/yarn.rs
- crates/volta-core/src/error/details.rs
- tests/acceptance/corrupted_download.rs
- tests/acceptance/main.rs
- tests/acceptance/support/sandbox.rs
- tests/fixtures/node-v0.0.1-darwin-x64.tar.gz
- tests/fixtures/node-v0.0.1-linux-x64.tar.gz
- tests/fixtures/node-v0.0.1-win-x64.zip
- tests/fixtures/node-v0.0.1-win-x86.zip
- tests/fixtures/yarn-v0.0.1.tar.gz
- tests/smoke/main.rs
Closes #200 
Closes #275 
Info
-----
When downloading Node or Yarn, if the download is interrupted (by the user pressing Ctrl+C, for example) or if the download is corrupted in some way, the Volta internal state gets corrupted. We currently write the archive directly to the cache, so if it is invalid in some way, on subsequent attempts, we continue to try to use that invalid cache.
Changes
-----
* Updated `distro::node` and `distro::yarn` to download the archives into a temp file, and only move that temp file over to the cache location once the fetching and unpacking has completed successfully.
Tested
-----
* Manual testing to verify that interrupting the download of Node or Yarn no longer leaves an incomplete cache file in the inventory directory.
* Manually confirmed that after …
> Download archives to temp file to prevent corrupted state

- Cargo.lock
- crates/volta-core/Cargo.toml
- crates/volta-core/src/lib.rs
- crates/volta-core/src/signal.rs
- crates/volta-core/src/tool/mod.rs
- src/shim.rs
Closes #500 
Info
-----
Currently the `Ctrl+C` SIGINT signal is being sent to both the Volta process and the shimmed child process simultaneously. This means that if a shim waits after receiving the SIGINT signal (as in the repro example in #500), Volta will still exit immediately and not wait for the shim.
Changes
-----
* Used the `ctrlc` crate to set a handler for Ctrl+C in the shim executable.
* Handler uses a flag to determine if control has been passed to the shim or not.
* If it has, the handler does nothing and lets the child process control the flow of the application.
* If it hasn't, then we are still doing Volta work (perhaps downloading a version of Node), so it exits immediately (the default behavior).
* Added a call to set the flag immediately before running the shim process. …
> Delegate Ctrl+C handling for shims

- dev/unix/tests/install-script.bats
- dev/unix/volta-install.sh
Partially addresses #519 
Info
-----
* We don't currently provide pre-built binaries for Architectures that aren't x86_64.
* The installer, however, only looks at the OS and doesn't consider the architecture, so it is happy to try to install a 64-bit binary on a 32-bit system.
* This binary fails, but it's only once the user attempts to run `volta` that they see the issue.
* We can detect early on that an install won't work, and fail fast with a message to the user.
Changes
-----
* Added a `check_architecture` function to the install script which verifies that the architecture the user is on is supported.
* The function will always succeed if the install is from a local build, since those binaries were built on the current architecture and should work.
* If it's not a local build, then …
> Installer - fail fast on unsupported architectures

- src/command/list/toolchain.rs
When checking whether the list of all packages and tools includes tools, check the tools against `Kind::Tool` instead of `Kind::Package`. (Fixes a mistake introduced during the refactor made in 3eb57526.)
> volta list: fix tool printing logic

- crates/volta-core/src/error/details.rs
- crates/volta-core/src/path/mod.rs
- crates/volta-core/src/path/unix.rs
- dev/rpm/build-rpm.sh
- dev/rpm/volta-postinstall.sh
- dev/rpm/volta.spec
- tests/acceptance/autocreate_home_dir.rs
- tests/acceptance/main.rs
- tests/acceptance/support/sandbox.rs
The `volta` binary is now installed to `/usr/bin`, so it will be available on the PATH after install. For the user who ran the install, everything is still setup in their home dir.
If this was installed by `root` (which seems to be typical in managed environments), then other users will not have `~/.volta/` setup for them. We already had code to create the directory layout if it does not exist, and this adds one more step to also create the base shims (`node`, `npm`, `yarn`). This allows a non-root user to bootstrap `~/.volta` after this has been installed by root.
There are also some changes to where Volta looks for the `shim` executable. I added an option to look in the install location `/usr/bin/volta-lib/shim` for the RPM special case, so non-root users can still create shims that …
> Update how RPM install works, and auto-create shims along with the home dir layout

- crates/volta-core/src/error/details.rs
- crates/volta-fail-derive/src/lib.rs
- crates/volta-fail/src/lib.rs
Closes #306 
Since the error rework, there is no longer a need to support the `VoltaError::unknown()` and `VoltaError::is_user_friendly()` errors. All errors are now user-friendly, and no unknown errors are used anywhere in the code base.
Additionally, we do still want to have separate crates, which will necessitate having separate error types, so we don't want to remove `volta-fail` entirely (as was originally suggested in #334)
> Remove unknown() and is_user_friendly() from VoltaError

- Cargo.lock
- crates/archive/Cargo.toml
- crates/archive/src/tarball.rs
- crates/fs-utils/Cargo.toml
- crates/fs-utils/src/lib.rs
- crates/volta-core/Cargo.toml
- crates/volta-core/src/error/details.rs
- crates/volta-core/src/error/reporter.rs
- crates/volta-core/src/fs.rs
- crates/volta-core/src/shell/mod.rs
- crates/volta-core/src/tool/node/fetch.rs
- crates/volta-core/src/tool/node/resolve.rs
- crates/volta-core/src/tool/package/fetch.rs
- crates/volta-core/src/tool/package/serial.rs
- crates/volta-core/src/tool/yarn/fetch.rs
- tests/smoke/volta_install.rs
Fixes #538.
This ensures that the directory exists before trying to unpack the tarball there.
Additional cleanup: I moved the `ensure_containing_dir_exists` function into a new `fs-utils` crate. There are some other functions that could be moved there, but I didn't want to go down that hole for this PR.
When there is an error (I made the parent dir read-only for this), we get the error message from the OS:
```
$ ./target/debug/volta install @wdio/cli --verbose
[verbose] No custom hooks found
[verbose] Running command: `"npm" "view" "--json" "@wdio/cli@latest"`
[verbose] [parsed package metadata (single)]
NpmViewData { name: "@wdio/cli", version: Version { major: 5, minor: 12, patch: 5, pre: [], build: [] }, dist: RawDistInfo { shasum: "f4121b0d7682f67431521b83aa213c23128341a2", tarball: …
```
> Ensure download directory exists for tarballs

- crates/volta-core/src/error/details.rs
- crates/volta-core/src/run/binary.rs
- crates/volta-core/src/run/mod.rs
- crates/volta-core/src/run/node.rs
- crates/volta-core/src/run/npm.rs
- crates/volta-core/src/run/npx.rs
- crates/volta-core/src/run/yarn.rs
- crates/volta-core/src/tool/package/resolve.rs
- src/command/which.rs
Closes #545 
Info
-----
* The current implementation of `volta install <package>` call `npm view` and relies on the existing `PATH` / shims to execute `npm`.
* This means that calling the command requires calling the shims, which then have to re-build all of Volta's state, before finally calling `npm` directly.
* With the refactor in #505, it's now possible to access the `Session` object while resolving a package version, so we can create the command and call `npm` directly.
* This cuts out one layer of indirection and allows us to provide nicer error messages about the existence of `node` on the system.
* Additionally, we can now separate being unable to find the package from being unable to find `npm` / `node`, so we can improve the error messaging around the failure states.
Changes …
> Improve Error Messages around 'npm view'

- crates/test-support/src/paths.rs
As of Rust 1.38, `ONCE_INIT` is deprecated in favor of `Once::new()` and is showing a warning. Switched the initialization to use that method, and confirmed that it compiles correctly on our stated minimum Rust version 1.34.0
> Update the initialization of Once to use the const constructor

- Cargo.toml
- azure-pipelines.yml
- ci/check-overrides.sh
- ci/run-tests-updates.yml
- crates/volta-core/Cargo.toml
Info
-----
* To support working on Volta updates in parallel with other changes, we want to hide the updates work behind a feature flag, which is well supported by `cargo`
* We also want PRs involving the update work to test that work as it goes in, but don't want the update tests to break non-updates CI.
Changes
-----
* Added a `volta-updates` feature flag to `Cargo.toml` for the root project and for `volta-core`
* Added a CI override `[volta updates]` in the commit message that will run the automated tests with the feature flag enabled.
* Added new jobs to `azure-pipelines.yml` to enable the feature flag tests only if the CI override is detected.
> [volta updates] Add volta-updates feature and CI override

- src/cli.rs
- src/command/activate.rs
- src/command/deactivate.rs
Suggestion from @thoov in #559: Add deprecation warning to `volta activate` and `volta deactivate` for the `0.6.x` releases, so that users get a warning that they are going away.
Then when we remove them in `0.7.0` with the update work, it won't be completely out of nowhere to the users.
> Add deprecation warnings to activate and deactivate

- src/command/list/mod.rs
We are currently using `info!` to write the output of `volta list`. However, that goes to `stderr` since it is part of the logging interface. Since the expected effect of running `volta list` is output to the terminal, we should directly write to stdout using `println!` instead.
This aligns with `volta which` also writing to stdout, since it is expected output instead of a purely informational note about what happened.
> Write 'volta list' output to stdout directly

- crates/volta-core/src/manifest/mod.rs
- crates/volta-core/src/manifest/serial.rs
- crates/volta-core/src/project.rs
- crates/volta-core/src/session.rs
- crates/volta-core/src/tool/node/mod.rs
- crates/volta-core/src/tool/yarn/mod.rs
- src/command/list/mod.rs
- src/command/list/toolchain.rs
- tests/acceptance/volta_pin.rs
- tests/smoke/support/temp_project.rs
Closes #522 
Info
-----
* Currently our `Project` state is lazily evaluated and then never updated when we make changes.
* This means that if we try to `volta pin` both Node and Yarn in the same command, the first one succeeds (pinning Node), but the second fails (pinning Yarn) because it looks at the internal `Project` and thinks that Node isn't pinned yet.
* We should update the internal state to reflect any changes that we make, so that future pins in the same command will see the true state, instead of an outdated one.
Changes
-----
* Switched the `LazyProject` and related methods to return a reference instead of an `Rc`
* Added the ability to get a mutable reference to the project.
* Updated `Manifest` to separate changing the stored `PlatformSpec` and writing those changes into …
> Allow Pinning Node and Yarn in a single command

- Cargo.lock
- Cargo.toml
- crates/test-support/Cargo.toml
Hamcrest2 released version `0.3.0` this week, which includes a fix for the deprecation warning we were seeing when compiling for test (specifically they had a collision between the name of a function and the name of a macro, so when we were importing the macro per Rust 2018 edition, we were seeing a warning that the function was deprecated).
Updating to the newer version doesn't appear to break anything we were using it for in test, so this PR removes those erroneous warnings.
> Upgrade to hamcrest2 v0.3.0

- crates/fs-utils/src/lib.rs
- crates/validate-npm-package-name/src/lib.rs
Enabling Clippy in VS Code shows a few more warnings that weren't being surfaced by running `cargo clippy` in an already-built project.
> Fix a few more clippy warnings that didn't surface immediately

- ci/run-tests-updates.yml
The "features" list in the Updates CI runs was incorrectly specified, causing the Acceptance and Smoke tests to wind up running a no-op instead of the actual tests.
> [volta updates] Fix commands for running acceptance and smoke tests

- crates/volta-core/src/lib.rs
- crates/volta-core/src/platform/mod.rs
- crates/volta-core/src/run/mod.rs
- crates/volta-core/src/session.rs
- src/cli.rs
- src/command/mod.rs
- tests/acceptance/intercept_global_installs.rs
- tests/acceptance/main.rs
- tests/acceptance/support/sandbox.rs
Related to #222 
Closes #562 
Closes #216 
Closes #165 
Closes #104 
Closes #99
Info
-----
* As part of the push towards automatic updates, we want to enable Volta to work directly on the command line, instead of through a shell function wrapper.
* The purpose of the function wrapper was to allow the `volta activate` and `volta deactivate` commands to work as expected, modifying the PATH environment variable for the current shell.
* However, those commands were intended as a release valve for when we were in early testing phases, and are no longer needed since Volta is much more stable now.
Changes
-----
* Removed the `activate` and `deactivate` commands from the Volta CLI and the associated `ActivityType`
* Moved the `VOLTA_UNSAFE_GLOBAL` environment variable definition to the `run` …
> [Updates] Remove 'volta activate' and 'volta deactivate' commands

- crates/volta-core/src/error/details.rs
- crates/volta-core/src/run/mod.rs
- tests/acceptance/main.rs
- tests/acceptance/volta_bypass.rs
Closes #599 
Info
-----
* `volta activate` and `volta deactivate` are built as Shell functions that only work in specific unix shells.
* They also don't cleanly interact with the proposed update logic since they require a different install process than we want to support.
* #562 Removed them as part of the updates work, which is still behind a feature flag for the moment.
* However, the escape hatch still has uses (most notably to work with custom versions of npm until we implement installing and pinning npm)
* To provide similar functionality, in a cross-platform way, we want to add a `VOLTA_BYPASS` environment variable that will cause the shims to skip their normal logic and shell out to the existing (non-Volta) system.
Changes
-----
* Added logic to `execute_tool` that checks for the …
> Add VOLTA_BYPASS override to short-circuit shim behavior

- Cargo.lock
- Cargo.toml
- crates/volta-core/src/error/details.rs
- crates/volta-core/src/layout/mod.rs
- crates/volta-core/src/session.rs
- crates/volta-core/src/style.rs
- src/cli.rs
- src/command/mod.rs
- src/command/setup.rs
Closes #564 
Closes #535 
Info
-----
* To support managed installs and automatic updates, we want to have a new command: `volta setup`
* `volta setup` Will bootstrap Volta from a situation where only the binaries are available to a fully-working Volta system. This will allow users in managed situations to "enable" Volta on their system.
* Additionally, the current installers can be simplified with this command to only (see #565):
1. Install the binaries
2. Call `volta setup`
Changes
-----
* Added `volta setup` command behind the `volta-updates` feature flag, along with implementations for both Unix and Windows.
* On both systems, the `VOLTA_HOME` file system layout is initialized.
* On Unix, we iterate through the same list of profile scripts that the installer uses, and add Volta lines …
> [Updates] Add 'volta setup' command

- crates/volta-core/src/error/details.rs
- crates/volta-core/src/inventory/mod.rs
- crates/volta-core/src/manifest/serial.rs
- crates/volta-core/src/run/npx.rs
- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/node/fetch.rs
- crates/volta-core/src/tool/node/resolve.rs
- crates/volta-core/src/tool/package/install.rs
- crates/volta-core/src/tool/package/resolve.rs
- crates/volta-core/src/tool/package/serial.rs
- crates/volta-core/src/tool/serial.rs
- crates/volta-core/src/tool/yarn/fetch.rs
- crates/volta-core/src/tool/yarn/resolve.rs
- crates/volta-core/src/version/mod.rs
- tests/smoke/volta_install.rs
Closes #491 
Closes #480 
Info
-----
Our current `volta install <package>` process has a few slightly-related issues that have come up multiple times:
* We currently select the latest version of Node that matches the `engines` field (or the latest overall if there are no `engines`), which can result in broken CLI tools when there is a major version bump.
* We don't currently support tag versions other than `latest` (e.g. `beta`).
Changes
-----
* Reworked the `VersionSpec` field to support tags, with `latest` and `lts` special-cased since they require additional handling.
* Updated the package resolve logic to support resolving version tags as well as pure versions or version ranges.
* Added an internal-only tag type (that can't be created using the `FromStr` implementation): …
> Package Install Improvements

- dev/rpm/build-rpm-updates.sh
- dev/rpm/volta-updates.spec
- dev/unix/release-updates.sh
- dev/unix/volta-install-updates.sh
- wix/updates.wxs
Closes #565 
Info
-----
* With `volta setup` created in #578, we can simplify the installers that we currently support to do 2 things:
* Install the binary files (`volta` and `volta-shim`) onto the PATH
* Call `volta setup` to handle creating the user directory and adding the Shim directory to the PATH
Changes
-----
* Added new installers for Windows (`updates.wxs`), Unix (`volta-install-updates.sh`), and RPM (`volta-updates.spec`).
* Copied and updated helper scripts (`release.sh` and `build-rpm.sh`) to support compiling with the `volta-updates` feature so that `volta setup` is available.
Notes
-----
* This PR builds on #578, so will remain a draft until that is merged
> [Updates] Create new installers that use 'volta setup'

- crates/volta-layout/src/v1.rs
In #610, the names of some of the layout functions were changed to `default_` from `user_`, however that change wasn't propagated into #590 before it was committed.
Fixes the naming to align with the new `v0` names, allowing Volta to correctly build when the `volta-updates` feature flag is enabled (no functional changes).
> Fix merge issue with v1 layout naming

- crates/volta-migrate/src/v1.rs
- tests/acceptance/migrations.rs
Closes #617 
The layout file was being written on a migration from a legacy V0 layout, but not on creation of an entirely new layout. This was causing the migration to run on every invocation, detecting the system as being in a "new" state, and then not write the layout file.
Updated the logic so both types of migrations result in writing the layout file before finishing.
> [volta updates] Ensure layout file is written on new installation

- ci/build-api-docs.yml
It appears that setting RUSTDOCFLAGS="--document-private-items" can cause
rustdoc to fail because the setting is set twice, once by cargo and again
by the environment variable. This results in the docs builds failing to
execute.
Updated to use the cargo flag, which ensures that the flag is only passed
to rustdoc once.
Also updated the build-api-docs CI task to include recently added crates.
> [ci docs] Use the cargo flag for --document-private-items

- Cargo.lock
- crates/volta-core/Cargo.toml
- crates/volta-core/src/hook/tool.rs
- crates/volta-core/src/layout/mod.rs
- crates/volta-core/src/tool/package/fetch.rs
- crates/volta-core/src/tool/package/mod.rs
- src/command/list/plain.rs
Closes #635 
Closes #630 
Closes #586 
Info
-----
* We use `fs::canonicalize()` in a few places to resolve relative paths and potential symlinks to the target file.
* On Windows, `canonicalize` returns a UNC path with `\\?\` in the prefix, however those paths cause issues in a number of use-cases (see also https://github.com/rust-lang/rust/issues/42869):
* JS Scripts that append paths using concatenation instead of `path.join` can cause issues, since UNC paths don't support `/` as a separator (see #635 and #586)
* We incorrectly fail to remove the Volta install directory from the PATH variable when doing a passthrough, because the comparison between `C:\...\Volta` and `\\?\C:\...\Volta` fails to match. This can cause an infinite loop of calls to the built-in shims, since they aren't …
> Remove UNC Prefix after Canonicalize on Windows

- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/package/mod.rs
- tests/acceptance/volta_uninstall.rs
- Move the logic of showing success/warn into `package::uninstall`
- Show `uninstall success` when package config exists or orphaned binary exists
- Matched unpacked and initialized package won't trigger `uninstall success`
Let me know if there is anything missing or anything I need to change. Thanks!
> Fix #636: Improve volta uninstall messaging for non-installed packages

- crates/volta-core/src/style.rs
- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/node/mod.rs
- crates/volta-core/src/tool/yarn/mod.rs
Closes #609 
Adds a `note:` message after running `volta install` inside a pinned project, reminding the user of the version they have pinned.
I'm more than happy to hear suggestions of better verbiage or formatting for the note, if there are any.
> Add note when running 'volta install' within a project

- crates/volta-core/src/tool/package/install.rs
Closes #643 
Info
-----
* Packages are sometimes published from Windows with CRLF (`\r\n`) as the line-ending on the scripts.
* This causes issues with shebang loaders, since Unix interprets `\r` as part of the command, instead of part of the EOL marker.
* Volta already supports parsing and storing information about the loader to use when running the command, we can take advantage of that to remove unexpected whitespace before calling the appropriate program.
Changes
-----
* Moved the `determine_script_loader` function out of OS-specific code and set it up to run on all platforms.
* Added a call to `.trim()` to the loader to remove any extraneous `\r` (and other whitespace) characters from the arguments before storing them.
Tested
-----
* Confirmed that the package listed in the original …
> Trim loader and store on all platforms

- crates/volta-core/src/error/details.rs
- src/command/completions.rs
Previously, we were failing when any part of the path did not exist, and reporting the wrong error to boot. Here, we attempt to create the directory instead, informing the user that we are changing their file system. Adds a new error scenario to cover a failure (e.g. a permissions error on creation), and a success message after writing the completion file.
Fixes #645
> Support creating completions in new directories

- tests/acceptance/main.rs
- tests/acceptance/support/sandbox.rs
The acceptance tests were written with only a few lines marked `#[cfg(feature = "mock-network")]`, however they all actually depended on that feature, since the tests wouldn't compile without it. Updated the test section to rely on that feature flag at the top-level, instead of lower down, so that it always compiles (though no tests will run without the flag).
> Make all acceptance tests depend on 'mock-network' flag

- crates/volta-core/src/shim.rs
- crates/volta-migrate/src/lib.rs
- src/command/setup.rs
- src/common.rs
- tests/acceptance/migrations.rs
Closes #661 
Info
-----
* Since the `volta setup` command is designed to make sure the user's system is correctly set up for Volta, it should also make sure to enforce that the shims are pointing to the correct location.
* Currently `volta` commands will only regenerate the shims if a migration is run.
Changes
-----
* Moved `regenerate_shims_for_dir` function into `volta_core::shim` module, instead of the `volta-migrate` module.
* Ensured that `regenerate_shims_for_dir` is always called after a migration runs, to maintain existing functionality.
* Added a call to `regenerate_shims_for_dir` into `volta setup` command, so that even if a migration doesn't run, `volta setup` will still cause the shims to be rebuilt.
Tested
-----
* Confirmed that running `volta setup` on an otherwise fully …
> Regenerate shims on 'volta setup'

- shell/windows/shim.cmd
- shell/windows/volta.cmd
- shell/windows/volta.ps1
- wix/main.wxs
Closes #660 
Info
-----
* Some tools on Windows (notably React Native) expect `npm` to be available through `npm.cmd`, which is provided by the standard `npm` installation.
* Volta doesn't currently have a `*.cmd` for the core shims (`npm`, `npx`, and `yarn`).
Changes
-----
* Created a passthrough shim that will call the executable with the same name (e.g. `npm.cmd` will call `npm.exe`)
* Updated the Windows installer to create a `.cmd` file for each of the 3 node tools that we install direct shims for: `npm.cmd`, `npx.cmd`, and `yarn.cmd`
* Also removed old `cmd` and `ps1` files that were left over from early Notion days.
Tested
-----
* Installed using the installer and confirmed that the `cmd` files are created.
* Manually verified that calling `npm.cmd --version` correctly runs the …
> Add shim CMD file to support tools that rely on CMD

- src/command/setup.rs
Closes #665 
Info
-----
* Due to how VS Code launches a shell using the existing environment, shells launched with VS Code already have the Volta shim directory on the PATH, before the run any profile / startup scripts.
* As a result, we detect that Volta is on the PATH and don't update it, however it is so far back on the PATH that it is superseded by any existing `node` / `npm` / `yarn` installation already on the machine.
* This causes `node --version` to output the wrong thing when using the VS Code terminal, while using a normal terminal directly works as expected.
Changes
-----
* Updated the lines that we write to profile scripts to always append `$VOLTA_HOME/bin` to the PATH, instead of first checking if it already exists and then updating.
Tested
-----
* Tested both `zsh` and …
> Always add Volta shims to PATH

- azure-pipelines.yml
Per [this article](https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/) and warnings in the logs, Microsoft will be removing the MacOS 10.13 image we are using for our Mac builds from the public-hosted images.
Following their suggestion to migrate to 10.14.
> Update CI to use MacOS 10.14 image

- dev/unix/volta-install.sh
Related to an issue reported in Discord: When the installer fails to create `$install_dir` and `$install_dir/bin`, it prints out the error messages but then continues along as if everything is okay. This ultimately results in errors later in the process, but we should detect that situation and show an accurate error message immediately.
Added an early exit if the `mkdir` calls fail.
> Exit early with an error message if creating install dir fails

- crates/volta-core/src/project.rs
- crates/volta-core/src/tool/yarn/mod.rs
- crates/volta-core/src/toolchain/mod.rs
Info
-----
* Currently our methods for setting the default `npm` and `yarn` only accept a real version, so it is not possible to unset those values (or set them back to `None`).
* Similarly, the methods for pinning `npm` and `yarn` also expect a real version.
* Allowing these to be unset will be necessary for `volta install npm@bundled`, as well as for supporting `volta uninstall yarn` at some point in the future.
Changes
-----
* Updated `Toolchain` methods `set_active_yarn` and `set_active_npm` to accept an `Option<Version`, instead of a `&Version`.
* Updated `Project` methods `pin_yarn` and `pin_npm` to also accept an `Option<Version>`
* Updated the call sites of each of those methods to pass an `Option`.
Tested
-----
* All tests pass
Note
-----
* This is a small, self-contained PR to …
> Support clearing as well as setting npm and yarn

- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/node/mod.rs
- crates/volta-core/src/tool/npm/mod.rs
- crates/volta-core/src/tool/package/install.rs
- crates/volta-core/src/tool/package/mod.rs
- crates/volta-core/src/tool/yarn/mod.rs
Info
-----
* Currently we have an enum `tool::Resolved`, whose only purpose is to store a `Tool` implementation and dynamically dispatch to the contained `Tool` when one of the methods is called (`fetch`, `install`, or `pin`).
* This is effectively the same as dynamic dispatch with trait objects, so we can implement that and save on some boilerplate.
* Additionally, the switch to trait objects makes sense in the context of #691, which introduces a new `Tool` implementation: `BundledNpm`
Changes
-----
* Removed `Resolved` enum and it's implementation.
* Updated `Spec::resolve` to return a `Box<dyn Tool>` instead of a `Resolved`
* Updated `Tool` trait to use `self: Box<Self>` as the self-type for all methods.
* Fixed the implementations to all take `self: Box<Self>`
Tested
-----
* All tests …
> Use dynamic dispatch for tool objects

- Cargo.lock
- crates/volta-core/src/layout/mod.rs
- crates/volta-core/src/platform/image.rs
- crates/volta-core/src/platform/test.rs
- crates/volta-core/src/tool/node/fetch.rs
- crates/volta-core/src/toolchain/mod.rs
- crates/volta-layout/src/lib.rs
- crates/volta-layout/src/v2.rs
- crates/volta-migrate/Cargo.toml
- crates/volta-migrate/src/lib.rs
- crates/volta-migrate/src/v1.rs
- crates/volta-migrate/src/v2.rs
- tests/acceptance/migrations.rs
- tests/acceptance/support/sandbox.rs
- tests/smoke/support/temp_project.rs
- tests/smoke/volta_fetch.rs
- tests/smoke/volta_install.rs
Info
-----
* To support custom npm versions, there are a few changes that need to be migrated:
* First, we should remove the `npm` version from the PATH to the Node image directory, since that Node will be used regardless of the npm version.
* Second, we should make sure that if the default npm version is set in `platform.json` (our internal state), we remove it, since in the new paradigm a value being set represents a custom npm version, and until now we have only had bundled versions.
* Additionally, there was some friction when adding a new migration, so I created a macro to deduplicate some of the detection work.
Changes
-----
* Added a macro for creating methods to handle detecting the existing Volta layout version (checking each existing layout file to see if it exists.
* Added a …
> Implement Migration to support custom npm versions

- crates/volta-core/src/inventory.rs
Closes #700 
Info
-----
* To find all installed packages, we were walking the package config directory with a `max_depth` set to `1`.
* Per the [WalkDir docs](https://docs.rs/walkdir/2.3.1/walkdir/struct.WalkDir.html#method.max_depth), `max_depth(1)` means that we only look at the direct descendants of the directory we started at, so we won't look at any file in subdirectories.
* However, when we install a scoped package, it winds up in a subdirectory as a result of the name having a `/` in it.
* This means `volta list` was not correctly showing scoped packages at all.
Changes
-----
* Updated to use `max_depth(2)`, which will find the children of subdirectories as well. We shouldn't need more than one additional directory, since `npm` forbids packages having a `/` in them, except for the …
> Ensure Scoped Packages are cataloged by `volta list` 

- dev/unix/volta-install.sh
Depending on environment configuration, `download_release_from_repo`
could write to stdout both through `curl` and `echo`.
The install script becomes more robust when we explicitly tell `curl` to
write out the effective name where the download was saved, and nothing
else.
Fixes #686.
> volta-install.sh: make curl write out downloaded file name

- crates/volta-core/src/run/binary.rs
- crates/volta-core/src/run/mod.rs
- crates/volta-core/src/run/node.rs
- crates/volta-core/src/run/npm.rs
- crates/volta-core/src/run/npx.rs
- crates/volta-core/src/run/yarn.rs
- crates/volta-core/src/tool/package/fetch.rs
- crates/volta-core/src/tool/package/resolve.rs
Info
-----
* As part of investigating how to implement `volta run`, it became clear that the `ToolCommand` constructors were doing too much work.
* By setting all of the args on the constructor, we needed to know all of the args at a single time, which meant that the `args` had to be passed to each Tool's `run` method, even though the only thing they were used for was to then pass along to the `ToolCommand`.
* We also already had wrapper behavior for the `current_dir` method, so it made sense to add `args` behavior in a similar way.
Changes
-----
* Updated `ToolCommand` to support `arg` and `args` methods (passing them to the eventual command)
* Updated `execute_tool` to pass the args directly to the command after it is constructed.
* Updated `binary::command` to pass its args before …
> Decouple args from ToolCommand constructors

- crates/volta-core/src/error/details.rs
In testing `volta run`, I noticed that the error message for when Yarn isn't available outside of a Project was missing a backtick on the `` `volta help install` `` prompt.
> Fix typo in NoDefaultYarn error message

- crates/volta-core/src/style.rs
- src/command/list/human.rs
- src/command/list/mod.rs
This PR is the implementation of @chriskrycho 's RFC https://github.com/volta-cli/rfcs/blob/info-commands/text/0000-informational-commands.md
Since the basic code structure and tests has been completed, I tried my best to follow the original design as much as possible. However, I noticed a few places that I have to change:
From the RFC, command `volta list package` should print out the header message as `<package> versions in toolchain:`. However, since we don't have a way to get the package name from CLI argument, I'm just showing a generic message here: `⚡️ Package versions in your toolchain:`.
---
From the RFC, when listing packages in `list all`, the packages should be grouped by package name and then version, like:
```
Packages:
<package name>
[<version> (default | current @ <project …
```
> Implement `volta list` for human

- crates/volta-core/src/hook/mod.rs
- crates/volta-core/src/hook/serial.rs
Info
-----
* To support resolving and installing `npm` versions, we need to add support for `npm` hooks, so that the process can be redirected in the same way as `node` and `yarn`
* These hooks currently will never be called, as fetching `npm` has not been implemented, but that will be included in another PR.
Changes
-----
* Added `npm` hook type to the `HookConfig` object.
* Added deserialization of `npm` hooks.
Tested
-----
* All tests pass
> [npm] [Tiny] Add support for npm hooks

- crates/test-support/src/matchers.rs
- crates/volta-core/src/run/mod.rs
With the latest `clippy` release, there are now warnings about calling `nth(0)` on an iterator, which is equivalent to calling `next()`.
Updated the couple of locations where we called `nth(0)` to use `next()` instead.
> Fix clippy warnings about nth(0)

- crates/volta-core/src/tool/node/mod.rs
I wanted to run some node scripts on my raspberry pi so I got this working tonight.
The Pi 3b is on armv7l arch:
```
$ uname -a
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
```
I had to compile using nightly, and that worked fine
```
$ ./dev/unix/volta-install.sh --release
```
Then everything else just worked
```
$ volta install node
success: installed and set node@12.16.2 (with npm@6.14.4) as default
$ node --version
v12.16.2
$ node  -e "console.log(process.platform, process.arch)"
linux arm
$ volta install yarn
success: installed and set yarn@1.22.4 as default
$ yarn --version
1.22.4
$ volta install cowsay
success: installed cowsay@1.4.0 with executables: cowthink, cowsay
$ cowsay ⚡️⚡️⚡️
________
< ⚡️⚡️⚡️ >
--------
\   ^__^
\  (oo)\_______
(__)\ …
```
> Support armv7l architecture (for Raspberry Pi)

- crates/volta-core/src/inventory.rs
- src/command/list/human.rs
- src/command/list/mod.rs
- src/command/list/plain.rs
- src/command/list/toolchain.rs
Info
-----
* As the first step of adding support for `volta install npm` and `volta pin npm`, we need to make sure that we can manage and query the inventory for `npm`.
* In line with querying the inventory, `volta list` should be updated to include custom `npm` versions as well.
Changes
-----
* Added `npm_available` and `npm_versions` function to `inventory`, analogous with the already-existing `node` and `yarn` functions.
* Updated `volta list` behavior to query and interpret fetched `npm` versions.
Tested
-----
* Added new tests to `plain.rs` that cover outputting `npm`
* All tests pass
> [npm] [Medium] Add support for querying and list 'npm' inventory

- Cargo.lock
- Cargo.toml
- crates/volta-core/Cargo.toml
- crates/volta-core/src/error/reporter.rs
- tests/acceptance/verbose_errors.rs
Closes #677 
Info
-----
* In CI environments, writing the error details into a log file isn't helpful, as the file is often deleted along with everything else when the run is complete.
* Instead, we should write error details directly to the console when in CI, so that they are available when reviewing the console logs later.
Changes
-----
* Updated `error::reporter.rs` to print any additional error details out to the console in CI environments.
Tested
-----
* Updated error reporting tests to mock the CI environment as needed.
* Added tests to confirm the error information is written out in CI (with mocks, so they work locally as well).
* All tests pass.
> [Small] Ensure error details are written to the terminal in CI environments

- crates/volta-core/src/error/reporter.rs
- src/cli.rs
Closes #675 
Info
-----
* Most of our colorized output is already run through the `console` crate, which auto-detects whether or not we should use colors based on the terminal.
* However, our help output was always using colors
* Additionally, we shouldn't write color codes into a file when writing the error log.
Changes
-----
* Updated the root StructOpt definition to use `clap::AppSettings::ColorAuto` instead of `clap::AppSettings::ColorAlways`, so that the output will be colorized based on whether or not the terminal is interactive.
* Added calls to `strip_ansi_codes` when writing the error log, so that we avoid writing any color / style codes into the error file.
Tested
-----
* Confirmed that `volta help | pbcopy` doesn't include any ANSI codes
* Confirmed that ANSI codes are no …
> [Tiny] Prevent writing color codes to error logs and help

- .github/workflows/release.yml
- ci/build-and-package.sh
- ci/build-with-openssl.sh
- ci/docker/Dockerfile
- ci/volta.manifest
Closes #676 
Info
-----
* To streamline and normalize the release process, we should build all the artifacts in CI, instead of on an individual maintainer's machines.
* We can use GitHub Actions to trigger these builds whenever a tag is pushed to the repository, allowing us to still have control over when releases are created.
* GitHub Actions can also create a new release and upload the artifacts so that it is ready for publishing.
Changes
-----
* Added `release.yml` with jobs to build all the necessary binaries and create a new Release in the repository.
* Added Dockerfile and supporting scripts to `ci` directory for Linux builds.
Notes
-----
* The release process will be triggered whenever we push a tag with the name `v<version>` to the repo.
* MacOS and Windows build are …
> Automate creation of releases with GitHub Actions

- crates/volta-core/src/platform/image.rs
- crates/volta-core/src/platform/mod.rs
- crates/volta-core/src/platform/test.rs
- crates/volta-core/src/run/npm.rs
- crates/volta-core/src/run/npx.rs
Info
-----
* To support custom `npm` versions, we need `Image` to be aware of the difference between custom and bundled `npm`
* We also need to ensure that the path to a custom `npm` version is earlier in the PATH than the path to the `node` directory, otherwise the bundled version will always win.
* We still need to maintain the ability to look up the actual `npm` version if needed, even if it is bundled.
Changes
-----
* Updated `Image` to hold an `Option` for `npm`, noting that `None` represents the version bundled with Node
* Updated `Image::bins` to properly order the bins to support custom `npm` (ensuring that `npm` is before `node` in the list)
* Added a `resolve_npm` method to `Image`, so that the explicit version can be looked up (including resolving the bundled version, if …
> [npm] [Small] Support Custom and Bundled npm in Image

- crates/archive/src/tarball.rs
- crates/archive/src/zip.rs
- crates/headers-011/src/lib.rs
- crates/volta-core/src/event.rs
- crates/volta-core/src/manifest/mod.rs
- crates/volta-core/src/manifest/serial.rs
- crates/volta-core/src/monitor.rs
- crates/volta-core/src/platform/mod.rs
- crates/volta-core/src/platform/test.rs
- crates/volta-core/src/project.rs
- crates/volta-core/src/run/binary.rs
- crates/volta-core/src/run/node.rs
- crates/volta-core/src/run/npm.rs
- crates/volta-core/src/run/npx.rs
- crates/volta-core/src/run/yarn.rs
- crates/volta-core/src/session.rs
- crates/volta-core/src/style.rs
- crates/volta-core/src/tool/node/resolve.rs
- crates/volta-core/src/tool/package/install.rs
- crates/volta-core/src/tool/package/serial.rs
- crates/volta-core/src/toolchain/mod.rs
- crates/volta-core/src/toolchain/serial.rs
- crates/volta-fail-derive/src/lib.rs
- crates/volta-layout-macro/src/ast.rs
- src/command/list/mod.rs
- src/command/list/toolchain.rs
- src/command/which.rs
Info
-----
In #626, we updated the model of `PlatformSpec` to support sources for individual Tools, instead of an overall source for the `PlatformSpec` as a whole. In order to make things ergonomic for both producers and consumers of `PlatformSpec` types, we used a trait and different implementations of that trait. However, while this solved the problem, work on `volta run` revealed some lingering ergonomic issues.
The core issue is that our model had 2 concepts combined into 1: `PlatformSpec` represents _either_ a single source of truth (e.g. from `package.json`) _or_ a ready-to-use merged platform (e.g. from `Session::current_platform`). While these two are _related_ (and often one comes directly from the other), they are not the _same_. Trying to support both concepts at the same time …
> [run] [Large] Rethinking of Platform / Image Sources

- .github/workflows/release.yml
See [the GitHub changelog post](https://github.blog/changelog/2020-04-28-github-actions-v2-artifact-actions/) for more details.
> Migrate to actions/upload-artifact@v2 and actions/download-artifact@v2

- tests/acceptance/migrations.rs
With the new GitHub annotations, we're surfacing a number of clippy warnings that were otherwise hidden. Fixing the outstanding warning around cognitive complexity of one of the test methods.
> Fix cognitive complexity warning in migration test

- tests/acceptance/volta_install.rs
- tests/acceptance/volta_pin.rs
The change in #691 to show an error when unable to determine the bundled version of `npm` after running `volta install npm@bundled` or `volta pin npm@bundled` broke the tests of that behavior, but somehow they passed the PR CI (though not the merge CI).
Updated the tests to make sure that the npm version file is available for all of those tests.
> Update npm@bundled tests to ensure the default version file is available

- tests/smoke/autodownload.rs
- tests/smoke/volta_fetch.rs
- tests/smoke/volta_install.rs
We are seeing intermittent failures trying to download Node in the smoke tests. Updated the tests to use more recent versions of Node, as well as to use different versions for each test.
> Update the versions of tools used in the smoke tests

- crates/volta-core/src/tool/node/resolve.rs
Closes #242 
Info
-----
* The current cache of the Node index is global and doesn't know about the fact that hooks can affect the URL we check for the Node index.
* This means that if you create the cache using the public repo, but then switch to a project that has hooks pointing to a private repo, the cache used will still be that of the public repo.
* Problems can arise when a private repo has a subset of the publicly available versions of Node, because the cache could result in us writing an invalid Node version into `package.json`, even though the project is correctly configured with Volta hooks.
Changes
-----
* Updated the cache format to include the URL that was fetched as the first line, followed by the contents.
* Updated the function that reads the cache to check for the URL at …
> Make node index cache aware of the cached URL

- crates/volta-core/src/error/details.rs
- crates/volta-core/src/platform/mod.rs
- crates/volta-core/src/platform/test.rs
- crates/volta-core/src/run/binary.rs
- crates/volta-core/src/run/mod.rs
- crates/volta-core/src/run/node.rs
- crates/volta-core/src/run/npm.rs
- crates/volta-core/src/run/npx.rs
- crates/volta-core/src/run/yarn.rs
- crates/volta-core/src/session.rs
- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/package/fetch.rs
- crates/volta-core/src/tool/package/resolve.rs
- src/cli.rs
- src/command/mod.rs
- src/command/run.rs
- src/volta-shim.rs
- tests/acceptance/main.rs
- tests/acceptance/volta_run.rs
- tests/smoke/main.rs
- tests/smoke/volta_run.rs
Info
----
* As described in https://github.com/volta-cli/rfcs/pull/39, we want to have a `volta run` command that allows you to override the detect `node` and `yarn` versions when running a specific command.
Changes
-----
* Added `CommandLine` source for Platforms and an `InheritOption` type that represents one of 3 possibilities: A Value, No Value but allowed to inherit, and No Value but _not_ allowed to inherit.
* Added a `CliPlatform` type that represents the data we can potentially get from the CLI (including the ability to prevent inheriting from the contextual Platform).
* Created the `run` command that parses the options and passes them to the core logic to execute.
Tested
-----
* Manual testing of `volta run` in different scenarios.
* Added unit tests around new Platform behaviors …
> [run] [Large] Implement `volta run` command

- .github/workflows/test.yml
Attempting to improve the stability of the smoke tests by returning to single-threaded
> Return to using single-threaded smoke tests

- src/cli.rs
The description of `volta run` wasn't updated to include `npm`, so it only mentions Node and Yarn.
> Include npm in the description of Volta run

- .github/workflows/release.yml
It turns out that in a `push` workflow, `github.ref` actually has the value: `refs.tags.{tagname}`, not just `{tagname}`, so we need to update our logic for parsing the version out of the ref.
Skipping the first 11 characters means stripping off the `refs.tags.v` from `refs.tags.v{version}`, leaving just the version number, which we can then use for naming the release artifacts.
> Update release automation to correctly parse the version

- Cargo.lock
- Cargo.toml
- crates/archive/Cargo.toml
- crates/archive/src/lib.rs
- crates/archive/src/tarball.rs
- crates/archive/src/zip.rs
- crates/volta-core/Cargo.toml
- crates/volta-core/src/tool/node/resolve.rs
- crates/volta-core/src/tool/npm/resolve.rs
- crates/volta-core/src/tool/package/resolve.rs
- crates/volta-core/src/tool/yarn/resolve.rs
Info
-----
* As originally found by @joshuarli in #536, we don't need all the async features of `reqwest` in Volta, since all of our HTTP access is synchronous.
* Unfortunately, while `reqwest` provides a synchronous API, it still uses the async engine and task executor (`tokio`) under the hood.
* Compiling that bloats our build times and executable size, by bringing in an entire async executor when we don't actually use it.
* `attohttpc` is a purely-synchronous HTTP Request client with a very similar API to `reqwest`.
Changes
-----
* Removed `reqwest` and added `attohttpc` to all of the appropriate crates.
* Upgraded `hyperx` to `1.0.0`, to match the transitive dependency on `http`
* Updated the code to fit `attohttpc`s slightly different API
Notes
-----
* This results in a ~25% …
> Use attohttpc instead of reqwest for fetching

- src/command/run.rs
Closes #745 
Info
-----
* The `--npm` option to `volta run` was incorrectly marked as conflicts with `--no-npm`, which doesn't exist
* This was causing `volta completions` to panic
Changes
-----
* Updated the `#[structopt]` attribute to correctly point to `bundled_npm` instead of `no_npm`
Tested
-----
* Confirmed that `volta completeions zsh` doesn't panic
> Fix 'conflicts_with' argument for run command

- README.md
The badge in `README.md` is still pointing at Azure Pipelines, which we aren't using any more. Updated to reflect the GitHub Actions build status.
> Update README badges to reflect GitHub Actions

- crates/volta-core/src/event.rs
- crates/volta-core/src/hook/mod.rs
- crates/volta-core/src/project.rs
- crates/volta-core/src/session.rs
- tests/acceptance/hooks.rs
- tests/acceptance/main.rs
- tests/acceptance/support/sandbox.rs
Info
-----
* Since project-local hooks were implemented, the work to detect a project root (walking up the file system looking for `package.json` was duplicated between `Project` and `HookConfig`.
* With the prospect of support for workspaces coming soon, that work has the potential to grow significantly, since it will now involve parsing `package.json` to find the `extends` key.
* To prevent that duplication, we should use the values already detected by the `project` to locate project-local hooks.
Changes
-----
* Updated `HookConfig` to accept an optional `Project` item, and use the already detected `project_root` to find project-local hooks.
* Refactored the `merge` functions to be more idiomatic Rust methods, making the precedence more explicit with `self` and `other` instead of `left` …
> [Medium] Refactor hooks loading to avoid repeating project detection

- crates/volta-core/src/project.rs
- src/command/list/human.rs
- src/command/list/mod.rs
- src/command/list/plain.rs
- src/command/list/toolchain.rs
Info
-----
* As discussed in #711, the output of `volta list` (both formatters) around project-local binaries is inaccurate.
* Though we don't yet have a clear path forward for determining the version / platform for project-locals, we can remove the incorrect information so as not to confuse the user.
Changes
-----
* Updated the `list::Package` data model to not include version or platform for local packages.
* Updated the logic for detecting a local package to not try to match on version (which didn't work anyway, because package.json is almost always filled with semver requirements).
* Changed both `human` and `plain` formatters to elide the incorrect information.
Tested
-----
* Updated the tests to represent the new output.
Notes / Questions
-----
* The `expected` output from the tests …
> Remove erroneous information from 'volta list' output

- src/command/list/mod.rs
Closes #770 
Closes #496 
Info
-----
* StructOpt / Clap seem to generate invalid completions files for zsh when there is a `:` in the description for a command or flag.
* This results in very weird behavior when pressing Tab while using the auto-generated completions.
Changes
-----
* Removed the `:` from the `volta list` description, replacing it with a `-`
Tested
-----
* Confirmed locally that completions no longer error.
> [Tiny] Update command doc comments to avoid completions bug

- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/node/metadata.rs
- crates/volta-core/src/tool/node/mod.rs
- crates/volta-core/src/tool/node/resolve.rs
- crates/volta-core/src/tool/npm/fetch.rs
- crates/volta-core/src/tool/npm/resolve.rs
- crates/volta-core/src/tool/package/install.rs
- crates/volta-core/src/tool/package/metadata.rs
- crates/volta-core/src/tool/package/mod.rs
- crates/volta-core/src/tool/package/resolve.rs
- crates/volta-core/src/tool/registry.rs
- crates/volta-core/src/tool/yarn/metadata.rs
- crates/volta-core/src/tool/yarn/mod.rs
- crates/volta-core/src/tool/yarn/resolve.rs
Info
-----
* Metadata parsing for the various tool resolution / installation processes was spread in anunintuitive way.
* The main structs were defined in the `resolve` submodule for each tool, but then the deserialization of those structs was defined in `serial` that was a sibling of `resolve`.
* Also, the metadata defined in `package` around the npm Registry format was used in multiple places outside of Package, so it doesn't make sense to have it exclusively confined to `package` any more.
Changes
-----
* Renamed module `serial` to `metadata` for each tool.
* Moved the definition of the deserialized structs into the `metadata` method, so that it sits along side the deserializiation.
* Added a `tool::registry` module to hold all of the structs related to the npm Registry.
* Moved …
> [Medium] Restructure Tool Metadata

- crates/volta-core/src/tool/npm/fetch.rs
Closes #776 
Info
-----
* The windows-specific overwriting of the npm `cmd` launcher is writing the wrong file. It's writing `npm` and `npx` instead of `npm.cmd` and `npx.cmd`
* This causes `npm.cmd` to not be correctly updated and to look in the wrong location for the actual JS script
Changes
-----
* Updated `overwrite_cmd_launcher` to make sure it is writing the `*.cmd` files.
Tested
-----
* Confirmed that custom npm versions run correctly on Windows.
> Fix writing of npm launch scripts on Windows

- crates/volta-core/src/error/kind.rs
- crates/volta-core/src/toolchain/mod.rs
- tests/acceptance/corrupted_download.rs
- tests/acceptance/volta_install.rs
Closes #575 
Info
-----
Currently, calling `volta pin yarn` or `volta pin npm` when Node isn't yet pinned will (correctly) show an error. However, the same is not true for `volta install npm` or `volta install yarn`. Instead, `volta install npm` without a Node version set will report success, however then trying to call `npm` immediately after will fail.
Even worse, if you follow the instructions and subsequently install Node, the fact that you had installed a version of `npm` or `yarn` is lost and we tell you to install them again.
Changes
-----
Updated `Toolchain::set_active_npm` and `Toolchain::set_active_yarn` to show an error if the platform isn't set (i.e. there is no Node version selected), exactly as `Project::pin_npm` and `Project::pin_yarn` do in the same situation.
Tested
----- …
> [Small] Error when installing a package manager before Node

- Cargo.lock
- crates/volta-core/Cargo.toml
- crates/volta-core/src/fs.rs
- crates/volta-core/src/tool/node/fetch.rs
- crates/volta-core/src/tool/npm/fetch.rs
- crates/volta-core/src/tool/package/fetch.rs
- crates/volta-core/src/tool/yarn/fetch.rs
- crates/volta-migrate/src/v2.rs
Closes #781 
Info
-----
* When installing a new tool version, we first unpack the tool into a temporary directory and then `rename` it to the proper location within the Volta directory.
* Unfortunately, on systems with Virus scanners, that `rename` can sometimes fail because the directory is in-use as the scanner reads it.
* A similar issue was fixed in Rustup here: https://github.com/rust-lang/rustup/pull/1873
Changes
-----
* Added the `retry` crate and helper method to retry `rename` if the problem is permissions (indicating one of the files is in use).
* Used the same Fibonacci backoff and ~28 second max duration as Rustup (we may want to monitor that and determine how often it's needed and how much time is actually needed).
* Updated all uses of `std::fs::rename` to use the helper …
> [Small] Retry 'rename' operations to avoid race condition with virus scanners

- crates/volta-core/src/fs.rs
- crates/volta-core/src/shim.rs
- crates/volta-core/src/tool/package/fetch.rs
- crates/volta-core/src/tool/package/mod.rs
- crates/volta-migrate/src/v2.rs
Closes #786 
Info
-----
* When running `volta uninstall`, we were deleting the config file with the assumption that it was there.
* If it wasn't, that would cause an error and abort the entire uninstall process.
* Since the goal of uninstall is to remove the file, if it isn't there, we should treat that as success.
Changes
-----
* Added `remove_file_if_exists` helper to `fs` module.
* Renamed `ensure_dir_does_not_exist` to `remove_dir_if_exists` for consistency.
* Updated calls to use the helper methods
Note
-----
Both methods attempt to delete the appropriate item and handle the `ErrorKind::NotFound` error type as a success. This avoids potential race conditions that could pop up when doing a separate check for if the item exists.
> [Small] Treat files / dirs not existing as a successful remove

- crates/volta-core/src/tool/package/install.rs
> use lts when engines.node fails parsing

- crates/volta-core/src/version/serial.rs
Info
-----
Our current `parse_requirements` function is appending an `=` to any requirement that starts with a digit. This causes hyphen ranges (e.g. `8.11 - 8.17`) to be turned into invalid requirements (`=8.11 - 8.17`), which in turn causes the parse to fail. It appears that `VersionReq::parse_compat` already correctly parses `1` as `=1`, and so on, so adding the additional `=` character is redundant for those cases.
@mikrostew Do you have more context on why we were adding the `=` character? Is there a common case that is missed by excluding that character?
Changes
-----
* Updated `parse_requirements` to avoid prepending the `=` character, but still strip off a leading `v`
Tested
-----
* Added a unit test for hyphen ranges, which now passes.
* All the existing tests pass without …
> [Tiny] Update version requirement parsing to support hyphen ranges

- Cargo.lock
- crates/volta-core/Cargo.toml
- crates/volta-core/src/lib.rs
- crates/volta-core/src/sync.rs
- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/node/mod.rs
- crates/volta-core/src/tool/npm/mod.rs
- crates/volta-core/src/tool/package/fetch.rs
- crates/volta-core/src/tool/package/mod.rs
- crates/volta-core/src/tool/yarn/mod.rs
- crates/volta-migrate/src/lib.rs
- tests/smoke/volta_install.rs
Closes #612 
Info
-----
* As described in #612, we currently have issues when multiple Volta processes try to mutate the VOLTA_HOME directory simultaneously.
* The most common case we've seen so far for this is when two processes try to download the same version of Node / Yarn at the same time (e.g. in an automated, parallel test).
* This PR alleviates those issues, based on the idea of double-checked locking:
* First, we check if we need to download the tool.
* If we do, then we acquire an exclusive file lock to a specific file in the Volta directory.
* Once the lock is acquired, other processes may have already downloaded the tool we are looking at, so we check _again_.
* If we detect that we _still_ need to download the tool / version, then because we have the lock, we can be confident …
> [Medium] Prevent concurrent writes to VOLTA_HOME

- crates/volta-core/src/error/kind.rs
- crates/volta-core/src/shim.rs
- crates/volta-core/src/sync.rs
- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/node/mod.rs
- crates/volta-core/src/tool/npm/mod.rs
- crates/volta-core/src/tool/package/mod.rs
- crates/volta-core/src/tool/yarn/mod.rs
- crates/volta-migrate/src/lib.rs
Info
-----
* With the implementation of #684, we are locking the Volta directory while fetching new versions of tools.
* However, we are _not_ maintaining the lock while performing additional actions (such as writing the default platform file or installing package dependencies).
* We want to make sure that the lock is maintained throughout the `volta install` process, while also ensuring that we don't get deadlocks from the `ensure_fetched` lock (which is needed because it can be called separately by the shims).
* Ultimately, the goal of `VoltaLock` is to be a _per-process_ lock, where we prevent other Volta processes from modifying the Volta directory, but allow the current one to make changes.
Changes
-----
* Refactored the `VoltaLock` type to keep a count of active locks and only …
> [Medium] Extend Locks through entire install process

- Cargo.toml
- crates/volta-core/Cargo.toml
- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/package_global/mod.rs
- crates/volta-layout/Cargo.toml
- crates/volta-migrate/Cargo.toml
Info
-----
* The implementation of the package install rework (see https://github.com/volta-cli/rfcs/pull/45) will be a significant revamp of the install code paths.
* To ensure that PRs don't become so large that they are difficult to review, we want to break the work up into smaller chunks.
* Adding a feature flag allows us to implement these changes without disrupting the working Volta on `main`
Changes
-----
* Added a feature flag `package-global` to all of the relevant crates.
* Updated the logic in the `tool` module to import the `Package` object from a new module when the feature flag is turned on (this module will be where most of the work goes).
Notes
-----
* For the initial work, the CI runs do not run tests using the feature flag.
* Once the core implementation is complete, …
> [package-global] Add feature flag for installing packages with global installs

- crates/volta-core/src/error/kind.rs
- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/package/install.rs
- crates/volta-core/src/tool/package_global/install.rs
- crates/volta-core/src/tool/package_global/mod.rs
Info
-----
* First step of the package rework: Install packages using `npm install --global` with a redirect into a Volta-managed directory.
* Install into a temporary directory first, to avoid creating unnecessary directories in the event of an error.
* This PR explicitly doesn't include parsing the `package.json` or writing configs & shims, those will be added in a future PR.
Changes
-----
* Added new error messages for new error paths.
* Created `global_install` method to actually run the install command.
* Created skeleton implementation of `Tool::install` for `Package`
* Included `TODO` comments for areas that will be added in future PRs.
Tested
-----
All tested locally as automated tests will be added in a future PR, when the entire workflow is complete
* Confirmed packages are …
> [Medium] Reimplement 'volta install' using global package install

- Cargo.lock
- crates/archive/Cargo.toml
- crates/archive/src/lib.rs
- crates/archive/src/tarball.rs
- crates/archive/src/zip.rs
- crates/volta-core/Cargo.toml
- crates/volta-core/src/tool/node/resolve.rs
- crates/volta-core/src/tool/npm/resolve.rs
- crates/volta-core/src/tool/package/resolve.rs
- crates/volta-core/src/tool/yarn/resolve.rs
This PR changes the http library from `attohttpc` to `reqwest` for proxy support to resolve #798. 
The [reqwest library supports proxies](https://docs.rs/reqwest/0.10.8/reqwest/#proxies) by default and can be set using environment variables. Ex:
```bash
export https_proxy=http://proxy.giantcorp.com:8080/
volta install npm@latest
```
> Switch to reqwest for proxy support

- .github/workflows/api-docs.yml
- crates/volta-core/src/lib.rs
Info
-----
* Building the docs currently fails on nightly due to some incomprehensible `serde` errors.
* The only reason we need to use nightly is that we have a feature declared in `volta_core`: `#[feature(doc_cfg)]`, which claims to help support cross-platform docs.
* However, we don't seem to be taking advantage of that feature within the API docs anywhere.
Changes
-----
* Removed the `#[feature]` attribute that we weren't using anyway.
* Updated the CI configuration to build the API docs on stable Rust.
Tested
-----
* Ran `cargo doc` on stable to ensure that it completes correctly.
> Remove use of #[feature] and build docs on stable

- crates/volta-core/src/error/kind.rs
- crates/volta-core/src/tool/package_global/configure.rs
- crates/volta-core/src/tool/package_global/install.rs
- crates/volta-core/src/tool/package_global/metadata.rs
- crates/volta-core/src/tool/package_global/mod.rs
Info
-----
* Part 2 of package install rework: Complete the `volta install <package>` flow.
* Parse `package.json` to determine the exact version and any bins that are installed by the package
* Write the package config, bin configs, and shims
Changes
-----
* Added `metadata` module with the various metadata files that are used. Each is similar to an existing `metadata` with the old flow, but implemented differently to fit the new workflow.
* Added `configure` module with methods for parsing the manifest and writing the configs and shims
* Restructured the data flow in the `Package::install` method to ensure all of the appropriate data is available and can be used. This was also done somewhat looking forward to enabling `npm i -g` to reuse much of the code.
Notes
-----
* This only …
> [Medium] Generate config files and shims during package install

- crates/volta-core/src/run/binary.rs
- crates/volta-core/src/tool/package_global/mod.rs
Info
-----
* Part 3 of package install rework.
* With the changes to the directory structure and config format for global packages, the shim code path for actually running a global executable needs to be updated.
Changes
-----
* Updated `run::binary` to load binary information from the new configuration format when the feature flag is enabled.
* Changed calculation of the path to the binary to use the new directory structure for packages.
Tested
-----
* Manually tested on both Windows and Mac that executing a global package works correctly after installing it with `volta install`.
> [Small] Rework Shim code path to work with global packages

- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/package_global/mod.rs
- crates/volta-core/src/tool/package_global/uninstall.rs
Info
-----
* Part 4 of package rework: Implementing uninstall
Changes
-----
* Created `uninstall` module within the feature-flagged `package_global` module.
* Added implementation of uninstall behavior.
Tested
-----
* Manual testing to confirm that uninstalling a package works in both the usual case and the "orphaned packages" case.
Notes
-----
* The implementation of uninstall is nearly identical to that in the existing `package` module (pre-rework).
* The main difference is that the new package directory is removed, instead of the old `package_image_root_dir`
* Additionally, the new config file format is used for loading the `PackageConfig`.
> [Small] Implement Uninstall for new package workflow

- crates/volta-core/src/run/binary.rs
- crates/volta-core/src/run/mod.rs
- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/package_global/metadata.rs
Info
-----
* Part 5 of package rework: Completely remove `tool::package` module when the feature flag is active
* Previously, to simplify implementation, both the `package` and `package_global` modules were available when the feature flag was enabled.
* Now that work has progressed far enough, we can completely replace the `package` module with the feature flag.
Changes
-----
* Updated the module definition to load `package_global/mod.rs` _as_ the module `package` when the feature flag is enabled.
* Added some more feature flags to prevent warnings with now-unused methods on `ToolCommand`
* Cleaned up some imports that were referencing `package_global` as a separate module.
Tested
-----
* Confirmed that Volta builds without errors / warnings both with and without the feature flag.
> [Tiny] Complete removal of 'package' module under feature flag

- crates/volta-core/src/hook/mod.rs
- crates/volta-core/src/hook/serial.rs
Info
-----
* Part 6 of package rework: Remove the unused `Package` hooks under the new workflow
* Since we are now delegating to `npm install --global` to handle package installs, we no longer want to have a hybrid Hooks & `.npmrc` method for redirecting the download.
* Even before the change, Package hooks were soft-deprecated and didn't fully work as expected
* With the new workflow, we can cleanly remove them and rely only on the `.npmrc` files used by the package manager.
Changes
-----
* Marked the `Package` hook kinds as only available without the feature flag enabled.
Tested
-----
* Confirmed that Volta compiles without warnings or errors both with and without the feature flag.
> [Tiny] Remove Package Hooks under new install workflow

- crates/volta-core/src/inventory.rs
- crates/volta-core/src/layout/mod.rs
- crates/volta-core/src/run/binary.rs
- crates/volta-core/src/tool/package_global/mod.rs
- crates/volta-core/src/tool/package_global/uninstall.rs
- crates/volta-layout/src/lib.rs
- crates/volta-layout/src/v3.rs
- tests/acceptance/support/sandbox.rs
Info
-----
* Part 8 of package rework: Create a new layout version to represent the new package installation process.
* This new layout is a small change from the previous (`package_image_dir` no longer uses `version`), however it also will serve as a marker for migrating existing package installations.
Changes
-----
* Added `v3` layout in `volta_layout`
* Updated `layout` module in `volta_core` to use `v3` layout when the feature flag is active.
* Removed `new_package_image_dir` function and switched to calling `package_image_dir` on the `VoltaHome` instance.
* Removed `inventory::package_available` method when the feature flag is on, since it isn't used any more.
Notes
-----
* This change only includes the updated `layout`, but does _not_ include a migration for that layout yet. The …
> [Medium] Add new layout version for new package installation workflow

- Cargo.lock
- crates/volta-core/src/tool/package_global/install.rs
- crates/volta-layout/src/v3.rs
- crates/volta-migrate/Cargo.toml
- crates/volta-migrate/src/lib.rs
- crates/volta-migrate/src/v2.rs
- crates/volta-migrate/src/v3.rs
- crates/volta-migrate/src/v3/config.rs
- tests/acceptance/migrations.rs
- tests/smoke/main.rs
- tests/smoke/package_migration.rs
- tests/smoke/support/temp_project.rs
Info
-----
* Part 9 of package rework: Create migration for existing packages
* With the change to revamp to how packages are installed, we need to make sure to migrate anyone who has packages installed with the old logic.
* We achieve this by building a list of installed packages and re-installing them using the new logic
* The package install process overwrites the configuration files and the package image directory, so the old package will be completely replaced.
* By reading the old package configuration file, we can make sure to keep the pinned platform associated with an already-installed package.
Changes
-----
* Created migration to `v3` layout.
* Apart from changing the layout file, this migration updates the packages by loading the legacy package configs and re-installing each …
> [Medium] Implement Package Migration

- crates/volta-core/src/tool/package_global/configure.rs
- crates/volta-core/src/tool/package_global/install.rs
- crates/volta-core/src/tool/package_global/mod.rs
- crates/volta-migrate/src/v3.rs
Info
-----
* The next phase of the package rework involves supporting direct global installs (e.g. `npm install --global typescript`) to work within Volta.
* To do this, we will need to support a similar, but not identical interface for the install steps.
* To allow for reuse across different interfaces, refactor the various supporting methods into bare functions, which avoids them being tied to one specific struct (`Package`).
Changes
-----
* Update the `configure` and `install` modules in `package_global` to use bare functions that accept what they need as parameters.
* Similarly, updated the `persist_install` method to be a bare function.
* Added `run_install` to the `impl Package` block directly, so the entire public interface is in one place.
Tested
-----
* There should be no …
> [Medium] Refactor install logic to use bare functions

- crates/volta-core/src/run/binary.rs
- crates/volta-core/src/tool/package_global/configure.rs
- crates/volta-core/src/tool/package_global/install.rs
- crates/volta-core/src/tool/package_global/manager.rs
- crates/volta-core/src/tool/package_global/metadata.rs
- crates/volta-core/src/tool/package_global/mod.rs
- tests/acceptance/volta_uninstall.rs
Info
-----
* In order to support direct global installs, we need to track the idiosyncrasies of the different package manager installs.
* This requires us to keep track of which package manager actually performed the install of a package.
Changes
-----
* Added a `PackageManager` enum to the `tool::package` module. This type has associated functions to determine the bin and source locations for a package and to set up a command to install into the appropriate directory.
* Updated all of the existing install logic to use the `PackageManager::Npm` type, since it uses `npm install --global` internally.
* Included the package manager in the package and bin config files, so they can be used on lookup if needed.
* Updated the binary execution to take advantage of the stored package manager and …
> [Small] Add PackageManger type to install logic

- crates/volta-core/src/error/mod.rs
- crates/volta-core/src/fs.rs
- crates/volta-core/src/project/mod.rs
- crates/volta-core/src/run/binary.rs
- crates/volta-core/src/tool/package/install.rs
- crates/volta-core/src/tool/package/metadata.rs
- crates/volta-core/src/tool/package/mod.rs
- crates/volta-core/src/tool/package_global/metadata.rs
- crates/volta-core/src/tool/package_global/uninstall.rs
- crates/volta-migrate/src/v1.rs
- crates/volta-migrate/src/v2.rs
@charlespierce I am ok with any kind of comments. I would like to know if this is the correct direction you want to take in regards to [issue 823](https://github.com/volta-cli/volta/issues/823).
I have changed only the places that do an `open` operation on FS, and left alone other operations on FS like `rename` or `delete`
There may be some missing places that I could not find
> Handle ErrorKind NotFound instead of file.exists()

- crates/volta-core/src/lib.rs
- crates/volta-core/src/platform/mod.rs
- crates/volta-core/src/run/binary.rs
- crates/volta-core/src/run/mod.rs
- crates/volta-core/src/run_package_global/binary.rs
- crates/volta-core/src/run_package_global/executor.rs
- crates/volta-core/src/run_package_global/mod.rs
- crates/volta-core/src/run_package_global/node.rs
- crates/volta-core/src/run_package_global/npm.rs
- crates/volta-core/src/run_package_global/npx.rs
- crates/volta-core/src/run_package_global/yarn.rs
- tests/acceptance/main.rs
- tests/acceptance/merged_platform.rs
- tests/acceptance/support/sandbox.rs
- tests/acceptance/volta_run.rs
Info
-----
* Looking forward to allowing `npm i -g <package>` to work seamlessly within Volta, we need to ensure that the `run` module can handle more extensibility.
* Since there will be more possible branches (`npm i -g` will need to include extra behavior both before and after running a command), we will want to allow a command to be built up more piecemeal than is currently supported.
* We also want to leave things in a state that they can be easily extended to new use-cases (i.e. `npm i -g yarn` should delegate to the `volta install yarn` behavior, instead of treating it like any other package).
Changes
-----
* Added new `run_package_global` directory, used as the `run` module when the feature flag is enabled.
* Removed all the feature flag attributes from `run`, as it is now only …
> [Large] Refactor 'run' module to allow for better extensibility

- crates/volta-core/src/lib.rs
- crates/volta-core/src/platform/mod.rs
- crates/volta-core/src/run/binary.rs
- crates/volta-core/src/run/mod.rs
- crates/volta-core/src/run_package_global/binary.rs
- crates/volta-core/src/run_package_global/executor.rs
- crates/volta-core/src/run_package_global/mod.rs
- crates/volta-core/src/run_package_global/node.rs
- crates/volta-core/src/run_package_global/npm.rs
- crates/volta-core/src/run_package_global/npx.rs
- crates/volta-core/src/run_package_global/yarn.rs
- crates/volta-core/src/tool/package_global/mod.rs
- tests/acceptance/main.rs
- tests/acceptance/merged_platform.rs
- tests/acceptance/support/sandbox.rs
- tests/acceptance/volta_run.rs
Info
-----
* First pass, naive enabling of `npm i -g <package>` to go through the `volta install` logic (using the package manager of choice) and install the package with Volta's stable platform guarantees and delegating shims.
* Completes the plumbing to make the happy path work, but doesn't handle edge cases at all.
Changes
-----
* Added `DirectInstall` type in `tool::package_global` that provides the interface necessary for modifying global installs to work with Volta's install process.
* Specifically it exposes the ability to set up a `command` with the appropriate environment variables and to complete an install, moving files out of the `tmp` directory and into the appropriate location in the Volta data directory.
* Created a `PackageInstallCommand` that builds a command for …
> [Medium] Initial implementation of direct global installs

- crates/volta-core/src/run_package_global/executor.rs
- crates/volta-core/src/run_package_global/mod.rs
- crates/volta-core/src/run_package_global/npm.rs
- crates/volta-core/src/run_package_global/yarn.rs
Info
-----
* Improves on the Naive package installation implementation in #829 to:
* Correctly parse and install versioned packages (e.g. `npm i -g typescript@3`)
* Special-case handling of internal installs—installs for packages that Volta handles internally separate from the package manager behavior (like Node, Yarn, etc.).
Changes
-----
* Added `InternalInstallCommand` executor that delegates to Volta's existing install behavior (and writes a note to the user that we are changing how the command is handled).
* Used the existing parsing of `tool::Spec` to handle parsing the package to install correctly.
Tested
-----
* Local testing to confirm that installs work with and without versions, and that the appropriate packages are intercepted by Volta's logic.
Notes
-----
* There aren't any …
> [Small] Correctly Parse package versions and support internal installs

- crates/volta-core/src/run_package_global/npm.rs
- crates/volta-core/src/run_package_global/yarn.rs
- tests/acceptance/direct_install.rs
- tests/acceptance/main.rs
- tests/acceptance/support/sandbox.rs
- tests/smoke/direct_install.rs
- tests/smoke/main.rs
Info
-----
* Now that the new flows work end-to-end in specific cases, we should have tests that verify the functionality.
Changes
-----
* Added smoke tests to confirm that installing packages directly with `npm i -g` and `yarn global add` works as expected.
* Added acceptance tests to confirm the correct interception of internal tool installs.
* Added unit tests to cover the argument parsing logic.
Notes
-----
* This PR builds on #831 so it will remain a draft until that is merged. To view only the changes from this PR, use [this link](https://github.com/volta-cli/volta/pull/832/files/5c8402e6889841d37fa3d466653882de155f2f06..12007c4477725102100d592f9ce0fc88cbf5df59)
> [Small] Add tests for new direct package install flows

- crates/volta-core/src/run_package_global/executor.rs
- crates/volta-core/src/run_package_global/mod.rs
- crates/volta-core/src/run_package_global/npm.rs
- crates/volta-core/src/run_package_global/yarn.rs
- crates/volta-core/src/tool/mod.rs
- tests/acceptance/direct_uninstall.rs
- tests/acceptance/main.rs
Info
-----
* Since we now support installing globals directly with `npm i -g <package>`, we should also support removing them with `npm uninstall -g <package>`
* This should always delegate to the internal Volta logic, so we can be sure that the shims and config files are correctly cleaned up.
Changes
-----
* Added a new `Executor` for uninstall commands, which calls out to the `tool::Spec::uninstall` method.
* Updated the parsing of npm and Yarn commands to check for global uninstalls and use the new Executor.
Tested
-----
* Added new tests to the parsing logic to confirm `uninstall` / `remove` are handled correctly.
* Added new acceptance tests to confirm that running `npm uninstall -g` or `yarn global remove` correctly uninstall all of the Volta extras.
Notes
-----
* As with the global …
> [Small] Implement direct global uninstalls

- crates/volta-core/src/run_package_global/mod.rs
- crates/volta-core/src/run_package_global/parser.rs
- tests/acceptance/direct_install.rs
Info
-----
* Previously, we used the (undocumented) environment variable `VOLTA_UNSAFE_GLOBAL` to disable the global install interception.
* While our new logic allows global installs, it still makes modifications to the process, so we should keep the escape valve to run the bare command.
Changes
-----
* Updated the `CommandArg::for_npm` and `CommandArg::for_yarn` to short-circuit to `NotGlobal` (No interception) if the `VOLTA_UNSAFE_GLOBAL` environment variable is set.
Tested
-----
* Added acceptance tests to confirm that global installs are not modified when the environment variable is set.
> [Small] Add VOLTA_UNSAFE_GLOBAL env variable to new package install

- crates/volta-core/src/error/kind.rs
- crates/volta-core/src/event.rs
Info
-----
* With the `package-global` changes making significant changes to the package install flow, several errors are no longer being used.
* Additionally, there were some `ErrorKind` variants left around that weren't being used at all (even before the changes).
Changes
-----
* Marked all errors that are not used with the feature flag as `#[cfg(not(feature = "package-global"))]` so they won't be included.
* Removed several errors that weren't in use anywhere in the app.
Tested
-----
* Confirmed that Volta compiles and the tests pass both with and without the feature flag.
> [Small] Remove errors that aren't being used

- crates/volta-core/src/run_package_global/executor.rs
- crates/volta-core/src/tool/package_global/mod.rs
Info
-----
* When installing a package with `npm i -g` or `yarn global add`, we are still modifying the Volta directory, so we still should have a lock on the process.
Changes
-----
* Added a call to `VoltaLock::acquire()` in the `execute` method of the `PackageInstallCommand` executor.
* Removed an erroneous `?` on the call to `VoltaLock::acquire()` in the `Package` implementation of `Tool`
> [Tiny] Ensure a VoltaLock is acquired when installing packages directly

- crates/volta-core/src/error/kind.rs
- crates/volta-core/src/fs.rs
- crates/volta-core/src/run_package_global/binary.rs
- crates/volta-core/src/run_package_global/executor.rs
- crates/volta-core/src/tool/package_global/mod.rs
- crates/volta-core/src/tool/package_global/uninstall.rs
- crates/volta-layout/src/v3.rs
Info
-----
* As described in [the RFC](https://github.com/volta-cli/rfcs/pull/45), we want to provide a way for global packages to "see" other global packages when running a `require` statement, to match up with the standard global install behavior.
* To do this, we create a shared directory with symlinks to each of the global packages and add it to the `NODE_PATH` environment variable when executing a global binary.
Changes
-----
* Added the `shared_lib_root` and `shared_lib_dir` to the V3 layout (no change to the migration is necessary as the directory is already created by the `create()` method).
* Updated the global install process (for both `volta install` and `npm i -g`) to create a symlink from the package directory into the `shared_lib_root`
* Updated the global uninstall process …
> [Medium] Allow global binaries to access global libraries

- crates/volta-core/src/platform/image.rs
- crates/volta-core/src/platform/tests.rs
- crates/volta-core/src/run_package_global/executor.rs
- crates/volta-core/src/run_package_global/mod.rs
- crates/volta-core/src/run_package_global/node.rs
- crates/volta-core/src/run_package_global/npm.rs
- crates/volta-core/src/run_package_global/npx.rs
- crates/volta-core/src/run_package_global/yarn.rs
Info
-----
* In a non-Volta environment, global bins are put on the PATH and can freely call one another.
* Volta should allow that behavior as well, since there are cases where it is needed (multiple related bins delivered as a single package, for example).
* To do that, we need to leave the shim directory on the PATH when executing a command.
* However, since the Volta shims for global packages are located in the same directory as the shims for node, npm, yarn, etc., we need to make sure that a bad state doesn't cause an infinite recursion.
* The built-in shims (Node, npm, npx, and Yarn) each call their command by putting the appropriate directory on the PATH and then calling the bare command.
* This is in contrast to the binary shims, which call their command directly with the path to …
> [Small] Leave shim directory on PATH to allow bins to call other bins

- Cargo.lock
- crates/archive/Cargo.toml
- crates/archive/src/lib.rs
- crates/archive/src/tarball.rs
- crates/archive/src/zip.rs
- crates/volta-core/Cargo.toml
- crates/volta-core/src/tool/node/resolve.rs
- crates/volta-core/src/tool/npm/resolve.rs
- crates/volta-core/src/tool/yarn/resolve.rs
Info
-----
* In #809, we switched to `reqwest` for handling HTTP requests to support proxies via `HTTP_PROXY` and `HTTPS_PROXY` environment variables.
* However, that change came with an increase in build time and binary size, since `reqwest` is a much larger library than `attohttpc`.
* Additionally, `reqwest` currently doesn't support the `NO_PROXY` environment variable for carving out exceptions to the proxy environment.
* `attohttpc` recently (with version `0.16.0`) added support for proxies, including the `NO_PROXY` environment variable.
Changes
-----
* Switched back to using `attohttpc`, but requiring version 0.16.0.
* This is mostly a revert of #809, accounting for merge conflicts.
Tested
-----
* All existing automated tests work.
* Local testing to confirm that proxy environment …
> Move back to attohttpc, now that it supports proxies

- .github/workflows/release.yml
As discussed in #803, though we aren't yet at 1.0, Volta is production-ready (and we're using it at scale within LinkedIn). We have been committed to stability and backwards-compatibility for some time, so it is reasonable to no longer use the "Pre-release" flag on GitHub releases.
This also unlocks updates to the Volta formula in Homebrew, which requires that packages not be pre-release to be included in the public repo.
Updating the CI script that creates the draft release to _not_ set the pre-release flag.
> Remove pre-release flag from auto-generated releases

- crates/volta-core/src/tool/package/mod.rs
Closes #857 
Info
-----
* There is an upstream bug in `npm@7` where global installs into a custom prefix will fail if the expected `lib` subdirectory doesn't already exist (https://github.com/npm/cli/issues/2012)
* While this will likely get fixed, we can also work around it internally in Volta by ensuring the expected `lib` and `bin` directories are created before running an install.
Changes
-----
* Updated the creation of the staging directory to ensure that the appropriate `lib` and `bin` directories are also created.
Tested
-----
* Confirmed that installing packages under npm 7 works as expected.
> Ensure prefix subdirectories are created when installing

- crates/volta-core/src/layout/mod.rs
Info
-----
Since Volta 0.9.0, there have been a few reports of `volta_migrate` failing to launch even though the binary is available, both from managed corporate environments and from `brew` installs. It turns out our logic for finding the install directory (which we then use to locate the `volta_migrate` executable) had a very subtle defect: It was stripping off the file to locate the directory _before_ canonicalizing the path. This meant that if the executable _itself_ was a symlink, but the parent directory wasn't, that we wouldn't correctly resolve location of the _actual_ binaries. For example:
* Volta is installed in `/home/user/volta/bin/{volta,volta-shim,volta-migrate}`
* `/home/user/links/volta` is a symlink to `/home/user/volta/bin/volta`, but the other two binaries aren't …
> [Tiny] Correctly locate install_dir

- crates/validate-npm-package-name/src/lib.rs
- crates/volta-core/src/tool/serial.rs
- src/command/list/mod.rs
Info
-----
Clippy now gives warnings about match expressions that could be better written using the [`matches!`](https://doc.rust-lang.org/std/macro.matches.html) macro.
Changes
-----
Updated each expression to use `matches!` instead of a hand-written match block.
Note
-----
The `matches!` macro was added in Rust 1.42, so we need to bump our MSRV. It's currently at 1.41, so it's not a huge bump. Created https://github.com/volta-cli/website/pull/86 to update the documentation to better reflect our workflow.
> Use the matches! macro instead of manual match blocks

- dev/unix/volta-install.sh
Closes #870 
Info
-----
* Though we don't have native builds for Apple Silicon machines yet, the existing MacOS builds should continue to work under Rosetta.
* However, the installer currently shows an early error when the architecture isn't x86_64
Changes
-----
* Updated the installer to allow Apple ARM machines to pass the `check_architecture` function, after which they will install the existing MacOS build.
Testing
-----
* I don't currently have access to an M1 machine, so I could use confirmation from someone who does (cc @stefanpenner). The updated installer is at https://raw.githubusercontent.com/charlespierce/volta/ec2ba8bc2cfb4fa60b1ce4e0069e44f7a783b7bd/dev/unix/volta-install.sh, so a test would be to run the following on a standard, non-Rosetta terminal:
```
curl …
```
> Allow installs of MacOS version on Apple ARM architecture

- dev/unix/volta-install.sh
As pointed out on Discord, the installer currently includes some output from `tar` that looks out of place:
```
x volta
x volta-shim
x volta-migrate
```
This is because `tar` is invoked with `-v` for verbose output. We actually don't need that output to be part of the install process, so removing that flag from the installer.
Note: Also removed `-z` which has no use when extracting a tarball.
> Remove 'tar' output from installer

- .github/workflows/test-pnpm.yml
With development happening behind the `pnpm` feature flag, we should make sure that all tests are run with the feature flag enabled as well, to confirm that any changes don't break that work.
> Run CI tests with pnpm feature active

- ci/docker/Dockerfile
Info
-----
* The Dockerfile used to build the Linux versions of Volta is no longer working.
* It appears that the CentOS 6 packages are no longer hosted on `mirror.centos.org` and so must instead be downloaded from `vault.centos.org`
Changes
-----
* Updated the Dockerfile to use a specific version of CentOS 6 (6.10, which is the same that it was using when the tag was just `6`)
* Added commands to modify the repo and point it to `vault.centos.org` instead of using a list of mirrors.
Tested
-----
* Confirmed locally that the docker image builds successfully
> Update Dockerfile to redirect yum to vault.centos.org

- crates/volta-core/src/tool/node/resolve.rs
- crates/volta-core/src/tool/package/mod.rs
- crates/volta-core/src/version/mod.rs
Info
-----
* The latest clippy is showing a few new warnings to clean up in the code
Changes
-----
* Updated code to conform to clippy's suggested style
Tested
-----
* All tests continue to pass
* Manually verified that the Node index cache still respects the `url` and that the `version_serde` deserializer still strips a single preceding `v` character.
> Clean up warnings from clippy

- crates/volta-core/src/monitor.rs
- Use `cfg!(debug_assertions)` to check if it's a dev build or release build.
- For dev build, pipe `stdout` and `stderr` of the `command` in `spawn_process`, so it's easier to debug.
- For release build, pipe `stdout` and `stderr` to "nowhere", so the spawn_process won't mess up with `stdout` of `volta` if there is any thing from `stdout` or `stderr`
> Only show stdout and stderr of spawned process in dev mode

- crates/volta-core/src/run/node.rs
- crates/volta-core/src/run/npm.rs
- crates/volta-core/src/run/npx.rs
- crates/volta-core/src/run/yarn.rs
Adding `ActivityKind::Node/Npm/Npx/Yarn` into the event list under `ActivityKind::Tool`
Example when run `node -v`:
```
[
{"timestamp":1607565565134,"name":"tool","event":"start"}, 
{"timestamp":1607565565134,"name":"node","event":"start"},
{"timestamp":1607565565147,"name":"tool","event":{"end":{"exit_code":0}}}
]
```
> Add detailed activity kind to event for node/yarn/npm/npx

- crates/volta-core/src/monitor.rs
There are two places in `monitor.rs`, we should use `debug!` instead of `error!`.
> use debug! instead of error! in monitor.rs

- crates/volta-core/src/run/parser.rs
- tests/acceptance/direct_install.rs
- tests/acceptance/direct_uninstall.rs
Info
-----
* Currently, if a user runs a global install or uninstall without any package arguments (e.g. `npm i -g` or `yarn global remove`), we show:
```
note: Volta is processing each package separately
```
* However, since there are no arguments, we then effectively no-op by iterating over an empty list.
* This leads to a confusing situation where there's no feedback about success or failure to the user (and the return code is 0, indicating success).
* Since, in these situations, there aren't any tools for Volta to handle, we should treat it like a non-global situation and allow the underlying package manager to show whatever error it normally would when the user forgets the arguments.
Changes
-----
* Updated the parser for both npm and Yarn to handle the case of no package arguments …
> [Small] Better handling for global commands without arguments

- crates/volta-core/src/error/kind.rs
- crates/volta-core/src/run/executor.rs
- crates/volta-core/src/run/npm.rs
- crates/volta-core/src/run/parser.rs
- crates/volta-core/src/run/yarn.rs
- crates/volta-core/src/tool/package/manager.rs
- crates/volta-core/src/tool/package/mod.rs
Info
-----
* One of the main outstanding features prior to 1.0 release: Support for `npm link`, both to link the current project as a global _and_ to pull a global in as a link into the current project.
* The bare command (`npm link`) works similarly to a global install, except that internally npm create a symlink instead of copying the files into the global directory.
* Notably, it _does_ hook up any bins of the current project as global binaries.
* The command with package arguments (`npm link my_package`) will install the global `my_package` into the current project as a symlink.
Changes
-----
* Updated the command interception parser to handle `npm link` both with and without additional arguments.
* In the case that there are _no_ additional arguments, we can re-use the …
> [Large] Add support for 'npm link'

- crates/volta-core/src/run/npm.rs
- crates/volta-core/src/run/parser.rs
- crates/volta-core/src/run/yarn.rs
Info
-----
* Follow-up to #888, adding support for the bare `npm unlink` command, which removes the current project from the global links.
* Only when executed with no arguments does `npm unlink` behave like this, all other times it is effectively an alias of `npm uninstall`.
Changes
-----
* Updated the parser to handle `npm unlink` with no package arguments and attempt to uninstall the current project.
* If there is no current project or it can't be determined, this will delegate to the normal `npm` behavior to show any errors.
* However, if we know the project, then this will use Volta's internal logic to handle the uninstall, making sure everything is cleaned up correctly.
* Also removed the `InterceptedCommand` logic from `run/yarn.rs`, since as noted in #888, `yarn link` and `yarn …
> [Medium] Add support for 'npm unlink' 

- tests/smoke/main.rs
- tests/smoke/npm_link.rs
- tests/smoke/support/temp_project.rs
Info
-----
* With `npm link` and `npm unlink` set up to work correctly, we want to make sure that behavior is covered by our test suite.
* Since the actual results depend on running `npm`, we need to use the smoke tests.
Changes
-----
* Added test for linking / unlinking the local project into a global, confirming that Volta correctly picks up the changes and makes them available.
* Added test for linking a globally installed package into the local project, confirming that Volta sets the environment up for the link to work correctly.
Notes
-----
* This PR builds on #889 and so will remain a draft until that is merged. To see only the changes from this PR, use [this link](https://github.com/volta-cli/volta/pull/891/commits/2b3279ffeed66d75c21f74ed7b04e47fcc9e6c5e)
> [Small] Add smoke tests for `npm link` interception & behavior.

- .github/workflows/release.yml
- crates/volta-core/src/error/kind.rs
- crates/volta-core/src/run/executor.rs
- crates/volta-core/src/run/parser.rs
- crates/volta-core/src/tool/package/mod.rs
- tests/smoke/direct_upgrade.rs
- tests/smoke/main.rs
Closes #850
Info
-----
* The last piece of global install interception is allowing users to upgrade their versions using the built-in commands from the package manager: `npm update --global` and `yarn global upgrade`.
* Due to Volta's package sandboxing, we need to intercept this command and set things up so that the package managers can correctly locate the packages to upgrade.
* Since the directory layout is different between the package managers, we also need to make sure that we only upgrade packages installed by the package manager being invoked.
* Finally, running `npm update -g` or `yarn global upgrade` without any package arguments attempts to upgrade _all_ installed global packages, so we need to provide support for that behavior.
Changes
-----
* Added interception for the global …
> [Large] Implement global upgrade interception

- .github/workflows/release.yml
Info
-----
* As part of the run-up to the 1.0 release, we want to digitally sign the Windows installer so that it can gain reputation and eventually prevent the SmartScreen errors.
* Since the build artifacts are created during CI runs, we need the signature to happen there too.
Changes
-----
* Added the certificate and password to the repo's secrets.
* Updated CI to fetch the certificate and sign the `.msi` installer file during a release build (this has to be triggered by pushing a tag, it won't happen in PR builds, which don't have access to the secrets).
Tested
-----
* Confirmed that the built artifact is correctly signed.
Notes
-----
* Due to how Microsoft SmartScreen works, even though the installer is signed, it will require an unknown number of actual installs to establish …
> Sign Windows Installer after creation

- crates/volta-core/src/toolchain/mod.rs
- crates/volta-core/src/toolchain/serial.rs
- crates/volta-migrate/src/v2.rs
Replace `Platform::from_json` with `Platform::try_from`, implement `TryFrom<String>` trait.
This is an attempt at part of https://github.com/volta-cli/volta/issues/489.
I'm aware that this may not be what was intended in #489. I'm prepared to accept that feedback and close if that's the case 🙂 
One drawback is that `try_from` doesn't mention JSON, whereas `from_json` clearly expects a JSON string.
> Replace Platform::from_json with TryFrom trait implementation

- crates/volta-core/src/toolchain/mod.rs
- crates/volta-core/src/toolchain/serial.rs
Part of https://github.com/volta-cli/volta/issues/489
Replace into_platform with TryInto implementation. 
The first commit, 39e6d3a, includes a very simple change that implements `Into<Option<PlatformSpec>>`.
The second commit goes further and implements `TryInto<PlatformSpec>` that may result in a `VoltaError` of kind `ErrorKind::NoPlatform`. Implementing `TryInto` seems more idiomatic than implementing `into` to return an `Option`. I am very new to this codebase and a Rust novice, this may be going too far and the first commit may be sufficient.
> Replace Platform::into_platform with Into implementation

- crates/volta-core/src/manifest/serial.rs
- crates/volta-core/src/tool/node/metadata.rs
A new Rust version comes with a couple of new Clippy warnings to clean up 🎉
> Clean up new clippy warnings (1.49.0)

- crates/volta-core/src/tool/node/metadata.rs
- crates/volta-core/src/tool/node/mod.rs
- crates/volta-core/src/tool/node/resolve.rs
Closes #34 
Info
-----
* Now that Rust 1.49 is out and has stable [Tier 2 support for Apple M1 chips](https://blog.rust-lang.org/2020/12/31/Rust-1.49.0.html#64-bit-arm-macos-and-windows-reach-tier-2), we can create an M1 native build of Volta.
* Currently, Node doesn't provide pre-built binaries for M1 chips, so we still need to fetch the x64 version of Node and run it through Rosetta 2.
* At the same time, we should also confirm when resolving a Node version that it is available for the current OS & Architecture.
Changes
-----
* Updated the `NODE_DISTRO_*` constants to also include `NODE_DISTRO_IDENTIFIER`, representing the identifier used in the Node index `files` property.
* Currently this uses the `osx-x64-tar` identifier on M1 MacOS, since Node doesn't provide pre-built M1 binaries …
> [Small] Check Node OS & Arch availability and support M1 native builds

- .github/workflows/release.yml
- ci/build-for-arm.sh
Info
-----
* With #915, we can now create native M1 MacOS binaries.
* We should create them in CI so they are included in future releases.
Changes
-----
* Updated the CI scripts to build both Intel and ARM Mac builds (the latter being named `volta-{version}-macos-aarch64.tar.gz`
* Updated the release job to also include the native build in the release artifacts.
> [Small] Build Apple Silicon Native build in CI

- crates/volta-core/src/tool/node/resolve.rs
- crates/volta-core/src/version/mod.rs
Info
-----
* With the previous package installation logic, we relied on finding a Node version that matched `engines` to determine which Node version to use when installing a global package.
* To better match user expectations, we added an internal-only `LtsRequirement` tag, which represented finding the latest LTS version that matched a requirement (if possible), falling back to the latest version overall.
* Now that we match `npm i -g` more closely and use the current default Node version for global installs, that internal tag is no longer needed.
Changes
-----
* Removed the `LtsRequirement` variant from the `VersionTag` enum.
* Removed the `resolve_lts_semver` function which was used only with that variant.
> [Small] Remove now-unused 'LtsRequirement' tag

- dev/unix/volta-install.sh
Update the installer script to fetch the M1 Native build instead of the standard x64 build.
* DO NOT MERGE Until after version 1.0.1 has been released and https://volta.sh/latest-version updated
> [Tiny] Update installer to fetch native M1 Volta binary

- ci/build-for-arm.sh
- crates/volta-core/src/tool/node/metadata.rs
- crates/volta-core/src/tool/serial.rs
- crates/volta-migrate/src/lib.rs
- src/command/list/human.rs
With the release of Rust 1.50, there are a couple of new clippy warnings about functions that are being unnecessarily wrapped in `Result` or `Option`. In each case, it appears that the wrapping is necessary to match the expected API (or to support cross-platform behavior). Added `#[allow(clippy::unnecssary_wraps)]` to each of those with a note about why it's allowed.
Also, there's a small change to formatting with `rustfmt`, so since we build in CI using the latest Rust, we want to fix that.
Finally, @uasi noted in #938 that the ARM build is failing because it's using the wrong version of the Mac OS SDK, so fixed that as well.
> Fix clippy warnings, formatting, and M1 build

- crates/volta-migrate/src/lib.rs
- src/common.rs
- src/volta-migrate.rs
Addresses https://github.com/volta-cli/volta/issues/927
Shims are symbolic links to `/path/to/volta-shim`. If a package manager installs a new version of Volta to a different location and removes the current version, shims will be broken.
- Make `volta-migrate` regenerate shims even if the layout is up-to-date.
- Add `--no-create` option to `volta-migrate`. When specified, `volta-migrate` runs migration only if the Volta directory already exists.
> Make volta-migrate regenerate shims and add --no-create option to it

- crates/volta-core/src/run/mod.rs
Closes #939 
Info
-----
* Our logic for detecting the tool name on Windows was assuming that the command would always be called as e.g. `node` or `node.exe`, fully lowercase.
* On Windows, the file system is case-insensitive, so it's possible to call the tool as `NODE.EXE` or even `nOdE.eXe` or any capitalization.
* We should detect those situations and treat them appropriately.
Changes
-----
* Updated the Windows implementation of getting the tool name from the file name to convert the tool to lowercase before removing the `.exe` and trying to match the command name.
Tested
-----
* Confirmed that running `node.exe --version`,  `NODE.EXE --version`, and `nOdE.eXe --version` all work correctly.
Notes
-----
* The detection of binaries is based on locating the configuration on disk, so …
> [Tiny] Make tool name case-insensitive on Windows

- crates/volta-core/src/run/executor.rs
- crates/volta-core/src/run/npm.rs
- crates/volta-core/src/run/parser.rs
- crates/volta-core/src/tool/package/mod.rs
Closes #934 
Info
-----
* With npm 7, when we run `npm link` it uses a relative path to link the local directory to the global directory.
* Since we link into a temp directory and then `rename` to the final `tools/images` directory, we need to make sure that the temp directory has the same level of nesting as the final directory, so that relative symlinks work correctly.
* When linking a package that has a scope, the final directory includes an extra level of nesting, from `@scope/package`, so we need to account for that when creating the temp directory.
Changes
-----
* Updated the install executor and helper struct (`DirectInstall`) to support including the name if available.
* Updated `setup_staging_directory` to handle the case when an extra layer of nesting is required.
* Connected …
> [Medium] Add extra directory when linking scoped package

- crates/volta-core/src/platform/mod.rs
- tests/acceptance/merged_platform.rs
When node is pinned in a project, and `volta pin npm@bundled` is run, nothing is added to `package.json`, that is, `npm@bundled` is pinned by default. However, when actually running npm in a project like this, Volta didn't behave correctly, and used the global default npm.
It would be nice to write a test case for the fixed behavior, and I tried, but I don't understand correctly the Sandbox thing, or how I should go about doing it.
After fixing this, I noticed that the `volta list` output is wrong as well in this case, showing the default npm version instead of the bundled one. Could be fixed in a follow-up commit, will need some advice on how to do that.
Fixes #953
> Fix pinning of npm@bundled

- crates/volta-core/src/tool/package/metadata.rs
Closes #963 
Info
-----
* When the `bin` field in `package.json` is a string (as opposed to a hash), that's interpreted as the _path_ to the binary and the package name is used as the name of the binary.
* However, when the package is scoped (e.g. `@scope/package-name`), then the binary should be named after the package _without_ the scope (`package-name` in this example).
* Including the scope causes problems when creating shims, as the `/` is interpreted as a filesystem directory separator.
Changes
-----
* Updated the logic that handles string-valued `bin` to strip off any scope when setting the name of the binary.
Tested
-----
* Added unit tests to confirm that removing the scope works as expected
* Manual testing to confirm that a scoped package with a string bin can be installed …
> Remove package scope from default binary name

- crates/volta-core/src/tool/node/fetch.rs
- crates/volta-core/src/tool/node/metadata.rs
- crates/volta-core/src/tool/node/mod.rs
- tests/acceptance/corrupted_download.rs
- tests/acceptance/support/sandbox.rs
Closes #919 
Info
-----
* With the release of Node v16, there are now pre-built binaries available for Apple Silicon devices.
* Where possible, we should fetch and use those binaries, so that users get the best possible experience.
* However, for older versions of Node, we will need to continue to fetch the x64 binaries and rely on Rosetta.
Changes
-----
* Updated the constants section in `tool/node/mod.rs` to include the constant values for Apple Silicon architecture
* Ensured that the parsing of the `files` metadata in the Node index will check for both the native and x64 versions of Node.
* Customized `archive_filename` on Apple Silicon builds to check the Node major version and fetch either a native or x64 build of Node depending on whether it is greater than or equal to 16.
Tested …
> [Medium] Fetch Native Apple Silicon Node builds for Node 16+

- crates/volta-core/src/inventory.rs
Closes #980 
Info
-----
* Currently, the `inventory::package_configs` function reads all of the files in the package config directory and attempts to parse them as package configs.
* However, sometimes the OS will automatically generate hidden files in a directory (e.g. `.DS_Store` on macOS).
* Those auto-generated files will not be valid package configs, but they shouldn't cause `volta list` to fail, instead they should be ignored.
Changes
-----
* Updated the directory walk within `package_configs` to ignore both directories _and_ any file that doesn't have a `.json` extension.
Tested
-----
* Locally tested to confirm that adding an empty dotfile into the package config directory does _not_ cause `volta list` to fail.
> Ignore non-json files when listing all package configs

- Cargo.lock
- crates/volta-core/src/platform/tests.rs
- crates/volta-core/src/project/mod.rs
Info
-----
* As of the latest Rust release, Windows builds are failing to compile due to an issue with `proc-macro-hack`, which is a transitive dependency on Windows.
* The upstream `proc-macro-hack` released a new version `0.4.3` that resolves the compiler failure.
* Additionally, there are some warnings from Clippy on Windows that should be resolved.
Changes
-----
* Used `cargo update` to bump the version of `proc-macro-hack` in `Cargo.lock`
* Fixed the clippy warnings.
Tested
-----
* Compiles on a Windows machine completely.
* `cargo clippy` Shows no warnings.
> Fix Windows Builds and Clippy Warnings

- src/command/setup.rs
This will prevent changes when these settings are defined in a different, but compatible way to what volta does.
> Don't update the user's shell config files if VOLTA_HOME and PATH already contains what we need.

- Cargo.lock
Resolve #1055.
```sh
volta on  bump-clap is 📦 v1.0.5 via 🦀 v1.56.1
❯ ./target/debug/volta -h | false
volta on  bump-clap is 📦 v1.0.5 via 🦀 v1.56.1
❯
```
> Update to latest clap@2.x

- Cargo.lock
- crates/test-support/src/matchers.rs
- crates/volta-core/src/run/binary.rs
- crates/volta-core/src/session.rs
- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/node/fetch.rs
- crates/volta-core/src/tool/npm/fetch.rs
- crates/volta-core/src/tool/npm/resolve.rs
- crates/volta-core/src/tool/package/configure.rs
- crates/volta-core/src/tool/package/uninstall.rs
- crates/volta-core/src/tool/yarn/fetch.rs
- crates/volta-core/src/tool/yarn/resolve.rs
- crates/volta-core/src/toolchain/mod.rs
- src/command/list/human.rs
- src/command/list/mod.rs
- src/command/list/plain.rs
- src/command/list/toolchain.rs
Info
-----
* Bumping the Rust version came with some new clippy warnings about unnecessary borrows.
* Those warnings could cause CI to fail since CI always builds on the latest stable.
Changes
-----
* Removed the unnecessary borrows based on Clippy feedback.
Tested
-----
* There should be no functional changes, since the warning is about redundant referencing.
* All tests pass.
> Fix clippy warnings about unneeded borrows

- .github/dependabot.yml
The previous implementation overspecified this, and that ended up not even being correct (despite coming from GitHub's docs!), so the easiest solution is simply to remove things which the defaults cover for us: scheduling and rebasing.
> Fix dependabot config: specify the bare minimum

- crates/test-support/src/matchers.rs
- crates/volta-core/src/tool/registry.rs
- src/command/list/plain.rs
Info
-----
* Seems like I should have waited a couple of days before #1057, as there's a new Rust version with new compiler / clippy warnings
Changes
-----
* Removed some unused struct fields and a redundant closure
> Fix clippy warnings from Rust 1.57.0

- Cargo.lock
- Cargo.toml
- crates/volta-core/src/tool/node/fetch.rs
- crates/volta-core/src/tool/node/resolve.rs
- crates/volta-core/src/tool/registry.rs
- tests/acceptance/hooks.rs
Info
-----
* `mockito` appears to be moving away from having a static server address defined in a constant.
* For the time being, the constant still exists and works, however it is marked as deprecated.
* Unfortunately, the suggested `server_url` method as a way forward doesn't work due to how our tests are structured:
* `server_url` attempts to start the server if it isn't running, then returns the address.
* This relies on the assumption that the call to `server_url` in the code under test and the creation of the `Mock` objects happen in the same process, since the server status is shared memory.
* In our case, our acceptance tests call the `volta` and shim binaries as a child process, in order to inspect their return codes and output.
* Using `server_url` in the `volta_core` area …
> Bump mockito and suppress deprecation warnings

- Cargo.lock
- crates/volta-core/Cargo.toml
- crates/volta-core/src/style.rs
- crates/volta-core/src/tool/node/resolve.rs
- crates/volta-core/src/tool/npm/resolve.rs
- crates/volta-core/src/tool/package/install.rs
- crates/volta-core/src/tool/yarn/resolve.rs
Info
-----
* The dependabot update to `indicatif` in #1094 is failing because the API has changed slightly between versions.
Changes
-----
* Bumped `indicatif` to the latest version.
* Updated `progress_spinner` to accept the message as a `Cow<'static, str>` to match `indicatif`. This allows it to accept either a string literal or an owned string, which matches our usage.
* Removed the now-incorrect borrows of the results of `format!` when calling `progress_spinner`
Tested
-----
* All tests pass
* Manual testing confirms the spinner is still shown as expected.
> Bump indicatif to latest and update API

- Cargo.lock
- Cargo.toml
- crates/volta-core/Cargo.toml
- crates/volta-core/src/log.rs
- src/command/list/human.rs
Info
-----
* The dependabot update to `textwrap` in #1064 is failing to build, because the API changed a bit between version 0.11.0 and 0.14.2.
Changes
-----
* Bumped `textwrap` version
* Updated calls to use the new API
Tested
-----
* All tests pass, including formatting tests around `volta list`
> Bump 'textwrap' to the latest version and resolve API conflicts

- Cargo.lock
- crates/validate-npm-package-name/Cargo.toml
- crates/validate-npm-package-name/src/lib.rs
Info
-----
* The dependabot update to `percent-encoding` in #1063 is failing to build, because predefined escape sets were removed in 2.1.0.
Changes
-----
* Bumped `percent-encoding` version
* Switched to using `utf8_percent_encode`, which takes an `&str` instead of an `&[u8]`.
* Created a custom `AsciiSet` based on the definition of [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#description)
Tested
-----
* All tests for `validate-npm-package-name` pass.
> Bump 'percent_encoding' version and create appropriate escape set

- Cargo.lock
- crates/volta-core/Cargo.toml
- crates/volta-core/src/hook/tool.rs
Info
-----
* The dependabot update to `cmdline_words_parser` in #1065  is failing to build, because the API has changed from an extension trait to a bare function.
Changes
-----
* Bumped `cmdline_words_parser` version
* Switched to calling `posix_parse` instead of `StrExt::parse_cmdline_words`
Tested
-----
* All tests pass.
> Bump cmdline_words_parser and use the new API

- crates/volta-core/src/hook/tool.rs
- crates/volta-layout-macro/src/ir.rs
Info
-----
* Another new Rust release comes with new clippy lints! This time, clippy found a few places where we were unnecessarily calling `to_string` inside of a `format!` macro 🤯 
Changes
-----
* Removed the redundant `to_string` calls.
> Clean up unnecessary to_string calls

- crates/volta-core/src/run/parser.rs
Closes #1166 
Info
-----
* Our interception of `npm install --global` (and other global npm commands) relies on us setting the `prefix` configuration via an environment variable.
* However, if a user (or script) explicitly provides a prefix at the command line via `--prefix`, that will override our environment variable.
* In those cases, our intercepted install will fail since the install will go to a different location than we expect.
* At the same time, explicitly providing a prefix is an advanced option that likely means the user is doing something intentional and not trying to do a "standard" global install.
* We shouldn't try to be smarter than the user, in these cases we should skip interception entirely to prevent unexpected errors.
Changes
-----
* Updated the `has_global_flag` …
> Don't intercept npm commands with prefix flag

- crates/volta-core/src/tool/package/metadata.rs
Info
-----
* Reported in Discord: https://discord.com/channels/413753499835301908/413753499835301917/845139760993402891
* If a package has an invalid name in the `bin` hash in `package.json`, both npm and Yarn handle it by skipping over that entry, but Volta tries to create shims and then fails with an error.
* We should match the behavior of the package managers and skip over invalid entries (ones that contain path separators).
Changes
-----
* Updated the logic for parsing the `bin` hash to exclude any names that contain path separators (`/` and `\`).
Tested
-----
* Installed the example from Discord (`@ethersphere/swarm-cli`) and confirmed that it failed before the change and succeeded afterwards.
* Note: npm version 6 and lower appear to do some normalization of the `package.json` …
> Filter out invalid bins when loading package manifest

- crates/volta-core/src/project/tests.rs
Info
-----
* Another new Rust version, more useful clippy warnings.
Changes
-----
* Updated `assert_eq!` with a literal boolean to use `assert!` directly instead.
Tested
-----
* All tests pass.
* Clippy does not show any warnings or errors.
> Resolve new clippy warnings

- crates/volta-core/src/tool/yarn/fetch.rs
- crates/volta-core/src/tool/yarn/resolve.rs
- tests/acceptance/volta_install.rs
- tests/acceptance/volta_pin.rs
- tests/acceptance/volta_run.rs
- tests/smoke/autodownload.rs
- tests/smoke/volta_fetch.rs
- tests/smoke/volta_run.rs
This removes the `VOLTA_FEATURE_YARN_3` feature flag, so that Yarn3 is fully supported.
https://github.com/orgs/volta-cli/projects/1/views/1
I slightly modified some of the logic, because we are checking the `@yarnpkg/cli-dist` registry first for Yarn3, before the `yarn` registry for Yarn1, so that errors with Yarn3 don't impact Yarn1.
> Remove the feature flag to fully enable Yarn3

- crates/validate-npm-package-name/src/lib.rs
- crates/volta-core/src/error/kind.rs
- crates/volta-core/src/event.rs
- crates/volta-core/src/hook/mod.rs
- crates/volta-core/src/hook/tool.rs
- crates/volta-core/src/shim.rs
- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/toolchain/serial.rs
- crates/volta-core/src/version/mod.rs
A new Rust version, new clippy warnings :smile: This time all related to deriving `PartialEq` without also deriving `Eq`.
> Fix clippy warnings

- Cargo.lock
- crates/volta-core/Cargo.toml
- crates/volta-core/src/log.rs
This upgrade was attempted by dependabot, but the API had shifted slightly so it needed to be updated manually.
> Bump textwrap to 0.15.1

- Cargo.lock
- crates/volta-core/Cargo.toml
- crates/volta-core/src/layout/mod.rs
Closes #1074.
We can also consider removing `once_cell` crate once it's included in the standard library.
> Replace `double-checked-cell` with `once_cell`

- tests/acceptance/support/sandbox.rs
- tests/smoke/main.rs
Info
-----
* There are a couple of warnings still popping up in CI during the tests.
* One of them is another derive of `Eq`
* The other is a dead code warning around the `EnvVar` in smoke tests. While we aren't using this right now, having it around makes sense going forward (rather than adding / removing it as tests are updated to use or not use the API).
Changes
-----
* Added an `Eq` derive to the `FileBuilder` definition.
* Made the `support` module in the smoke tests `pub`, so that dead code warnings won't be generated for types used by the public API.
> Clean up warnings in the tests

- Cargo.lock
- crates/volta-core/Cargo.toml
Info
-----
* I was seeing some warnings when running `cargo clippy` manually about a version of `winapi` which will not be supported in a future Rust compiler version.
* At first, I was looking to the dependency try and trying to update `winfolder` to no longer require that version of `winapi`
* However, it became a rabbit-hole of transitive dependencies, many of which haven't been updated in many years.
* Ultimately, I discovered that we actually aren't even using `winfolder` any more.
* While looking at `Cargo.toml`, I found a few other packages that were declared in dependencies but not actually used within the code.
Changes
-----
* Removed unused dependencies from `Cargo.toml`
Tested
-----
* Verified that Volta compiles properly even with those dependencies removed from `Cargo.toml`
> Remove unused dependencies

- README.md
Grafana and Astro images are broken. So, this PR fixes it.
> wfix: grafana and astro images

- .github/workflows/api-docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- ci/docker/Dockerfile
- rust-toolchain.toml
Info
-----
* As noted in the [release announcement](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#compatibility-notes), Rust now requires a minimum of glibc 2.17
* This is higher than Volta's current minimum glibc requirement of 2.12
* We have committed to maintaining that backwards compatibility at least until we release Volta 2.0 at some point in the future.
* As a result, we need to pin our builds to use Rust 1.63 and no longer always use the latest.
Changes
-----
* Updated all CI scripts and the Linux build Dockerfile to pin to Rust 1.63
* Added a `rust-toolchain.toml` file so that developers running `cargo` locally will use the appropriate version as well (making sure we don't accidentally try to use features released after 1.63)
Tested
-----
* CI builds are currently …
> Pin Rust to 1.63 to maintain compatibility with old CentOS versions

- Cargo.lock
- crates/volta-core/Cargo.toml
- crates/volta-core/src/fs.rs
This was attempted by dependabot, but ran into issues with a change to the `Error` API. Bumping manually and resolving the `Error` issue.
> Bump retry to 2.0.0

- dev/unix/volta-install.sh
Info
-----
* In #687, we improved the reliability of the install by having cURL write out the filename directly (rather than following it with an `echo` and running into issues of extra output).
* However, some older versions of cURL (including those available by default on older systems that we nominally support) don't understand the `filename_effective` variable.
* This causes the installer to abort early with an error, despite the fact that it successfully downloaded the binary.
* From [the docs](https://everything.curl.dev/usingcurl/verbose/writeout), using `filename_effective` is mostly to handle the case where there is a `--output` set and so the file name is changed. However, in our case we're explicitly setting `--output` and _know_ what the filename is going to be.
Changes
----- …
> Avoid using curl write-out variable that isn't always supported

- .github/workflows/api-docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Use https://github.com/Swatinem/rust-cache to cache CI artifacts from cargo and speed things up
> Cache cargo artifacts to speed up CI runs

- .github/workflows/api-docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
There are a lot of deprecation warnings in our recent workflow runs (for ex. [1](https://github.com/volta-cli/volta/actions/runs/3383641697), [2](https://github.com/volta-cli/volta/actions/runs/3387570392), [3](https://github.com/volta-cli/volta/actions/runs/3387570396)).
All of these contain multiple instances of the same three things:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions-rs/toolchain, actions/upload-artifact, actions/checkout
```
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will- …
```
> chore: Update deprecated actions

- crates/volta-core/src/platform/tests.rs
- crates/volta-core/src/tool/package/manager.rs
- rust-toolchain.toml
Info
-----
* There are a couple of clippy warnings that I missed in the code review for the pnpm implementation.
* The `rust-toolchain.toml` file also doesn't contain the necessary components to let `rust-analyzer` work properly in local development environments.
Changes
-----
* Fixed the warnings with clippy's suggested fixes.
* Added `clippy` and `rustfmt` to the `components` in `rust-toolchain.toml`
Tested
-----
* Locally verified that there aren't any clippy warnings.
* Confirmed that local development works as expected.
> Fix clippy warnings and rust-toolchain.toml file

- Cargo.lock
- crates/archive/Cargo.toml
- crates/volta-core/Cargo.toml
Closes #1364 
Info
-----
* Prior to version 0.24.0, when using the `tls-rustls` feature flag, `attohttpc` would use WebPKI root certificates instead of the native certificate store for the appropriate system.
* As a result, when we switched in Volta 1.1.0 to use `rustls` instead of `native-tls`, we regressed in our certificate handling, causing issues with corporate proxies.
* In version 0.24.0, `attohttpc` [added the ability](https://github.com/sbstp/attohttpc/pull/134) to use native root certificates with rustls via the `rustls-native-certs` crate.
* This allows the root certificate finding to match that of the `native-tls` implementation.
Changes
-----
* Updated our imports of `attohttpc` to use version 0.24 and activate the `tls-rustls-native-roots` feature flag, to ensure that we are …
> Upgrade attohttpc and use native root certificates

- README.md
https://pbs.twimg.com/profile_images/1577718489330192387/rOehZ3d5_400x400.png returns 404
> chore: fix Astro logo, take Grafana and Sentry logos from GitHub

- .github/workflows/release.yml
Info
-----
* The docker CI build takes a long time to complete and can sometimes fail when building the docker image.
* However, the docker image itself shouldn't be changing often, we rarely make changes to the CI environment.
* We should be able to cache the docker image and re-use it on subsequent runs for both performance and stability.
Changes
-----
* Added the `docker/setup-buildx-action` and `docker/build-push-action` CI steps to build and cache the docker image on GitHub actions, instead of manually calling `docker build` each time.
Tested
-----
* This PR will be the testing ground, to verify that the build completes and that the cache works across runs.
* Update: Tested rerunning the build after it completed and can confirm that it loads from cache. The initial run took ~5:30 to …
> Use docker buildx to cache docker image in CI

- crates/volta-core/src/lib.rs
- crates/volta-core/src/platform/mod.rs
- crates/volta-core/src/run/mod.rs
- crates/volta-core/src/tool/mod.rs
- tests/acceptance/corrupted_download.rs
- tests/acceptance/hooks.rs
- tests/acceptance/merged_platform.rs
- tests/acceptance/volta_install.rs
- tests/acceptance/volta_pin.rs
- tests/acceptance/volta_run.rs
Info
-----
* #1273 Added support for the core pieces of `pnpm`: Instaling, pinning, and running.
* Global package installation / interception are still TODO as we need to work out the specifics of how to implement those.
* As noted in that PR, this change will break the behavior for anyone who was using `pnpm` as a global package in previous versions of Volta.
* To maintain backwards compatibility, we want to make sure that those users aren't impacted by default.
* We tackled a related issue previously with Yarn 3 support by adding a feature flag environment variable, which should work for this case as well.
Changes
-----
* Added a feature flag environment variable `VOLTA_FEATURE_PNPM` that will turn on the native pnpm support.
* Updated the install, uninstall, run, and platform checkout …
> Gate pnpm support behind a feature flag to avoid compatibility issues

- crates/volta-core/src/project/mod.rs
Yarn berry works great with single mode, but does not works if inside workspace directory. I found that this line does not respect root monorepo:
https://github.com/volta-cli/volta/blob/7827adefcb57ffe3beb7896c7ed483b24e619556/crates/volta-core/src/project/mod.rs#L176
as it expect `.pnp.js` on same level as root dir. But workspace dir does not have `.pnp.js` hence it works fine with yarn berry. like `yarn why packagename`
> fix(yarn) pnp workspace support

- ci/docker/Dockerfile
* The most recent version of Rustup depends on a newer version of `glibc` than is available in the CentOS 6-based Docker image we are using to compile the Linux version of Volta.
* This is causing CI to fail as it's not able to install the Rust compiler.
* We're intentionally using an older version of glibc to maintain compatibility with those older versions.
* Luckily, older Rustup versions are available for download.
* Updated the Dockerfile to directly fetch an older version of `rustup-init` and use that to install Rust.
> Manually fetch older version of Rustup on Linux production build

- Cargo.lock
- Cargo.toml
- crates/volta-core/Cargo.toml
- crates/volta-core/src/log.rs
- src/command/list/mod.rs
Replaces `atty` with `is-terminal` as the former is unmaintained.
> chore: replace atty with is-terminal

- Cargo.lock
- crates/archive/Cargo.toml
This only gets us part of the way to fully updated, but our MSRV and the transitive MSRV of one of zip's dependencies means we cannot yet upgrade all the way to v0.6 (latest). It is sufficient to get the vulnerability eliminated, though!
Fixes #1599
> Update to zip 0.5 to resolve bzip2 issue

- Cargo.lock
- crates/volta-core/Cargo.toml
This does not *fully* resolve our issue with our dependency on vulnerable versions of `time`, but it gets us closer. (We also need to get from zip 0.5 to 0.6!)
> Update to the latest version of Chrono

- Cargo.lock
- crates/archive/Cargo.toml
This is the second half of getting us out of the position of depending on the vulnerable version of `time`.
> Configure `zip` not to use its `time` feature

- Cargo.lock
- crates/volta-core/Cargo.toml
Just what it says on the tin. Zero functional changes, but some minor clean-up in the implementation.
> Use published version of detect-indent

- crates/volta-core/src/tool/node/mod.rs
Previously, since we were testing against a version spec of `1.2.3`, we were failing on local Apple Silicon builds because our test expectations looked for the correct (`arm64`) string, but the version check we use to avoid incorrectly trying to install non-Apple Silicon-compatible Node versions without Rosetta meant we ended up in the fallback path. Update the existing tests to use versions which will get `arm64` when run on an Apple Silicon machine, and add additional tests behind a `#[cfg(...)]` check for `macos-aarch64` to confirm the fallback works correctly.
Note that these new tests will *only* run locally at present, since we do not yet have Apple Silicon runners on GitHub, but if/when we can add those, they will run automatically there. This path should also become less important …
> Correctly (locally) test Node architecture fallback

- crates/volta-core/src/tool/mod.rs
> fixed #1311

- src/command/uninstall.rs
Following this comment from @chriskrycho:
https://github.com/volta-cli/volta/issues/1563#issuecomment-1836808073 
Resolves #1563
> Update `uninstall` command's help text with examples of what can actually be uninstalled

- .github/workflows/api-docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- ci/build-linux.sh
- ci/docker/Dockerfile
- rust-toolchain.toml
We originally pinned to 1.63 because that was the last version before Rust dropped support for older versions of `glibc` [in Rust 1.64][blog]. However, the relevant operating systems we were maintaining support for at that time (CentOS/RHEL 6) have now been end-of-life for three full years, so it seems reasonable to update to a more current version. Since no other changes to the `glibc` support have happened in the interval, we can safely update to the most current version of Rust.
[blog]: https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html
As part of this, update the RHEL 7 Dockerfile setup for building on Rust 1.74, including using updated versions of gcc and binutils.
---
**For discussion:** is this breaking? I do not think we have written down our SemVer …
> Update Rust version to 1.75

- .github/workflows/api-docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- tests/acceptance/volta_bypass.rs
This lets us use `rust-toolchain.toml` for our single source of truth for our targeted Rust version. Resolves #1618.
> Switch to actions-rust-lang/setup-rust-toolchain

- Cargo.lock
- Cargo.toml
- crates/volta-core/Cargo.toml
- crates/volta-core/src/log.rs
- src/command/list/mod.rs
As the Rust version used by `volta` has been updated to 1.75, `volta` can use `std::io::IsTerminal`.
> chore: replace is-terminal crate with std::io::IsTerminal

- Cargo.lock
- crates/volta-core/Cargo.toml
- crates/volta-core/src/style.rs
`term_size` announces that it is not maintained although it works fine, and proposes using `terminal_size` crate instead.
https://github.com/clap-rs/term_size-rs/pull/31
> chore: replace term_size with terminal_size

- Cargo.lock
- Cargo.toml
- src/cli.rs
We lost this with the Clap v4 upgrade, and it is a small nicety that users may miss. Happily, the capability exists, and is just opt-in rather than the default now.
<details><summary>Volta v1</summary>
</details>
<details><summary>Volta v2 <em>without</em> this change</summary>
</details>
<details><summary>Volta v2 <em>with</em> this change</summary>
</details>
Things to notice:
- The Clap output made a couple changes going to v4 (all of which already landed as part of #1649):
- It now puts flags after commands.
- It renamed "Subcommands" to "Commands".
- It switched from all caps to title case.
- It no longer prints `volta-completions` or similar as the name of subcommands (which is a behavior change we have wanted!).
- I made a couple design choices:
- I restored the color choices we …
> Add colors back to help output

- .github/workflows/release.yml
- .github/workflows/test.yml
We get this transitively via actions-rust-lang/setup-rust-toolchain@v1 now, and we are not using any of its configuration options, so we can simply drop it for now.
I am opening this on top of #1635 to see if it resolves the build issue there; I do not expect it to, as I think the underlying caching issue there may be a bit more finicky than this, but it is worth checking.
> Remove Swatinem/rust-cache from CI configs

- COMPATIBILITY.md
While discussing #1611, @rwjblue and I noticed that we do not have any explicit documentation of our SemVer/compatibility policy. We should specify what versions of our main targeted operating systems we support.
Additionally, this proposes that dropping support for a currently-supported version will be a major version bump for Volta—so, e.g. when #1611 itself lands, we should release 2.0 afterwards, since it will drop support for the EOL'd RHEL 6 line. As an alternative, we could consider treating operating system support similar to the way most crates treat Rust support and the way most JS packages treat Node versions: non-breaking to drop support for EOL versions.
> Describe Volta's SemVer commitments (COMPATIBILITY.md)

- Cargo.lock
- Cargo.toml
- crates/archive/Cargo.toml
- crates/archive/src/tarball.rs
- crates/volta-core/Cargo.toml
- crates/volta-core/src/tool/node/resolve.rs
- tests/acceptance/support/sandbox.rs
Replaces `hyperx` crate with `headers` crate to modernize dependencies regarding to HTTP headers. `hyperx` was released as an extraction of the `hyper` 0.11 typed header module. Today, `hyper` community decoupled the header module as `headers` crate and maintains it.
> chore: replace hyperx with headers

- Cargo.lock
- Cargo.toml
- crates/validate-npm-package-name/Cargo.toml
- crates/validate-npm-package-name/src/lib.rs
- crates/volta-core/Cargo.toml
- crates/volta-core/src/hook/mod.rs
- crates/volta-core/src/hook/tool.rs
- crates/volta-core/src/layout/mod.rs
- crates/volta-core/src/platform/tests.rs
- crates/volta-core/src/project/mod.rs
- crates/volta-core/src/run/npx.rs
- crates/volta-core/src/sync.rs
- crates/volta-core/src/tool/serial.rs
- crates/volta-core/src/toolchain/mod.rs
- src/command/list/human.rs
- src/command/list/plain.rs
`once_cell`, `lazycell`, and `lazy_static` crates have been used in the `volta` project. The crates provides similar functionality. As parts of `once_cell`'s API is stabilized at the standard library and the other parts are going on, replaces `lazycell` and `lazy_static` with `once_cell` crate.
> chore: use once_cell crate uniformly

- crates/volta-core/src/error/kind.rs
- dev/unix/install.sh.in
- dev/unix/volta-install-legacy.sh
- src/command/setup.rs
> feat: use zshenv over zshrc in setup

- src/command/list/mod.rs
`clap::ValueEnum` can be used to describe the list format.
> chore: Use clap::ValueEnum to describe list format

- Cargo.lock
- crates/archive/src/lib.rs
- crates/archive/src/tarball.rs
- crates/volta-core/Cargo.toml
- crates/volta-core/src/tool/node/resolve.rs
> chore: apply small refactoring

- crates/archive/src/tarball.rs
I merged two PRs recently that had conflicting imports. The net result was that 'main' isn't currently building because one PR removed an import that the other PR relied on.
> Re-add 'Header' import to tarball module

- crates/volta-core/src/platform/tests.rs
Info
-----
The tests of the platform resolution for the various 'volta run' scenarios were using a lazily-loaded 'const' value. Clippy raised some warnings about those, as 'const' values are actually duplicated for each location they are used, so the interior mutability wasn't helpful.
It seems that the `Lazy` behavior was actually a way to work around the fact that `Version` doesn't have a 'const' constructor, however all of the fields are `pub`, so we can construct the values directly. This allows us to have a true `const` value and use it in each test without needing extra interior mutability or cloning.
Changes
-----
* Updated the `NODE_VERSION`, `NPM_VERSION`, and `YARN_VERSION` constants used in the `cli_platform` tests to be directly defined, rather than lazy loaded.
* Changed all …
> Update cli_platform tests to use 'const' correctly

- .github/workflows/api-docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Both of these were on versions using Node 16; update to the current fixes that *and* gets us some performance improvements and bug fixes.
> chore: update GHA `checkout` and `upload-artifact`

- Cargo.lock
- crates/volta-core/Cargo.toml
- crates/volta-core/src/fs.rs
- crates/volta-core/src/layout/mod.rs
- crates/volta-core/src/shim.rs
- crates/volta-layout/src/lib.rs
- crates/volta-layout/src/v4.rs
- crates/volta-migrate/src/lib.rs
- crates/volta-migrate/src/v4.rs
- tests/acceptance/migrations.rs
Closes #1397 
Info
-----
* Huge kudos to @rcsilva83 and @Xstoudi for a bunch of iteration in #1552 on removing symlinks for Windows, to allow dropping the requirement for Developer Mode.
* Based on discussions in that PR, we had a new idea for replacing symlink shims on Windows by using scripts that call `volta run <package>`.
* This is a first-pass implementation of creating simple script-based shims for executing 3rd-party binaries on Windows.
* This should be a no-op for Unix.
Changes
-----
* Used `junction` to create NTFS junctions instead of directory symlinks (this part is directly copied from #1552)
* Updated the `shim` module to have different implementations of `create` for Unix and Windows.
* The Unix implementation is the same as it was before.
* The Windows implementation …
> Replace Windows symlinks with `volta run` scripts

- crates/volta-core/src/error/kind.rs
- src/command/uninstall.rs
- tests/acceptance/direct_uninstall.rs
- tests/acceptance/volta_uninstall.rs
Instead of parsing whatever string the user supplied as the tool name and supplying a default `VersionSpec`, attempt to parse the value as a full specifier which may include a version. This means we can provide better errors when the user passes a version. Specifically we can report that Volta does not yet support uninstalling specific versions of tools. Previously, we would report something like this:
```
warning:  No package 'typescript@5.4' found to uninstall
```
Notice that the old message treated `'typescript@5.4'` as the name of the tool, when it should have been treating it as a tool and a version specifier. Now, we instead report that uninstalling specific versions of tools is unsupported.
The original motivation here was noticing that we printed errors like that if the user tried …
> Better error messages for unsupported `uninstall` arguments

- .github/dependabot.yml
Since we added Dependabot a few years ago, they added support for this simpler way of configuring multiple directories for the same package ecosystem (see [Directories][docs] in the docs), including support for globbing.
[docs]: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories
> Simplify the Dependabot config

- Cargo.lock
I expected 0dd64304 would have done this, but: not fully? Odd.
> build(deps): update lockfile for latest `which`

- Cargo.lock
- crates/volta-core/src/log.rs
Discovered while debugging #1784: we assume a prefix of `"volta"` for all the crates in the repo, but that is simply not reflective of reality!
This raises the question of whether we *want* to standardize on that (which I think would be fine and dandy) or whether we want to collapse some of these smaller crates together, seeing as they are fairly stable and shouldn’t particularly affect our build times (which I *also* think would be fine and dandy), but I think we can defer those for later.
> Update logger config to support all internal crates

- .github/workflows/release.yml
Since `download-artifact@v2` is no longer compatible with `upload-artifact@v4`, download-artifact will also be upgraded to v4.
> Upgrade `download-artifact` action to v4

- .github/workflows/release.yml
- wix/main.wxs
Relate #1270 
A build for Windows on Arm will be added to Volta.
The changes I made include creating an msi and zip for Arm64 in my repository, and I have confirmed that it works on Windows on Arm machines.
> Support Windows Arm64 Build

- crates/archive/src/lib.rs
- crates/archive/src/tarball.rs
- crates/archive/src/zip.rs
- crates/volta-core/src/tool/node/fetch.rs
- crates/volta-core/src/tool/npm/fetch.rs
- crates/volta-core/src/tool/pnpm/fetch.rs
- crates/volta-core/src/tool/yarn/fetch.rs
Fixes #1744 
Info
-----
Currently, we make two overlapping GET requests when fetching a tarball: First, the main request to get the headers and the data stream, and then a second request to attempt to fetch the ISIZE field which holds the uncompressed size. Getting the uncompressed size lets us use the stream data after uncompressing to populate our progress bar for tarballs.
However, the extra request causes issues for some users, where the second request for the ISIZE field hangs during the TLS handshake. By removing the uncompressed size entirely and connecting the progress bar to the compressed read data, we can avoid the extra request entirely.
Changes
-----
* Removed the `uncompressed_size` method from the `Archive` trait.
* Removed the extra request for the ISIZE field from the …
> Remove extra GET for tarball uncompressed size

- Cargo.lock
- crates/archive/Cargo.toml
- crates/volta-core/src/log.rs
- src/cli.rs
- src/main.rs
The previous work on this in #1793 made it *possible* to use more log levels; this actually *uses* that new possibility. There is only a single tracing message at present, used to indicate that tracing itself is turned on, but we can use it for any future debugging work. Extracted from #1784, where we used it to help diagnose the issues underlying #1744.
> infra: enable tracing-level logging

- .github/workflows/release.yml
Info
-----
- When we added the ability to build for ARM Linux, we missed a step of updating the `needs` section for the publish CI job.
- This means that the job can potentially start before the ARM Linux build completes, which could then cause it to fail because it tries to download an artifact that hasn't been built yet.
Changes
-----
- Updated the `needs` section to include the `linux-arm` job as well.
> Update publish job to depend on all build jobs

- Cargo.lock
- crates/archive/Cargo.toml
- crates/archive/src/lib.rs
- crates/archive/src/tarball.rs
- crates/archive/src/zip.rs
Info
-----
* With the bump to our MSRV, we can now take advantage of the latest version of `zip`
* Additionally, we can take advantage of `ZipStreamReader`, which is an implementation of a streamed Zip extractor. It's marked as `unstable` so the crate authors recommend that we pin to a specific `zip` version when using it.
* The `ZipStreamReader` lets us greatly simplify the code for fetching & extracting a Zip file, making it much more analogous to the `tarball` code.
Changes
-----
* Updated the version of `zip`, keeping the same features enabled.
* Altered the implementation of `Zip` to take advantage of `ZipStreamReader`
Tested
-----
* Ran Volta locally on Windows and verified that fetching a Node version still works as expected.
> Update 'zip' to the latest version

- dev/unix/tests/install-script.bats
- dev/unix/volta-install.sh
Closes #1834 
Info
-----
Early on, we added a fast-fail function `check_architecture` to the installer. This allowed us to detect an unsupported architecture and fail early, rather than continuing and appearing to succeed only for the app to fail.
As of 2.0.0, however, we now support both x64 & ARM on all platforms, so we check the architecture as part of the normal install process. This means that the early exit is no longer necessary—an unsupported architecture will still be caught by the `parse_os_info` function before any download occurs.
Changes
-----
* Removed the `check_architecture` function and any calls to it from the installer
* Removed the tests of `check_architecture`
Tested
-----
* Ran the script locally and verified that it still downloaded the appropriate version of Volta.
> Remove early-exit check_architecture function from installer

- crates/volta-core/src/tool/mod.rs
- crates/volta-core/src/tool/node/mod.rs
- crates/volta-core/src/tool/npm/mod.rs
- crates/volta-core/src/tool/pnpm/mod.rs
- crates/volta-core/src/tool/yarn/mod.rs
Closes #1847 
Info
-----
Currently, the call-to-action suggestion to use `volta pin` is printed as part of the "success" message on every call to `volta install`. However, that message is confusing when you aren't in a project. Additionally, it's only necessary if the current project itself has a pinned version of the tool.
We actually already have a message sent after installing if the project has an overlapping version: a note that the local version is different. This message seems like the ideal place to have the CTA, so that it lets users know what they can do to update the local version in case that's what they intended.
Changes
-----
* Removed the `volta pin` CTA from the `info_installed` message
* Updated the `info_project_version` message to include a `volta pin` CTA
* Updated …
> Move pin suggestion CTA to the project version message

- crates/volta-core/src/tool/mod.rs
Closes #1845 
Info
-----
We have a helper utility `check_shim_reachable` that notifies the user if the shim for a tool they just installed is on their PATH and whether it's shadowed. However, that check currently assumes that all shims are in `VoltaHome::shim_dir`. Unfortunately, on Windows that isn't the case—we install the default shims alongside Volta itself inside of `Program Files`.
To prevent showing an unnecessary message to Windows users, we should properly check both Volta directories on Windows when validating whether a shim is properly available on the Path.
Changes
-----
* Updated `check_shim_reachable` to call a new function `find_expected_shim_dir` to determine which directory should be used as the base when checking for the shim.
* Implemented `find_expected_shim_dir` for …
> Update `check_shim_reachable` to correctly handle Windows

- Cargo.toml
Info
-----
* Despite putting a large focus on performance (and to some extent, binary size), we haven't taken advantage of Rust's ability to enable link-time optimizations (LTO).
* These optimizations can improve performance and reduce binary size, at the cost of taking longer at compilation.
Changes
-----
* Updated `Cargo.toml` to enable fat LTO in release builds of Volta
* Also added `codegen-units = 1`, which is another setting which increases final performance at the cost of compile time (see [the Rust Performance Book](https://nnethercote.github.io/perf-book/build-configuration.html) for more details).
Tested
-----
* On Windows, this results in an ~10% reduction in binary size. I didn't see any significant performance difference.
* On macOS (M2 Max), I see ~25% reduction in binary …
> Enable fat link-time optimizations in release builds

- src/command/run.rs
Fixes #1852 
Info
-----
Clap's parsing for variable-length argument lists has precedence rules for what happens when a potential vararg overlaps with a known flag value (see https://docs.rs/clap/latest/clap/struct.Arg.html#method.allow_hyphen_values):
1. If we are already in a list of variable args, the args take precedence and any potential flags are ignored (flags are treated as part of the vararg)
2. If we are _not_ already in a list of variable args, then known flags take precedence and are parsed as such, rather than starting the vararg list
As a result of this precedence, with `volta run` set up to have `args` be separate from `command`, we could run into parsing issues with commands that have flags that overlap with Volta's. For example:
```
volta run node -h
```
When parsing this, …
> Fix argument parsing for `volta run` to properly handle flags

- .github/workflows/release.yml
Info
-----
* When trying to publish v2.0.1 to Winget, there was an automated message about the install failing because it didn't have the Visual C Runtime.
* However, we should have fixed that in #1844 
* It turns out that the `setup-rust-toolchain` action we use will, by default, set a `RUSTFLAGS` environment variable.
* Then, per [the docs](https://github.com/actions-rust-lang/setup-rust-toolchain?tab=readme-ov-file#rustflags), that variable will override any `.cargo/config.toml` setting we have, which is how we set the app to statically link.
* As a result, the CI-built version of Volta actually _isn't_ currently statically linked to the C Runtime.
Changes
-----
* Updated the CI job following the suggestion in `setup-rust-toolchain` to set `rustflags` to an empty string, which prevents …
> Prevent GitHub Action from overriding RUSTFLAGS

- .github/workflows/test.yml
Info
-----
* Noted in #1861, we need to update the SHASUMS256.txt file for the installer script whenever we make changes to the installer.
* This adds a simple CI check that verifies the checksum to run on PRs, so that we can't forget to update the hash.
Changes
-----
* Added a new CI job that validates the checksum
Tested
-----
* Tested in this PR that the job passes when there are no changes to `volta-install.sh` and fails when there are changes that don't also update the `SHASUMS256.txt` file.
> Add a step to CI that validates the installer checksum

- Cargo.toml
- crates/archive/Cargo.toml
- crates/fs-utils/Cargo.toml
- crates/progress-read/Cargo.toml
- crates/test-support/Cargo.toml
- crates/validate-npm-package-name/Cargo.toml
- crates/volta-core/Cargo.toml
- crates/volta-core/src/hook/serial.rs
- crates/volta-core/src/project/mod.rs
- crates/volta-core/src/toolchain/mod.rs
- crates/volta-core/src/toolchain/serial.rs
- crates/volta-layout-macro/Cargo.toml
- crates/volta-layout/Cargo.toml
- crates/volta-migrate/Cargo.toml
- crates/volta-migrate/src/lib.rs
- crates/volta-migrate/src/v1.rs
- crates/volta-migrate/src/v2.rs
- crates/volta-migrate/src/v3.rs
- crates/volta-migrate/src/v4.rs
Seems to be able to use edition 2021.
> chore: update to edition 2021

- crates/volta-core/src/tool/node/resolve.rs
Uses `httpdate` crate to format expires. This simplify the implementation a little, and uses the same `httpdate` crate directly for encoding and decoding not depending on the specification or the internal implementation.
> chore: use httpdate to format expires

- .github/workflows/release.yml
Info
-----
When installing a package using `cargo install`, by default it ignores the lockfile for that package and installs the latest relevant dependency versions. This can be overridden by using the `--locked` flag.
Using an unlocked install is causing issues in CI, because we have our Rust version pinned to a version that is older than the MSRV for some of `cargo-wix`'s dependencies. Switching to a locked install means that the dependency versions will be repeatable and so we shouldn't have issues with Rust version mismatches.
Changes
-----
* Updated the CI task that installs `cargo wix` to use the `--locked` flag
Tested
-----
* Validating in CI
Notes
-----
* See [the Cargo book](https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile) for more info about …
> Use lockfile when installing cargo-wix in CI

- crates/test-support/src/matchers.rs
Removes the legacy numeric constant import.
> chore: remove legacy numeric constant import

- Cargo.lock
Fixes the `Cargo.lock` file.
```
error: failed to parse lock file at: /Users/runner/work/volta/volta/Cargo.lock
Caused by:
package `winreg` is specified twice in the lockfile
```
> chore: fix Cargo.lock file
