README.md
support/unix/build.sh

Make the build and install process less painful by automatically figuring out the paths to the build artifacts.

Simplify setup - automatically figure out artifact paths

---

crates/notion-core/src/style.rs
crates/notion-core/src/tool.rs
src/notion.rs

situational error styling

---

crates/notion-core/src/config.rs
crates/notion-core/src/event.rs
crates/notion-core/src/manifest.rs
crates/notion-core/src/monitor.rs
crates/notion-core/src/plugin.rs
crates/notion-core/src/serial/config.rs
crates/notion-core/src/serial/manifest.rs
crates/notion-core/src/serial/plugin.rs
crates/notion-core/src/session.rs

…instead of `package.json`.
Closes #106.

Move events reporting plugin to the user's config file

---

crates/notion-core/src/distro/node.rs
crates/notion-core/src/distro/yarn.rs
crates/notion-core/src/style.rs

Changed the "Installing" string to "Fetching", to more accurately match what is happening.
Closes #125.

Installing -> Fetching

---

crates/notion-core/src/session.rs
src/command/config.rs
src/command/current.rs
src/command/deactivate.rs
src/command/fetch.rs
src/command/help.rs
src/command/install.rs
src/command/mod.rs
src/command/shim.rs
src/command/use_.rs
src/command/version.rs
src/notion.rs

Per discussion on [#114](https://github.com/notion-cli/notion/pull/114#discussion_r212484537).

Convert Notion::go and friends to Fallible<()>.

---

crates/notion-core/src/catalog.rs
crates/notion-core/src/distro/node.rs
crates/notion-core/src/distro/yarn.rs
crates/notion-core/src/lib.rs
crates/notion-core/src/path/mod.rs

Ensure the cache dir exists when caching things

---

Cargo.lock
crates/notion-core/Cargo.toml
crates/notion-core/src/env.rs
crates/notion-core/src/image/mod.rs
crates/notion-core/src/lib.rs
crates/notion-core/src/manifest/mod.rs
crates/notion-core/src/manifest/serial.rs
crates/notion-core/src/project.rs
crates/notion-core/src/session.rs
crates/notion-core/src/tool.rs
src/command/current.rs
src/command/deactivate.rs
src/command/shim.rs

This PR implements the core abstractions for platform images.
Closes #141.

Platform images

---

.travis.yml

Makes things a bit easier to reason about (and the CI output shows duration of each individual one).

CI: Use array of scripts (instead of single long list).

---

README.md

The sample `package.json` has been moved to `dev` directory

Update the demo section of README

---

dev/unix/install.sh.in

For Unix, add a check that prompts the user and then cleans up their 0.1 install for them before reinstalling.

Installer: check for legacy installs.

---

crates/notion-core/src/inventory/mod.rs
crates/notion-core/src/inventory/serial.rs
crates/notion-core/src/version/mod.rs
tests/acceptance/notion_pin.rs
tests/acceptance/verbose_errors.rs
tests/smoke/notion_install.rs

Support `notion install node lts`

---

crates/test-support/src/paths.rs

Fix build warning about ATOMIC_USIZE_INIT

---

crates/notion-core/src/distro/node.rs
crates/notion-core/src/distro/package.rs
crates/notion-core/src/distro/yarn.rs
crates/notion-core/src/session.rs
crates/notion-core/src/style.rs

Improve tool formatting: `tool@version`.

---

crates/notion-core/src/inventory/mod.rs

- Builds on top of (and should be merged after) #344.
- Fixes #375.
- Should probably be merged after (and rebased on top of #368).

Make `inventory/mod.rs` a bit more idiomatic.

---

dev/unix/boot-install.sh

Fixes #291 
```
$ ./dev/unix/boot-install.sh
Checking for existing Notion installation
Latest version 0.3.0 already installed
```

If latest version is installed, install script notifies and exits

---

.vscode/launch.json
Cargo.lock
Cargo.toml
crates/notion-core/Cargo.toml
crates/notion-core/src/error/details.rs
crates/notion-core/src/style.rs
crates/notion-core/src/tool/mod.rs
crates/notion-core/src/version/mod.rs
crates/validate-npm-package-name/Cargo.toml
crates/validate-npm-package-name/src/lib.rs
src/command/fetch.rs
src/command/install.rs
src/command/pin.rs
tests/acceptance/notion_pin.rs
tests/acceptance/verbose_errors.rs
tests/smoke/notion_fetch.rs
tests/smoke/notion_install.rs

- Implements [RFC #32](https://github.com/notion-cli/rfcs/pull/32)

Update version handling.

---

dev/unix/install.sh.in

Installer: account for macOS' defaulting to login shells.

---

crates/volta-core/src/distro/node.rs
crates/volta-core/src/distro/package.rs
crates/volta-core/src/distro/yarn.rs
crates/volta-core/src/error/details.rs
crates/volta-core/src/error/mod.rs
crates/volta-core/src/fs.rs
crates/volta-core/src/hook/mod.rs
crates/volta-core/src/inventory/mod.rs
crates/volta-core/src/inventory/serial.rs
crates/volta-core/src/manifest/mod.rs
crates/volta-core/src/path/mod.rs
crates/volta-core/src/shell/mod.rs
crates/volta-core/src/toolchain/mod.rs

Use owned PathBuf instead of String for file system errors

---

crates/volta-core/src/tool/binary.rs

Closes #444 
During a refactor, we appear to have lost the code that checks for a user tool shebang loader and executes it correctly. This didn't affect the unix behavior since unix correctly parses `#!/usr/bin/env node`, but on Windows it means we weren't running the JS file using `node`.
Re-added the code that checks for a loader and executes it correctly for user tools.

Restore check for loader when executing a user binary

---

crates/volta-core/src/style.rs

Resolves #449.
<details><summary>initially 80-wide terminal</summary>
</details>
<details><summary>initially 80-wide terminal, then resize to 100-wide terminal</summary>
</details>
<details><summary>initially 80-wide terminal, then resize to full screen width</summary>
</details>
<details><summary>100-wide terminal</summary>
</details>
<details><summary>initially 100-wide terminal, then resize to full screen width</summary>
</details>
<details><summary>initially 100-wide terminal, then resize to 80-wide terminal</summary>
</details>
<details><summary>120-wide terminal</summary>
</details>
<details><summary>initially 120-wide terminal, then resize to 80-wide terminal</summary>
</details>

Simplify/improve wrapping of error messages.

---

dev/unix/volta-install.sh

Skip the version equality check for local dev installs

---

crates/volta-core/src/style.rs

Closes #507 
Updates `progress_spinner` to use ASCII characters on Windows, since UTF-8 isn't supported by default in `cmd`. Instead of the default UTF-8 dots that move around, it replaces it with `-\|/`, animated to look like a spinning bar.

Use ASCII characters for spinner on Windows

---

crates/volta-core/src/distro/package.rs
crates/volta-core/src/fs.rs
crates/volta-core/src/inventory/mod.rs

Rename fs:read_file_opt to read_file

---

crates/volta-core/src/manifest/mod.rs
tests/acceptance/support/sandbox.rs
tests/acceptance/volta_pin.rs

Fixing a couple of outstanding clippy / compiler warnings.

Fix clippy warnings

---

dev/unix/volta-install.sh

Closes #639 
Info
-----
The installer currently calls `volta setup`, which will modify your profile scripts. However, some users may not want all of their profile scripts to be edited by Volta, instead preferring to set up the shims in their own, custom way.
Changes
-----
* Added a new command-line option to the installer: `--skip-setup`, which will prevent the installer from running `volta setup` after unpacking the binaries.
* Also updated the logic for detecting the existing installed version to support both the 0.6.8 and 0.7.0 locations for the `volta` binary.
Tested
-----
* Ran the installer with and without the flag set, confirming that the `--skip-setup` option correctly prevents the call to `volta setup`
* Confirmed that the installer correctly detects an existing Volta 0.7.0 …

Add option to skip running 'volta setup' to installer

---

README.md

Update the "Fast/Reliable/Universal" text to match the new website.

Update high-level description to match new website

---

crates/volta-core/src/fs.rs
crates/volta-core/src/tool/package/install.rs

Info
-----
* Currently, the function `set_executable_permissions` is contained within `tool::package::install`, which is a very specific location.
* Since it is a filesystem operation, it should be a part of the utilities that we already have in `crate::fs`.
* This will also be useful going forward when `npm` installs will need this behavior as well.
Changes
-----
* Moved the logic for `set_executable_permissions` into `crate::fs::set_executable`.
* Updated package install logic to use the helper method from the `fs` module.
Tested
-----
* All tests pass, no change in functionality.

[npm] [Small] Move set_executable_permissions into fs module

---

src/command/setup.rs

Closes #718 
Info
-----
* Our current approach with `volta setup` is to only modify files that already exist.
* We only show an error if we aren't able to find _any_ files to modify.
* This creates problems when users have profile scripts for different shells than the one they are currently using, but don't have any for their current shell (which is a common situation for MacOS users with the change to using `zsh` as the default shell).
Changes
-----
* Updated the logic for modifying profile scripts to modify any files that exist, _and_ any files for the currently detected shell (using the `SHELL` environment variable).
* The only exception is `bash`, which has some issues where creating new files can cause other files to not be loaded (see …

Make 'volta setup' more robust at creating profile scripts

---

src/command/setup.rs

Closes #689 
Info
-----
* The current `volta setup` command always writes the full path to the Volta directory into profile scripts.
* This can cause problems for users who share profile scripts across computers, where the `$HOME` part of the path might be different between machines.
Changes
-----
* Updated `volta setup` to check for two conditions:
* Is `HOME` set?
* Does the `VOLTA_HOME` we are going to write begin with the value of `$HOME`?
* If both are true, then we use `$HOME` when writing profile scripts, instead of using the full path.
* If either isn't true, then we write the entire path, exactly as we did previously.
Tested
-----
* Ran `volta setup` in normal conditions and confirmed that we write `export VOLTA_HOME="$HOME/.volta"` into the profile scripts, instead of the full …

Use $HOME in profile scripts if possible

---

crates/volta-core/src/hook/tool.rs

Closes #773 
Info
-----
* As noted in the issue, our hooks are currently inadequate to handle the (common) use-case of a Node mirror.
* Adding new replacements to the `template` hooks is a backwards-compatible change we can make to improve this behavior.
* In order to support cross-platform Node mirrors, we need to provide the file extension at a minimum, however we can also use the expected/public file name as a replacement for simplicity.
Changes
-----
* Added `{{ext}}` to the distro hook replacement, pulling the extension from the expected filename.
* Note: This logic needed to be customized, since the "extension" could be multi-part, in the case of tarballs (`tar.gz`)
* Added `{{filename}}` to the distro hook replacement, using the expected filename.
Tested
-----
* Added tests around …

[Small] Add extension and filename replacements for template hooks

---

Cargo.toml
crates/volta-core/Cargo.toml
crates/volta-layout/Cargo.toml
crates/volta-migrate/Cargo.toml

Info
-----
* Starting work towards supporting `pnpm` in Volta
* Adding a feature flag so that the work can be broken up into multiple PRs without interrupting the trunk.
Changes
-----
* Added `pnpm` feature to the root project, as well as `volta-migrate`, `volta-layout`, and `volta-core`

Add feature flag for pnpm support

---

crates/volta-core/src/run/parser.rs

Info
-----
* The most recent `npm` trunk branch shows a number of new aliases for the `install` and `uninstall` commands: https://github.com/npm/cli/blob/latest/lib/utils/cmd-list.js
* We should support these as aliases that we use for intercepting the appropriate commands. While not strictly accurate since older versions of `npm` _won't_ support the alias and will likely show an "unknown command" error, it should still be safe since none of the new aliases were commands in the past.
Changes
-----
* Added new aliases (and moved them into a `const` list, instead of a series of equality checks)
Tested
-----
* Added to the unit tests to cover these new aliases as well as the existing ones.

[Small] Add support for new npm command aliases

---

dev/unix/volta-install.sh

Fix shims not created with --skip-setup

---

src/command/list/toolchain.rs

Closes #761 
Info
-----
* Our logic for determining the source of a tool for `volta list` currently has an incorrect short-circuit when we are in a project that doesn't have a Volta setting at all.
Changes
-----
* Updated the logic to correctly fall through to check the default if we have a project but no platform specified.
Tested
-----
* Locally confirmed that running `volta list` and `volta list node` from a project with no `"volta"` key works as it should.

[Small] Clean up 'volta list' source lookup behavior in non-Volta projects

---

README.md

Add projects using Volta to readme

---

.github/dependabot.yml

I *think* this is the right setup, and should more or less work. We can tweak the frequency later; I set it to 5/day for the top level and 3/day for the other crates initially just so we don't all die of Dependabot PRs. 😂

Set up a Dependabot config for the project

---

.github/dependabot.yml

Apparently #1061 *underspecified* things.

Include schedule.interval in dependabot config

---

crates/archive/src/tarball.rs

I believe this addresses #217. Just dipping my toes into the project and found something small that no one seems to have claimed.

replace unpack_isize with from_le_bytes

---

Cargo.lock
crates/volta-core/Cargo.toml
crates/volta-core/src/style.rs

This was also attempted by dependabot but foiled by API changes.

Bump indicatif to 0.17.1

---

Cargo.lock
Cargo.toml
RELEASES.md

Ideally would like to write a short blog post about the changes (and potentially previewing the ongoing pnpm work as well), but I don't want to completely block this if that doesn't happen on a reasonable time frame.
Will need to do a bunch of testing, especially around the new installer.
Closes #1333

Version 1.1.0

---

README.md

| Before | After |
|:-:|:-:|
|![](https://pbs.twimg.com/profile_images/1290672565690695681/0G4bie6b_400x400.jpg)|![](https://raw.githubusercontent.com/microsoft/TypeScript-Website/v2/packages/typescriptlang-org/static/branding/ts-logo-512.svg)|

Fix TypeScript logo

---

Cargo.lock
Cargo.toml
src/cli.rs
src/command/completions.rs
src/command/fetch.rs
src/command/install.rs
src/command/list/mod.rs
src/command/pin.rs
src/command/run.rs
src/command/setup.rs
src/command/uninstall.rs
src/command/use.rs
src/command/which.rs
src/main.rs

chore: update to clap 4

---

Cargo.lock
Cargo.toml
crates/archive/Cargo.toml
crates/volta-core/Cargo.toml

chore: Update http dependencies

---

Cargo.lock
Cargo.toml
crates/test-support/Cargo.toml

chore: Resolve unused dependencies

---

src/cli.rs
src/command/completions.rs
src/command/list/mod.rs
src/command/run.rs

chore: refactor clap config

---

Cargo.lock

Updates some dependencies to reduce transitive dependencies.

chore: update dependency to reduce transitive dependency

---

README.md

Fixes #1883 (thanks for flagging that up, @alefteris!).

Remove Astro and Grafana from README.md

---

crates/volta-core/src/project/mod.rs
src/volta-migrate.rs

Simplifies the conditional expressions.

chore: simplify conditional expression

---

crates/volta-core/src/platform/mod.rs
crates/volta-core/src/run/parser.rs
crates/volta-core/src/version/mod.rs

Removes the needless lifetimes.

chore: remove needless lifetime
